//>>built
define(["dojo/_base/declare","dojo/_base/lang","dojo/_base/array","dojo/_base/Deferred","dojo/_base/json","dojo/has","dojo/io-query","esri/kernel","esri/request","esri/deferredUtils","esri/geometry/normalizeUtils","esri/tasks/Task","esri/tasks/FeatureSet","esri/tasks/JobInfo","esri/tasks/GPMessage","esri/tasks/LinearUnit","esri/tasks/DataFile","esri/tasks/RasterData","esri/tasks/Date","esri/tasks/ParameterValue","esri/tasks/GPResultImageLayer","esri/layers/MapImage"],function(m,h,p,n,k,D,q,E,j,o,r,s,t,l,u,v,w,x,y,z,A,B){m=m(s,{declaredClass:"esri.tasks.Geoprocessor",
_eventMap:{"execute-complete":["results","messages"],"get-result-data-complete":["result"],"get-result-image-complete":["mapImage"],"get-result-image-layer-complete":["layer"],"job-cancel":["jobInfo"],"job-complete":["jobInfo"],"status-update":["jobInfo"]},constructor:function(){this._jobUpdateHandler=h.hitch(this,this._jobUpdateHandler);this._getJobStatus=h.hitch(this,this._getJobStatus);this._getResultDataHandler=h.hitch(this,this._getResultDataHandler);this._getResultImageHandler=h.hitch(this,
this._getResultImageHandler);this._executeHandler=h.hitch(this,this._executeHandler);this._updateTimers=[];this.registerConnectEvents()},updateDelay:1E3,processSpatialReference:null,outputSpatialReference:null,outSpatialReference:null,setUpdateDelay:function(a){this.updateDelay=a},setProcessSpatialReference:function(a){this.processSpatialReference=a},setOutputSpatialReference:function(a){this._setOutSR(a)},setOutSpatialReference:function(a){this._setOutSR(a)},__msigns:[{n:"execute",c:3,a:[{i:0,p:["*"]}],
e:2,f:1},{n:"submitJob",c:4,a:[{i:0,p:["*"]}],e:3}],_setOutSR:function(a){this.outSpatialReference=this.outputSpatialReference=a},_getOutSR:function(){return this.outSpatialReference||this.outputSpatialReference},_gpEncode:function(a,d,b){for(var f in a){var c=a[f];h.isArray(c)?a[f]=k.toJson(p.map(c,function(a){return this._gpEncode({item:a},!0).item},this)):c instanceof Date&&(a[f]=c.getTime())}return this._encode(a,d,b)},_decode:function(a){var d=a.dataType,b=new z(a);if(-1!==p.indexOf(["GPBoolean",
"GPDouble","GPLong","GPString"],d))return b;if("GPLinearUnit"===d)b.value=new v(b.value);else if("GPFeatureRecordSetLayer"===d||"GPRecordSet"===d)b.value=new t(b.value);else if("GPDataFile"===d)b.value=new w(b.value);else if("GPDate"===d)a=b.value,b.value=h.isString(a)?new y({date:a}):new Date(a);else if("GPRasterData"===d||"GPRasterDataLayer"===d)a=a.value.mapImage,b.value=a?new B(a):new x(b.value);else if(-1!==d.indexOf("GPMultiValue:")){var f=d.split(":")[1],a=b.value;b.value=p.map(a,function(a){return this._decode({paramName:"_name",
dataType:f,value:a}).value},this)}else console.log(this.declaredClass+" : GP Data type not handled. : "+b.dataType),b=null;return b},submitJob:function(a,d,b,f,c){var e=this._getOutSR(),g=c.assembly,a=this._gpEncode(h.mixin({},this._url.query,{f:"json","env:outSR":e?e.wkid||k.toJson(e.toJson()):null,"env:processSR":this.processSpatialReference?this.processSpatialReference.wkid||k.toJson(this.processSpatialReference.toJson()):null},a),null,g&&g[0]),i=this._jobUpdateHandler,C=this._errorHandler;return j({url:this._url.path+
"/submitJob",content:a,callbackParamName:"callback",load:function(a,e){i(a,e,!1,d,b,c.dfd)},error:function(a){C(a,f,c.dfd)}})},_jobUpdateHandler:function(a,d,b,f,c,e){var g=a.jobId,d=new l(a);this._successHandler([d],"onStatusUpdate",c,b&&e);if(!b)switch(clearTimeout(this._updateTimers[g]),this._updateTimers[g]=null,e&&e.progress(d),a.jobStatus){case l.STATUS_SUBMITTED:case l.STATUS_EXECUTING:case l.STATUS_WAITING:case l.STATUS_NEW:var i=this._getJobStatus;this._updateTimers[g]=setTimeout(function(){i(g,
b,f,c,e)},this.updateDelay);break;default:this._successHandler([d],"onJobComplete",f,e)}},_getJobStatus:function(a,d,b,f,c){var e=this._jobUpdateHandler;j({url:this._url.path+"/jobs/"+a,content:h.mixin({},this._url.query,{f:"json"}),callbackParamName:"callback",load:function(a,i){e(a,i,d,b,f,c)},error:this._errorHandler})},_getResultDataHandler:function(a,d,b,f,c){try{this._successHandler([this._decode(a)],"onGetResultDataComplete",b,c)}catch(e){this._errorHandler(e,f,c)}},getResultData:function(a,
d,b,f){var c=this._getResultDataHandler,e=this._errorHandler,g=new n(o._dfdCanceller);g._pendingDfd=j({url:this._url.path+"/jobs/"+a+"/results/"+d,content:h.mixin({},this._url.query,{f:"json",returnType:"data"}),callbackParamName:"callback",load:function(a,e){c(a,e,b,f,g)},error:function(a){e(a,f,g)}});return g},checkJobStatus:function(a,d,b){var f=this._jobUpdateHandler,c=this._errorHandler,e=new n(o._dfdCanceller);e._pendingDfd=j({url:this._url.path+"/jobs/"+a,content:h.mixin({},this._url.query,
{f:"json"}),callbackParamName:"callback",load:function(a,b){f(a,b,!0,null,d,e)},error:function(a){c(a,b,e)}});return e},cancelJob:function(a,d,b){var f=this._errorHandler,c=new n(o._dfdCanceller);c._pendingDfd=j({url:this._url.path+"/jobs/"+a+"/cancel",content:h.mixin({},this._url.query,{f:"json"}),callbackParamName:"callback",load:h.hitch(this,function(a){this._successHandler([a],"onJobCancel",d,c)}),error:function(a){f(a,b,c)}});return c},execute:function(a,d,b,f){var c=this._getOutSR(),e=f.assembly,
a=this._gpEncode(h.mixin({},this._url.query,{f:"json","env:outSR":c?c.wkid||k.toJson(c.toJson()):null,"env:processSR":this.processSpatialReference?this.processSpatialReference.wkid||k.toJson(this.processSpatialReference.toJson()):null},a),null,e&&e[0]),g=this._executeHandler,i=this._errorHandler;return j({url:this._url.path+"/execute",content:a,callbackParamName:"callback",load:function(a,c){g(a,c,d,b,f.dfd)},error:function(a){i(a,b,f.dfd)}})},_executeHandler:function(a,d,b,f,c){try{var e=a.results,
g,i,h=a.messages;for(g=0,i=e.length;g<i;g++)e[g]=this._decode(e[g]);for(g=0,i=h.length;g<i;g++)h[g]=new u(h[g]);this._successHandler([e,h],"onExecuteComplete",b,c)}catch(j){this._errorHandler(j,f,c)}},_getResultImageHandler:function(a,d,b,f,c){try{this._successHandler([this._decode(a)],"onGetResultImageComplete",b,c)}catch(e){this._errorHandler(e,f,c)}},getResultImage:function(a,d,b,f,c){var e=this._getResultImageHandler,g=this._errorHandler,b=this._gpEncode(h.mixin({},this._url.query,{f:"json"},
b.toJson())),i=new n(o._dfdCanceller);i._pendingDfd=j({url:this._url.path+"/jobs/"+a+"/results/"+d,content:b,callbackParamName:"callback",load:function(a,b){e(a,b,f,c,i)},error:function(a){g(a,c,i)}});return i},cancelJobStatusUpdates:function(a){clearTimeout(this._updateTimers[a]);this._updateTimers[a]=null},getResultImageLayer:function(a,d,b,f){a=this._url.path+"/jobs/"+a+"/results/"+d;this._url.query&&(a+="?"+q.objectToQuery(this._url.query));b=new A(a,{imageParameters:b},!0);this.onGetResultImageLayerComplete(b);
f&&f(b);return b},onStatusUpdate:function(){},onJobComplete:function(){},onExecuteComplete:function(){},onGetResultDataComplete:function(){},onGetResultImageComplete:function(){},onGetResultImageLayerComplete:function(){},onJobCancel:function(){}});r._createWrappers(m);return m});