//>>built
define(["dojo/_base/declare","dojo/_base/lang","dojo/_base/array","dojo/_base/json","dojo/_base/Deferred","dojo/has","esri/kernel","esri/lang","esri/deferredUtils","esri/tasks/Task","esri/renderers/SimpleRenderer","esri/geometry/scaleUtils","esri/tasks/Geoprocessor","esri/tasks/PrintTemplate","require","require"],function(r,g,k,o,s,z,A,p,t,u,v,w,x,y){return r(u,{declaredClass:"esri.tasks.PrintTask",constructor:function(b,h){this.url=b;this.printGp=new x(this.url);this._handler=g.hitch(this,this._handler);if(h&&h.async)this.async=
h.async},_handler:function(b,h,a,d,c){try{var e;this.async?"esriJobSucceeded"===b.jobStatus&&this.printGp.getResultData(b.jobId,"Output_File",g.hitch(this,function(b){e=b.value;this._successHandler([e],"onComplete",a,c)})):(e=b[0].value,this._successHandler([e],"onComplete",a,c))}catch(f){this._errorHandler(f,d,c)}},execute:function(b,h,a){var d=this._handler,c=this._errorHandler,e=b.template||new y,f=e.exportOptions,i;f&&(i={outputSize:[f.width,f.height],dpi:f.dpi});this._preserveScale=!1===e.preserveScale?
!1:!0;var f=e.layoutOptions,l,q=[];if(f){this.legendAll=!1;f.legendLayers?k.forEach(f.legendLayers,function(a){var b={};b.id=a.layerId;if(a.subLayerIds)b.subLayerIds=a.subLayerIds;q.push(b)}):this.legendAll=!0;var j,m;if("Miles"===f.scalebarUnit||"Kilometers"===f.scalebarUnit)j="Kilometers",m="Miles";else if("Meters"===f.scalebarUnit||"Feet"===f.scalebarUnit)j="Meters",m="Feet";l={Miles:"mi",Kilometers:"km",Yards:"yd",Feet:"ft",Meters:"m"};l={titleText:f.titleText,authorText:f.authorText,copyrightText:f.copyrightText,
customTextElements:f.customTextElements,scaleBarOptions:{metricUnit:j,metricLabel:l[j],nonMetricUnit:m,nonMetricLabel:l[m]},legendOptions:{operationalLayers:q}}}j=this._getPrintDefinition(b.map);if(b.outSpatialReference)j.mapOptions.spatialReference=b.outSpatialReference.toJson();if(b.template&&p.isDefined(b.template.showAttribution))j.mapOptions.showAttribution=b.template.showAttribution;g.mixin(j,{exportOptions:i,layoutOptions:l});this.allLayerslegend&&g.mixin(j.layoutOptions,{legendOptions:{operationalLayers:this.allLayerslegend}});
e={Web_Map_as_JSON:o.toJson(p.fixJson(j)),Format:e.format,Layout_Template:e.layout};b.extraParameters&&(e=g.mixin(e,b.extraParameters));var n=new s(t._dfdCanceller),b=function(b,c){d(b,c,h,a,n)};i=function(b){c(b,a,n)};n._pendingDfd=this.async?this.printGp.submitJob(e,b,null,i):this.printGp.execute(e,b,i);return n},onComplete:function(){},_multipointLayer:function(){this.layerDefinition={name:"multipointLayer",geometryType:"esriGeometryMultipoint",drawingInfo:{renderer:null}};this.featureSet={geometryType:"esriGeometryMultipoint",
features:[]}},_polygonLayer:function(){this.layerDefinition={name:"polygonLayer",geometryType:"esriGeometryPolygon",drawingInfo:{renderer:null}};this.featureSet={geometryType:"esriGeometryPolygon",features:[]}},_pointLayer:function(){this.layerDefinition={name:"pointLayer",geometryType:"esriGeometryPoint",drawingInfo:{renderer:null}};this.featureSet={geometryType:"esriGeometryPoint",features:[]}},_polylineLayer:function(){this.layerDefinition={name:"polylineLayer",geometryType:"esriGeometryPolyline",
drawingInfo:{renderer:null}};this.featureSet={geometryType:"esriGeometryPolyline",features:[]}},_createFeatureCollection:function(b){var h=new this._polygonLayer,a=new this._polylineLayer,d=new this._pointLayer,c=new this._multipointLayer;if("esri.layers.FeatureLayer"===b.declaredClass)h.layerDefinition.name=a.layerDefinition.name=d.layerDefinition.name=c.layerDefinition.name=b.name||b.id;b.renderer&&!g.isFunction(b.renderer.attributeField)?(h.layerDefinition.drawingInfo.renderer=b.renderer.toJson(),
a.layerDefinition.drawingInfo.renderer=b.renderer.toJson(),d.layerDefinition.drawingInfo.renderer=b.renderer.toJson(),c.layerDefinition.drawingInfo.renderer=b.renderer.toJson()):(delete h.layerDefinition.drawingInfo,delete a.layerDefinition.drawingInfo,delete d.layerDefinition.drawingInfo,delete c.layerDefinition.drawingInfo);if(b.fields)h.layerDefinition.fields=b.fields,a.layerDefinition.fields=b.fields,d.layerDefinition.fields=b.fields,c.layerDefinition.fields=b.fields;var e,f;for(f=0;f<b.graphics.length;f++){var i=
b.graphics[f];if(!1!==i.visible&&i.geometry){e=i.toJson();e.symbol&&e.symbol.outline&&e.symbol.outline.color&&e.symbol.outline.color[3]&&(e.symbol.outline.color[3]=255);if(b.renderer&&g.isFunction(b.renderer.attributeField)&&!e.symbol)e.symbol=b.renderer.getSymbol(i)?b.renderer.getSymbol(i).toJson():e.symbol;switch(i.geometry.type){case "polygon":h.featureSet.features.push(e);break;case "polyline":a.featureSet.features.push(e);break;case "point":d.featureSet.features.push(e);break;case "multipoint":c.featureSet.features.push(e)}}}e=
[];0<d.featureSet.features.length&&e.push(d);0<a.featureSet.features.length&&e.push(a);0<h.featureSet.features.length&&e.push(h);0<c.featureSet.features.length&&e.push(c);return{id:b.id,opacity:b.opacity,minScale:b.minScale||0,maxScale:b.maxScale||0,featureCollection:{layers:e}}},_getPrintDefinition:function(b){var h={operationalLayers:this._createOperationalLayers(b)},a=b.extent,d=b.spatialReference;if(b.spatialReference._isWrappable())a=a._normalize(!0),d=a.spatialReference;a={mapOptions:{showAttribution:b.showAttribution,
extent:a.toJson(),spatialReference:d.toJson()}};this._preserveScale&&g.mixin(a.mapOptions,{scale:w.getScale(b)});b.timeExtent&&g.mixin(a.mapOptions,{time:[b.timeExtent.startTime.getTime(),b.timeExtent.endTime.getTime()]});b={};g.mixin(b,a,h);return b},_createOperationalLayers:function(b){var h,a,d,c,e=[],f=[];this.allLayerslegend=this.legendAll?[]:null;for(h=0;h<b.layerIds.length;h++)if(a=b.getLayer(b.layerIds[h]),a.loaded&&a.visible&&-1===k.indexOf(e,a.id))switch(a.credential&&-1===a.url.indexOf("token=")&&
(a.url+="?token="+a.credential.token),d=a.declaredClass,c={id:a.id,title:a.id,opacity:a.opacity,minScale:a.minScale||0,maxScale:a.maxScale||0},d){case "esri.layers.ArcGISDynamicMapServiceLayer":var i=[];a._params.dynamicLayers?(d=o.fromJson(a._params.dynamicLayers),k.forEach(d,function(a){i.push({id:a.id,layerDefinition:a})})):k.forEach(a.layerInfos,function(b){var c={id:b.id,layerDefinition:{definitionExpression:null,layerTimeOptions:null}};if(a.layerDefinitions&&a.layerDefinitions[b.id])c.layerDefinition.definitionExpression=
a.layerDefinitions[b.id];if(a.layerTimeOptions&&a.layerTimeOptions[b.id])c.layerDefinition.layerTimeOptions=a.layerTimeOptions[b.id];(c.layerDefinition.definitionExpression||c.layerDefinition.layerTimeOptions)&&i.push(c)});c=g.mixin(c,{url:a.url,visibleLayers:a._params.layers?a.visibleLayers:null,layers:i});f.push(c);this.allLayerslegend&&this.allLayerslegend.push({id:a.id,subLayerIds:a.visibleLayers});break;case "esri.layers.ArcGISImageServiceLayer":c=g.mixin(c,{url:a.url,bandIds:a.bandIds,compressionQuality:a.compressionQuality,
format:a.format,interpolation:a.interpolation});a.mosaicRule&&g.mixin(c,{mosaicRule:a.mosaicRule.toJson()});a.renderingRule&&g.mixin(c,{renderingRule:a.renderingRule.toJson()});f.push(c);this.allLayerslegend&&this.allLayerslegend.push({id:a.id});break;case "esri.layers.WMSLayer":c=g.mixin(c,{url:a.url,title:a.title,type:"wms",version:a.version,transparentBackground:a.imageTransparency,visibleLayers:a.visibleLayers});f.push(c);this.allLayerslegend&&this.allLayerslegend.push({id:a.id,subLayerIds:a.visibleLayers});
break;case "esri.virtualearth.VETiledLayer":d=a.mapStyle;"aerialWithLabels"===d&&(d="Hybrid");c=g.mixin(c,{visibility:a.visible,type:"BingMaps"+d,culture:a.culture,key:a.bingMapsKey});f.push(c);break;case "esri.layers.OpenStreetMapLayer":c=g.mixin(c,{type:"OpenStreetMap",url:a.tileServers[0]});f.push(c);break;case "esri.layers.WMTSLayer":c=g.mixin(c,{url:a.url,type:"wmts",layer:a.layerInfos[0].identifier,style:a.layerInfos[0].style,format:a.layerInfos[0].format,tileMatrixSet:a.layerInfos[0].tileMatrixSet});
f.push(c);break;case "esri.layers.MapImageLayer":d=a.getImages();k.forEach(d,function(b,d){b.href&&(c={id:a.id+"_image"+d,type:"image",title:a.id,minScale:a.minScale||0,maxScale:a.maxScale||0,opacity:a.opacity,extent:b.extent.toJson(),url:b.href},f.push(c))});break;case "esri.layers.WebTiledLayer":d=a.url.replace(/\$\{/g,"{");c=g.mixin(c,{type:"WebTiledLayer",urlTemplate:d,credits:a.copyright});if(a.subDomains&&0<a.subDomains.length)c.subDomains=a.subDomains;f.push(c);break;default:if(a.getTileUrl||
a.getImageUrl)c=g.mixin(c,{url:a.url}),f.push(c)}for(h=0;h<b.graphicsLayerIds.length;h++)if(a=b.getLayer(b.graphicsLayerIds[h]),a.loaded&&a.visible&&-1===k.indexOf(e,a.id))switch(d=a.declaredClass,d){case "esri.layers.FeatureLayer":if(a.url&&a.renderer&&g.isString(a.renderer.attributeField)&&a._getField(a.renderer.attributeField,!0))if(a.credential&&-1===a.url.indexOf("token=")&&(a.url+="?token="+a.credential.token),c={id:a.id,url:a.url,title:a.id,opacity:a.opacity,minScale:a.minScale||0,maxScale:a.maxScale||
0,layerDefinition:{drawingInfo:{renderer:a.renderer.toJson()}}},a._params.source&&(d=a._params.source.toJson(),g.mixin(c.layerDefinition,{source:d})),a.getDefinitionExpression()&&g.mixin(c.layerDefinition,{definitionExpression:a.getDefinitionExpression()}),2!==a.mode)0<a.getSelectedFeatures().length&&(d=k.map(a.getSelectedFeatures(),function(b){return b.attributes[a.objectIdField]}),0<d.length&&a.getSelectionSymbol()&&g.mixin(c,{selectionObjectIds:d,selectionSymbol:a.getSelectionSymbol().toJson()}));
else{d=k.map(a.getSelectedFeatures(),function(b){return b.attributes[a.objectIdField]});if(0===d.length||!a._params.drawMode)break;g.mixin(c.layerDefinition,{objectIds:d});d=null;a.getSelectionSymbol()&&(d=new v(a.getSelectionSymbol()));g.mixin(c.layerDefinition.drawingInfo,{renderer:d&&d.toJson()})}else c=this._createFeatureCollection(a);f.push(c);this.allLayerslegend&&this.allLayerslegend.push({id:a.id});break;case "esri.layers.GraphicsLayer":c=this._createFeatureCollection(a),f.push(c),this.allLayerslegend&&
this.allLayerslegend.push({id:a.id})}b.graphics&&0<b.graphics.graphics.length&&(c=this._createFeatureCollection(b.graphics),f.push(c));return f}})});