//>>built
define(["dojo/_base/declare","dojo/_base/lang","dojo/_base/connect","dojo/_base/array","dojo/_base/Color","dojo/has","esri/kernel","esri/lang","esri/sniff","esri/toolbars/_toolbar","esri/toolbars/_Box","esri/toolbars/_GraphicMover","esri/toolbars/_VertexEditor","esri/symbols/SimpleMarkerSymbol","esri/symbols/SimpleLineSymbol"],function(q,m,i,h,c,k,v,p,w,r,s,t,u,f,d){var j=q(r,{declaredClass:"esri.toolbars.Edit",constructor:function(a,b){this._map=a;this._tool=0;if(this._map.loaded)this._scratchGL=a.graphics;else var e=
i.connect(this._map,"onLoad",this,function(){i.disconnect(e);e=null;this._scratchGL=this._map.graphics});var g=k("esri-touch")||k("esri-pointer");this._defaultOptions=m.mixin({vertexSymbol:new f(f.STYLE_CIRCLE,g?20:12,new d(d.STYLE_SOLID,new c([0,0,0,0.5]),1),new c([128,128,128])),ghostVertexSymbol:new f(f.STYLE_CIRCLE,g?18:10,new d(d.STYLE_SOLID,new c([0,0,0,0.5]),1),new c([255,255,255,0.75])),ghostLineSymbol:new d(d.STYLE_DOT,new c([128,128,128]),2),allowDeleteVertices:!0,allowAddVertices:!0,rotateHandleOffset:g?
24:16,boxLineSymbol:new d(d.STYLE_DASH,new c([64,64,64]),1),boxHandleSymbol:new f(f.STYLE_SQUARE,g?16:9,new d(d.STYLE_SOLID,new c([0,0,0,0.5]),1),new c([255,255,255,0.75]))},b||{})},activate:function(a,b,e){this.deactivate();this._graphic=b;this._options=m.mixin(m.mixin({},this._defaultOptions),e||{});var g=j.MOVE,e=j.EDIT_VERTICES,d=j.SCALE,c=j.ROTATE,f=!1,h=!1,k=!1,l=this._map,n=l.spatialReference,o=b.geometry.spatialReference;this._geo=!(!n||!o||n.equals(o)||!(n.isWebMercator()&&4326===o.wkid));
(a&g)===g&&(f=this._enableMove(b));g=(a&d)===d;c=(a&c)===c;if(g||c)k=this._enableBoxEditing(b,g,c);(a&e)===e&&(h=this._enableVertexEditing(b));if(!f&&!h&&!k)throw Error("[esri.toolbars.Edit::activate] Unable to activate the tool. Check if the tool is valid for the given geometry type.");if(this._tool=a)this._mapPanEndHandle=i.connect(l,"onPanEnd",this,this._mapPanEndHandler),this._mapExtChgHandle=i.connect(l,"onExtentChange",this,this._mapExtentChangeHandler),this.onActivate(this._tool,b);l.snappingManager&&
(f||h)&&l.snappingManager._startSelectionLayerQuery()},deactivate:function(){var a=this._tool,b=this._graphic;if(a){var e=!!this._modified;this._clear();i.disconnect(this._mapPanEndHandle);i.disconnect(this._mapExtChgHandle);this._graphic=this._geo=this._mapPanEndHandle=this._mapExtChgHandle=null;this.onDeactivate(a,b,{isModified:e});this._map.snappingManager&&this._map.snappingManager._stopSelectionLayerQuery()}},refresh:function(){this._refreshMoveables(!0)},getCurrentState:function(){return{tool:this._tool,
graphic:this._graphic,isModified:!!this._modified}},onActivate:function(){},onDeactivate:function(){},onGraphicMoveStart:function(){},onGraphicFirstMove:function(){this._modified=!0},onGraphicMove:function(){},onGraphicMoveStop:function(){},onGraphicClick:function(){},onVertexMoveStart:function(){},onVertexFirstMove:function(){this._modified=!0},onVertexMove:function(){},onVertexMoveStop:function(){},onVertexAdd:function(){this._modified=!0},onVertexClick:function(){},onVertexMouseOver:function(){},
onVertexMouseOut:function(){},onVertexDelete:function(){this._modified=!0},onScaleStart:function(){},onScaleFirstMove:function(){this._modified=!0},onScale:function(){},onScaleStop:function(){},onRotateStart:function(){},onRotateFirstMove:function(){this._modified=!0},onRotate:function(){},onRotateStop:function(){},_eventMap:{activate:["tool","graphic"],deactivate:["tool","graphic","info"],"graphic-move-start":["graphic"],"graphic-first-move":["graphic"],"graphic-move":["graphic","transform"],"graphic-move-stop":["graphic",
"transform"],"graphic-click":["graphic","info"],"vertex-move-start":["graphic","vertexinfo"],"vertex-first-move":["graphic","vertexinfo"],"vertex-move":["graphic","vertexinfo","transform"],"vertex-move-stop":["graphic","vertexinfo","transform"],"vertex-add":["graphic","vertexinfo"],"vertex-click":["graphic","vertexinfo"],"vertex-mouse-over":["graphic","vertexinfo"],"vertex-mouse-out":["graphic","vertexinfo"],"vertex-delete":["graphic","vertexinfo"],"scale-start":["graphic"],"scale-first-move":["graphic"],
scale:["graphic","info"],"scale-stop":["graphic","info"],"rotate-start":["graphic"],"rotate-first-move":["graphic"],rotate:["graphic","info"],"rotate-stop":["graphic","info"]},_enableMove:function(a){var b=this._map;switch(a.geometry.type){case "point":case "polyline":case "polygon":return this._graphicMover=new t(a,b,this),!0}return!1},_enableVertexEditing:function(a){var b=this._map;switch(a.geometry.type){case "multipoint":case "polyline":case "polygon":return this._vertexEditor=u.create(a,b,this),
!0}return!1},_enableBoxEditing:function(a,b,e){var c=this._map;switch(a.geometry.type){case "polyline":case "polygon":return this._boxEditor=new s(a,c,this,b,e,this._options.uniformScaling),!0}return!1},_disableMove:function(){var a=this._graphicMover;if(a)a.destroy(),this._graphicMover=null},_disableVertexEditing:function(){var a=this._vertexEditor;if(a)a.destroy(),this._vertexEditor=null},_disableBoxEditing:function(){var a=this._boxEditor;if(a)a.destroy(),this._boxEditor=null},_clear:function(){this._disableMove();
this._disableVertexEditing();this._disableBoxEditing();this._tool=0;this._modified=!1},_mapPanEndHandler:function(){this._refreshMoveables()},_mapExtentChangeHandler:function(a,b,c){c&&this._refreshMoveables()},_refreshMoveables:function(a){var b=h.filter([this._graphicMover,this._vertexEditor,this._boxEditor],p.isDefined);h.forEach(b,function(b){b.refresh(a)})},_beginOperation:function(a){h.forEach(this._getAffectedTools(a),function(a){a.suspend()})},_endOperation:function(a){h.forEach(this._getAffectedTools(a),
function(a){a.resume()})},_getAffectedTools:function(a){var b=[];switch(a){case "MOVE":b=[this._vertexEditor,this._boxEditor];break;case "VERTICES":b=[this._boxEditor];break;case "BOX":b=[this._vertexEditor]}return b=h.filter(b,p.isDefined)}});m.mixin(j,{MOVE:1,EDIT_VERTICES:2,SCALE:4,ROTATE:8});return j});