language: node_js
node_js:
  - "4"
before_install:
  - npm install -g npm
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
notifications:
  email:
    on_success: change
    on_failure: change
sudo: false
