//>>built
define(["dojo/_base/declare","dojo/_base/html","dojo/_base/lang","dojo/_base/sniff","dojo/_base/connect","dojo/_base/event","esri/kernel","esri/Evented","esri/geometry/Point","esri/geometry/ScreenPoint"],function(l,m,h,e,i,g,j,n,o,k){var b=i.connect,d=i.disconnect;return l([n],{declaredClass:"esri.MouseEvents",doubleClickDuration:300,minWheelValue:1,maxWheelValue:1,mozWheelDivisor:-1!==e("mac")?1:3,wheelDivisor:2>e("chrome")?360:120,preventPageScroll:!0,map:null,constructor:function(a,c){this.node=a;h.mixin(this,
c);var f=function(a){g.stop(a);return!1};e("mozilla")&&m.style(a,"MozUserSelect","none");this._handles=[b(a,"onselectstart",f),b(a,"ondragstart",f),b(a,"onmouseenter",this,this._onMouseEnterHandler),b(a,"onmouseleave",this,this._onMouseLeaveHandler),b(a,"onmousedown",this,this._onMouseDownHandler),b(a,"onclick",this,this._onClickHandler),b(a,"ondblclick",this,this._onDblClickHandler)];this._onMouseMoveHandler_connect=b(a,"onmousemove",this,this._onMouseMoveHandler);this._onMouseUpHandler_connect=
b(a,"onmouseup",this,this._onMouseUpHandler);this._fireClickEvent=h.hitch(this,this._fireClickEvent);this._initialDuration=this.doubleClickDuration;this.preventPageScroll=(f=this.map)?f.isScrollWheelZoom||f.isScrollWheelPan:this.preventPageScroll;this.enableMouseWheel(!1)},_fire:function(a,c){if(this[a])this[a](c);if(this.map&&this.map[a])this.map[a](c)},_processEvent:function(a){var a=g.fix(a,a.target),c=this.map,b=c&&c.position;if(b)a.screenPoint="DOMMouseScroll"===a.type&&3>e("ff")?new k(window.scrollX+
a.screenX-b.x,window.scrollY+a.screenY-b.y):new k(a.pageX-b.x,a.pageY-b.y),a.mapPoint=c.extent?c.toMap(a.screenPoint):new o;a.numPoints=0;return a},_onMouseEnterHandler:function(a){d(this._onKeyDown_connect);d(this._onKeyUp_connect);this._onKeyDown_connect=b(document,"onkeydown",this,this._onKeyDownHandler);this._onKeyUp_connect=b(document,"onkeyup",this,this._onKeyUpHandler);this._fire("onMouseOver",this._processEvent(a))},_onMouseLeaveHandler:function(a){d(this._onKeyDown_connect);d(this._onKeyUp_connect);
this._onKeyDown_connect=this._onKeyUp_connect=null;this._fire("onMouseOut",this._processEvent(a))},_onMouseMoveHandler:function(a){this._dragEnd?this._dragEnd=!1:this._fire("onMouseMove",this._processEvent(a))},_onMouseDownHandler:function(a){d(this._onMouseMoveHandler_connect);this._onMouseMoveHandler_connect=null;this.node.setCapture&&this.node.setCapture(!1);this._onMouseDragHandler_connect=b(document,"onmousemove",this,this._onMouseDragHandler);this._startX=a.pageX;this._startY=a.pageY;this._fire("onMouseDown",
this._processEvent(a))},_onMouseUpHandler:function(a){var c=this.node;c.releaseCapture&&c.releaseCapture();d(this._onMouseDragHandler_connect);this._onMouseDragHandler_connect=null;d(this._onMouseMoveHandler_connect);this._onMouseMoveHandler_connect=b(c,"onmousemove",this,this._onMouseMoveHandler);this._fire("onMouseUp",this._processEvent(a))},_onMouseDragHandler:function(a){d(this._onMouseDragHandler_connect);this._onMouseDragHandler_connect=b(document,"onmousemove",this,this._onMouseDraggingHandler);
d(this._onMouseUpHandler_connect);this._onMouseUpHandler_connect=b(document,"onmouseup",this,this._onDragMouseUpHandler);this._docLeaveConnect=b(document,"onmouseout",this,this._onDocMouseOut);this._fire("onMouseDragStart",this._processEvent(a))},_onMouseDraggingHandler:function(a){g.stop(a);this._fire("onMouseDrag",this._processEvent(a))},_onDragMouseUpHandler:function(a){var c=this.node;c.releaseCapture&&c.releaseCapture();this._dragEnd=!0;d(this._docLeaveConnect);d(this._onMouseDragHandler_connect);
d(this._onMouseUpHandler_connect);this._docLeaveConnect=this._onMouseDragHandler_connect=null;this._onMouseMoveHandler_connect=b(c,"onmousemove",this,this._onMouseMoveHandler);this._onMouseUpHandler_connect=b(c,"onmouseup",this,this._onMouseUpHandler);a=this._processEvent(a);this._fire("onMouseDragEnd",a);this._fire("onMouseUp",a)},_onDocMouseOut:function(a){var c=a.relatedTarget,b=a.relatedTarget&&a.relatedTarget.nodeName.toLowerCase();(!c||e("chrome")&&"html"===b)&&this._onDragMouseUpHandler(a)},
_onClickHandler:function(a){a=this._processEvent(a);if(!(a.pageX!==this._startX||a.pageY!==this._startY))clearTimeout(this._clickTimer),this._clickEvent=h.mixin({},a),this._clickTimer=setTimeout(this._fireClickEvent,this.doubleClickDuration)},_fireClickEvent:function(){clearTimeout(this._clickTimer);if(9>e("ie"))this._clickEvent.graphic=j._ieGraphic,delete j._ieGraphic;this._fire("onClick",this._clickEvent)},_onDblClickHandler:function(a){clearTimeout(this._clickTimer);this._fire("onDblClick",this._processEvent(a))},
_onMouseWheelHandler:function(a){var c=this.map;(c?c.isScrollWheelZoom||c.isScrollWheelPan:this.preventPageScroll)&&g.stop(a);var c=e("ie")||e("webkit")?a.wheelDelta/this.wheelDivisor:-a.detail/this.mozWheelDivisor,b=Math.abs(c),b=b<=this.minWheelValue?this.minWheelValue:this.maxWheelValue;a.value=0>c?-b:b;this._fire("onMouseWheel",this._processEvent(a))},_onKeyDownHandler:function(a){this._fire("onKeyDown",a)},_onKeyUpHandler:function(a){this._fire("onKeyUp",a)},enableMouseWheel:function(a){d(this._scrollHandle);
this._scrollHandle=b(this.node,e("ff")||e("mozilla")?a?"MozMousePixelScroll":"DOMMouseScroll":"onmousewheel",this,this._onMouseWheelHandler)},setImmediateClick:function(a){this.doubleClickDuration=a?0:this._initialDuration},destroy:function(){var a=this._handles.concat([this._onMouseMoveHandler_connect,this._onMouseUpHandler_connect,this._onMouseDragHandler_connect,this._scrollHandle,this._onKeyDown_connect,this._onKeyUp_connect,this._docLeaveConnect]),b;for(b=0;b<a.length;b++)d(a[b]);clearTimeout(this._clickTimer);
this.node=this.map=this._handles=this._clickEvent=this._onMouseMoveHandler_connect=this._onMouseUpHandler_connect=this._onMouseDragHandler_connect=this._scrollHandle=this._onKeyDown_connect=this._onKeyUp_connect=this._docLeaveConnect=null}})});