//>>built
define(["dojo/_base/declare","dojo/_base/lang","dojo/_base/array","dojo/_base/Color","dojo/_base/Deferred","dojo/has","esri/kernel","esri/graphic","esri/geometry/Point","esri/geometry/jsonUtils","esri/geometry/mathUtils","esri/geometry/webMercatorUtils","esri/symbols/SimpleMarkerSymbol","esri/symbols/SimpleLineSymbol","esri/symbols/CartographicLineSymbol","esri/symbols/SimpleFillSymbol","esri/Evented","require"],function(s,t,n,k,u,A,B,v,w,x,y,p,q,m,o,r,z){return s(z,{declaredClass:"esri.PopupBase",_evtMap:{"set-features":!0,
"clear-features":!0,"selection-change":!0,"dfd-complete":!0},onSetFeatures:function(){},onClearFeatures:function(){},onSelectionChange:function(){},onDfdComplete:function(){},initialize:function(){this.count=0;this.selectedIndex=-1},cleanup:function(){this.features=this.deferreds=null},setFeatures:function(a){if(a&&a.length){this.clearFeatures();var b,c;a[0]instanceof u?c=a:b=a;b?this._updateFeatures(null,b):(this.deferreds=c,c=c.slice(0),n.forEach(c,function(a){a.addBoth(t.hitch(this,this._updateFeatures,
a))},this))}},clearFeatures:function(){this.features=this.deferreds=this._marked=null;this.count=0;var a=this.selectedIndex;this.selectedIndex=-1;if(-1<a)this.onSelectionChange();this.onClearFeatures()},getSelectedFeature:function(){var a=this.features;if(a)return a[this.selectedIndex]},select:function(a){if(!(0>a||a>=this.count))this.selectedIndex=a,this.onSelectionChange()},enableHighlight:function(a){this._highlighted=a.graphics.add(new v(new w(0,0,a.spatialReference)));this._highlighted.hide();
if(!this.markerSymbol)a=this.markerSymbol=new q,a.setStyle(q.STYLE_TARGET),a._setDim(16,16,7),a.setOutline(new o(m.STYLE_SOLID,new k([0,255,255]),2,o.CAP_ROUND,o.JOIN_ROUND)),a.setColor(new k([0,0,0,0]));if(!this.lineSymbol)this.lineSymbol=new m(m.STYLE_SOLID,new k([0,255,255]),2);if(!this.fillSymbol)this.fillSymbol=new r(r.STYLE_NULL,new m(m.STYLE_SOLID,new k([0,255,255]),2),new k([0,0,0,0]))},disableHighlight:function(a){var b=this._highlighted;b&&(b.hide(),a.graphics.remove(b),delete this._highlighted);
this.markerSymbol=this.lineSymbol=this.fillSymbol=null},showHighlight:function(){var a=this.features&&this.features[this.selectedIndex];this._highlighted&&a&&a.geometry&&this._highlighted.show()},hideHighlight:function(){this._highlighted&&this._highlighted.hide()},updateHighlight:function(a,b){var c=b.geometry,e=this._highlighted;if(!c||!e)e&&e.hide();else{e.hide();!e.getLayer()&&a&&a.graphics.add(e);e.setGeometry(x.fromJson(c.toJson()));var d;switch(c.type){case "point":case "multipoint":d=this.markerSymbol;
d.setOffset(0,0);d.setAngle(0);if(c=b.getLayer()){var c=c._getSymbol(b),f,l,g=0,h=0,i=0;if(c){switch(c.type){case "simplemarkersymbol":f=l=c.size||0;break;case "picturemarkersymbol":f=c.width||0,l=c.height||0}g=c.xoffset||0;h=c.yoffset||0;i=c.angle||0}f&&l&&d._setDim(f+1,l+1,7);d.setOffset(g,h);d.setAngle(i)}break;case "polyline":d=this.lineSymbol;break;case "polygon":d=this.fillSymbol}e.setSymbol(d)}},showClosestFirst:function(a){var b=this.features;if(b&&b.length){if(1<b.length){var c,e=Infinity,
d=-1,f,l=y.getLength,g,h=a.spatialReference,i,j,a=a.normalize();for(c=b.length-1;0<=c;c--)if(f=b[c].geometry){i=f.spatialReference;g=0;try{j="point"===f.type?f:f.getExtent().getCenter(),j=j.normalize(),h&&i&&!h.equals(i)&&h._canProject(i)&&(j=h.isWebMercator()?p.geographicToWebMercator(j):p.webMercatorToGeographic(j)),g=l(a,j)}catch(k){}0<g&&g<e&&(e=g,d=c)}0<d&&(b.splice(0,0,b.splice(d,1)[0]),this.select(0))}}else if(this.deferreds)this._marked=a},_unbind:function(a){a=n.indexOf(this.deferreds,a);
if(-1!==a){this.deferreds.splice(a,1);return!this.deferreds.length?(this.deferreds=null,2):1}},_fireComplete:function(a){var b=this._marked;if(b)this._marked=null,this.showClosestFirst(b);this.onDfdComplete(a)},_updateFeatures:function(a,b){if(a){if(this.deferreds){var c=this._unbind(a);if(c)if(b&&b instanceof Error){if(this._fireComplete(b),2===c)this.onSetFeatures()}else if(b&&b.length)if(this.features){if(this.features=this.features.concat(n.filter(b,function(a){return-1===n.indexOf(this.features,
a)},this)),this.count=this.features.length,this._fireComplete(),2===c)this.onSetFeatures()}else{this.features=b;this.count=b.length;this.selectedIndex=0;this._fireComplete();if(2===c)this.onSetFeatures();this.select(0)}else if(this._fireComplete(),2===c)this.onSetFeatures()}}else this.features=b,this.count=b.length,this.selectedIndex=0,this.onSetFeatures(),this.select(0)}})});