//>>built
define(["dojo/_base/array","dojo/_base/config","dojo/_base/Deferred","dojo/_base/lang","dojo/_base/url","dojo/_base/xhr","dojo/io/script","dojo/io/iframe","dojo/dom-construct","dojo/io-query","esri/kernel","esri/config","esri/sniff","esri/lang","esri/urlUtils","esri/deferredUtils"],function(q,B,L,h,m,F,Q,R,M,N,i,G,n,o,k,H){function r(a,d,b,c){var I=!1,O=!1,l=!0;o.isDefined(d)&&(h.isObject(d)?(I=!!d.useProxy,O=!!d.usePost,l=o.isDefined(d.crossOrigin)?d.crossOrigin:l):I=!!d);a=h.mixin({},a);if(a._ssl)a.url=a.url.replace(/^http:/i,
"https:");var d=a.content,j=a.url,g=b&&a.form,f=G.defaults.io;a.load=function(a){var b;if(a){if(a.error)b=h.mixin(Error(),a.error),b.log=B.isDebug;else if("error"===a.status)b=h.mixin(Error(),a),b.log=B.isDebug;if(b&&!o.isDefined(b.httpCode))b.httpCode=b.code}return b||a};a.error=function(a,b){b&&b.xhr&&b.xhr.abort();a instanceof Error||(a=h.mixin(Error(),a));a.log=B.isDebug;f.errorHandler(a,b);return a};if(a._token)a.content=a.content||{},a.content.token=a._token;var J=0;d&&j&&(J=N.objectToQuery(d).length+
j.length+1);a.timeout=o.isDefined(a.timeout)?a.timeout:f.timeout;a.handleAs=a.handleAs||"json";try{var e,s,t=l&&k.canUseXhr(a.url)&&!/https?:\/\/[^\/]+\/[^\/]+\/admin\/?(\/.*)?$/i.test(a.url),m=k.hasSameOrigin(a.url,window.location.href)||t,p=O||b||J>f.postLength?!0:!1,r=!m&&-1!==a.handleAs.indexOf("json")&&a.callbackParamName&&!b?!0:!1,u=k.getProxyRule(a.url)||f.alwaysUseProxy||I||(!r||p)&&!m?!0:!1;b&&!n("esri-file-upload")&&!u&&t&&(u=!0);if(u)if(e=k.getProxyUrl(j,l),s=e.path,e._xo&&(t=!0),!p&&s.length+
1+J>f.postLength&&(p=!0),a.url=s+"?"+j,p)a.content=h.mixin(e.query||{},d);else{var z=N.objectToQuery(h.mixin(e.query||{},d));z&&(a.url+="?"+z);a.content=null}if(r&&!p){if(!o.isDefined(a.isAsync)&&4>n("ff"))a.isAsync=!0;return Q.get(v?v(a):a)}var w=a.headers;if(t&&(!w||!w.hasOwnProperty("X-Requested-With")))w=a.headers=w||{},w["X-Requested-With"]=null;if(b){var C=a.callbackParamName||"callback.html",A=a.callbackElementName||"textarea",x,D,y,E,H=g.elements?g.elements.length:0,K;if(d=a.content)for(x in d)if(y=
d[x],o.isDefined(y)){D=null;for(E=0;E<H;E++)if(K=g.elements[E],K.name===x){D=K;break}D?D.value=y:c?g.append(x,y):g.appendChild(M.create("input",{type:"hidden",name:x,value:y}))}if(n("esri-file-upload"))q.forEach(g.elements,function(a){a.name===C&&g.removeChild(a)}),a.contentType=!1,a.postData=c?g:new FormData(g),delete a.form;else{g.enctype="multipart/form-data";if(9>n("ie"))g.encoding="multipart/form-data";g.method="post";q.some(g.elements,function(a){return a.name===C})||g.appendChild(M.create("input",
{type:"hidden",name:C,value:A}));if(-1!==j.toLowerCase().indexOf("addattachment")||-1!==j.toLowerCase().indexOf("updateattachment"))if(a.url=j+(-1===j.indexOf("?")?"?":"&")+C+"="+A,u)a.url=s+"?"+a.url;delete a.content}}if(t&&!a.hasOwnProperty("withCredentials")&&i.id){var P=i.id.findServerInfo(u?s:j);if(P&&P.webTierAuth)a.withCredentials=!0}a=v?v(a):a;return p?b&&!n("esri-file-upload")?R.send(a):F.post(a):F.get(a)}catch(S){return b=new L,b.errback(a.error(S)),b}}function z(a){var d=G.defaults.io,
b=d._processedCorsServers,c=new m(a),f=-1,c=(c.host+(c.port?":"+c.port:"")).toLowerCase(),f=k.canUseXhr(a,!0);-1<f&&d.corsEnabledServers.splice(f,1);b[c]=1;return f}function A(a){var d=G.defaults.io,b=d._processedCorsServers;if(d.corsDetection)try{var c=new m(a),c=(c.host+(c.port?":"+c.port:"")).toLowerCase();n("esri-cors")&&a&&-1!==a.toLowerCase().indexOf("/rest/services")&&!k.hasSameOrigin(a,window.location.href)&&!k.canUseXhr(a)&&!b[c]&&(b[c]=-1,F.get({url:a.substring(0,a.toLowerCase().indexOf("/rest/")+
6)+"info",content:{f:"json"},failOk:!0,handleAs:"json",headers:{"X-Requested-With":null}}).then(function(f){f?(b[c]=2,k.canUseXhr(a)||d.corsEnabledServers.push(c)):b[c]=1},function(){b[c]=1}))}catch(f){console.log("esri._detectCors: an unknown error occurred while detecting CORS support")}}function f(a,d){var b,c=a.form,k=d&&d.disableIdentityLookup,h=d&&d._preLookup,l=c&&c.append,j=c&&(c.elements?q.some(c.elements,function(a){return"file"===a.type}):l),c=-1!==a.url.toLowerCase().indexOf("token=")||
a.content&&a.content.token||j&&q.some(c.elements,function(a){return"token"===a.name})?1:0;A(a.url);if(a._usrDfd)b=a._usrDfd;else{b=new L(H._dfdCanceller);b.addCallback(function(){var b=a._credential;if(b){var e=i.id.findServerInfo(b.server);if(e=e&&e.owningSystemUrl)e=e.replace(/\/?$/,"/sharing"),(b=i.id.findCredential(e,b.userId))&&-1===i.id._getIdenticalSvcIdx(e,b)&&b.resources.splice(0,0,e)}});b.addBoth(function(b){delete a._credential;if(b&&(!n("ie")||!b.nodeType))b._ssl=a._ssl});var g=a.load,
m=a.error;g&&b.addCallback(function(a){var e=b._pendingDfd,e=e&&e.ioArgs;return g.call(e&&e.args,a,e)});m&&b.addErrback(function(a){var e=b._pendingDfd,e=e&&e.ioArgs;return m.call(e&&e.args,a,e)})}if(i.id&&!c&&!a._token&&!i.id._isPublic(a.url)&&(!k||h))if(h=i.id.findCredential(a.url))a._token=h.token,a._ssl=h.ssl;b._pendingDfd=r(a,d,j,l);if(!b._pendingDfd)return b.ioArgs=b._pendingDfd&&b._pendingDfd.ioArgs,l=Error("Deferred object is missing"),l.log=B.isDebug,a._usrDfd=null,b.errback(l),b._pendingDfd=
null,b;b._pendingDfd.addCallback(function(d){b.ioArgs=b._pendingDfd&&b._pendingDfd.ioArgs;a._usrDfd=null;b.callback(d);b._pendingDfd=null}).addErrback(function(c){if(c&&403==c.code&&(4==c.subcode||c.message&&-1<c.message.toLowerCase().indexOf("ssl")&&-1===c.message.toLowerCase().indexOf("permission"))){if(!a._ssl){a._ssl=a._sslFromServer=!0;a._usrDfd=b;f(a,d);return}}else if(c&&415==c.status){if(z(a.url),!a._err415){a._err415=1;a._usrDfd=b;f(a,d);return}}else if(i.id&&-1!==q.indexOf(i.id._errorCodes,
c.code)&&!i.id._isPublic(a.url)&&!k&&(403!=c.code||!o.isDefined(c.subcode)||2==c.subcode)){b._pendingDfd=i.id.getCredential(a.url,{token:a._token,error:c});b._pendingDfd.addCallback(function(c){a._token=c.token;a._usrDfd=b;a._credential=c;a._ssl=a._sslFromServer||c.ssl;f(a,d)}).addErrback(function(c){a._usrDfd=null;b.errback(c);b._pendingDfd=null});return}b.ioArgs=b._pendingDfd&&b._pendingDfd.ioArgs;a._usrDfd=null;b.errback(c);b._pendingDfd=null});return b}var v;f._request=r;f._disableCors=z;f._detectCors=
A;f.setRequestPreCallback=function(a){v=a};return f});