//>>built
define(["dojo/_base/declare","dojo/_base/connect","dojo/_base/lang","dojo/_base/array","dojo/_base/Color","dojo/_base/Deferred","dojo/has","dojo/keys","esri/kernel","esri/graphic","esri/geometry/ScreenPoint","esri/geometry/Extent","esri/symbols/SimpleMarkerSymbol","esri/symbols/SimpleLineSymbol","esri/tasks/query"],function(D,d,t,u,z,E,H,F,I,G,A,r,B,C,s){return D(null,{declaredClass:"esri.SnappingManager",constructor:function(a){a=a||{};a.map||console.error("map is not specified for SnappingManager");this.map=a.map;
this.tolerance=a.tolerance||15;this.layerInfos=[];if(a.layerInfos)this.layerInfos=a.layerInfos;else{var b;for(b=0;b<this.map.graphicsLayerIds.length;b++)this.layerInfos.push({layer:this.map.getLayer(this.map.graphicsLayerIds[b])});if(this.map.loaded)this.layerInfos.push({layer:this.map.graphics});else var c=d.connect(this.map,"onLoad",this,function(){d.disconnect(c);c=null;this.layerInfos.push({layer:this.map.graphics});this.setLayerInfos(this.layerInfos)})}this.snapPointSymbol=a.snapPointSymbol?
a.snapPointSymbol:new B(B.STYLE_CROSS,15,new C(C.STYLE_SOLID,new z([0,255,255]),1),new z([0,255,0,0]));this.alwaysSnap=a.alwaysSnap?a.alwaysSnap:!1;this.snapKey=a.snapKey?a.snapKey:F.copyKey;this._SelectionLyrQuery=new s;this._SelectionLyrQuery.spatialRelationship=s.SPATIAL_REL_INTERSECTS;this._snappingGraphic=new G;this.setLayerInfos(this.layerInfos);this._currentGraphicOption={snapToPoint:!0,snapToVertex:!0,snapToEdge:!0};this._snappingCallback=t.hitch(this,this._snappingCallback)},getSnappingPoint:function(a){var b=
this.layers,c=this.tolerance,q=this.map,m=this.layerOptions,f=q.toMap(a.offset(-c,c)),c=q.toMap(a.offset(c,-c)),f=new r(f.x,f.y,c.x,c.y,q.spatialReference),o=new s;o.geometry=f;o.spatialRelationship=s.SPATIAL_REL_INTERSECTS;var i=[],k=[],d,x=this._extractPointsAndLines,v=new E,w=0,g,c=f.xmin,j=f.xmax;u.forEach(b,function(a){a.visible&&a.loaded&&"esri.layers.FeatureLayer"===a.declaredClass&&a.mode!==a.constructor.MODE_SELECTION&&w++});if(q.spatialReference._isWrappable())c=r.prototype._normalizeX(f.xmin,
q.spatialReference._getInfo()).x,j=r.prototype._normalizeX(f.xmax,q.spatialReference._getInfo()).x;var h=new r(c,f.ymin,j,f.ymax,q.spatialReference);u.forEach(b,function(a,b){if("esri.layers.GraphicsLayer"===a.declaredClass&&a.visible){var c=[];u.forEach(a.graphics,function(a){a&&a.visible&&h.intersects(a.geometry)&&c.push(a)});var f=x(c,m[b]);i=i.concat(f[0]);k=k.concat(f[1])}});var e=t.hitch(this,function(b){w--;b instanceof Error?console.log("getSnappingPoint: query features failed"):(b=x(b.features,
m[g]),i=i.concat(b[0]),k=k.concat(b[1]));w||(d=this._getSnappingPoint(i,k,a),v.callback(d))}),l=!1;u.forEach(b,function(a,b){a.visible&&a.loaded&&(g=b,"esri.layers.FeatureLayer"===a.declaredClass&&a.mode!==a.constructor.MODE_SELECTION&&(l=!0,a.queryFeatures(o,e,e)))});l||(d=this._getSnappingPoint(i,k,a),v.callback(d));return v},setLayerInfos:function(a){this.layers=[];this.layerOptions=[];var b;for(b=0;b<a.length;b++){this.layers.push(a[b].layer);this.layerOptions.push({snapToPoint:!0,snapToVertex:!0,
snapToEdge:!0});if(!1===a[b].snapToPoint)this.layerOptions[b].snapToPoint=a[b].snapToPoint;if(!1===a[b].snapToVertex)this.layerOptions[b].snapToVertex=a[b].snapToVertex;if(!1===a[b].snapToEdge)this.layerOptions[b].snapToEdge=a[b].snapToEdge}this._featurePtsFromSelectionLayer=[];this._featureLinesFromSelectionLayer=[];this._selectionLayers=[];this._selectionLayerOptions=[];u.forEach(this.layers,function(a,b){"esri.layers.FeatureLayer"===a.declaredClass&&a.mode===a.constructor.MODE_SELECTION&&(this._selectionLayers.push(a),
this._selectionLayerOptions.push(this.layerOptions[b]))},this);this.layerInfos=a},destroy:function(){d.disconnect(this._onExtentChangeConnect);this._killOffSnapping();this._featurePtsFromSelectionLayer=this._featureLinesFromSelectionLayer=this._currentFeaturePts=this._currentFeatureLines=this.layers=this.map=null},_startSelectionLayerQuery:function(){d.disconnect(this._onExtentChangeConnect);this._mapExtentChangeHandler(this._selectionLayers,this._selectionLayerOptions,this.map.extent);this._onExtentChangeConnect=
d.connect(this.map,"onExtentChange",t.hitch(this,"_mapExtentChangeHandler",this._selectionLayers,this._selectionLayerOptions))},_stopSelectionLayerQuery:function(){d.disconnect(this._onExtentChangeConnect)},_mapExtentChangeHandler:function(a,b,c){this._featurePtsFromSelectionLayer=[];this._featureLinesFromSelectionLayer=[];var q;this._SelectionLyrQuery.geometry=c;var d=t.hitch(this,function(a){a instanceof Error?console.log("getSnappingPoint: query features failed"):(a=this._extractPointsAndLines(a.features,
b[q]),this._featurePtsFromSelectionLayer=this._featurePtsFromSelectionLayer.concat(a[0]),this._featureLinesFromSelectionLayer=this._featureLinesFromSelectionLayer.concat(a[1]))});u.forEach(a,function(a,b){a.visible&&a.loaded&&(q=b,a.queryFeatures(this._SelectionLyrQuery,d,d))},this)},_extractPointsAndLines:function(a,b){var c=[],d=[],m,f;u.forEach(a,function(a){if(a.visible&&a.geometry)if("point"===a.geometry.type&&b.snapToPoint)c.push(a.geometry);else if("polyline"===a.geometry.type)for(m=0;m<a.geometry.paths.length;m++){d.push("lineStart");
for(f=0;f<a.geometry.paths[m].length;f++){var i=a.geometry.getPoint(m,f);b.snapToVertex&&c.push(i);b.snapToEdge&&d.push(i)}d.push("lineEnd")}else if("polygon"===a.geometry.type)for(m=0;m<a.geometry.rings.length;m++){d.push("lineStart");for(f=0;f<a.geometry.rings[m].length;f++)i=a.geometry.getPoint(m,f),b.snapToVertex&&c.push(i),b.snapToEdge&&d.push(i);d.push("lineEnd")}});return[c,d]},_getSnappingPoint:function(a,b,c){var d,m,f=this.tolerance,o=this.map,i=this.map._getFrameWidth(),a=a.concat(this._featurePtsFromSelectionLayer),
b=b.concat(this._featureLinesFromSelectionLayer);if(this._currentGraphic)var k=this._extractPointsAndLines([this._currentGraphic],this._currentGraphicOption),a=a.concat(k[0]),b=b.concat(k[1]);var t,x;u.forEach(a,function(a){a=o.toScreen(a,!0);if(-1!==i&&(a.x%=i,0>a.x&&(a.x+=i),o.width>i))for(var b=(o.width-i)/2;a.x<b;)a.x+=i;d=Math.sqrt((a.x-c.x)*(a.x-c.x)+(a.y-c.y)*(a.y-c.y));if(d<=f)f=d,t=a.x,x=a.y});if(t)b=new A(t,x),m=b=o.toMap(b);else{for(var v,w,f=this.tolerance,a=0;a<b.length;a++)if("lineStart"===
b[a])for(k=a+1;k<b.length;k++){if("lineEnd"!==b[k+1]&&"lineStart"!==b[k+1]&&"lineEnd"!==b[k]&&"lineStart"!==b[k]){var g=o.toScreen(b[k],!0),j=o.toScreen(b[k+1],!0),h=g.x>=j.x?g:j,e=g.x>=j.x?j:g;-1!==i&&(h.x%=i,0>h.x&&(h.x+=i),e.x%=i,0>e.x&&(e.x+=i),e.x>h.x&&(e.x-=i));var g=h.x,h=h.y,j=e.x,e=e.y,l,n,p,r,s,y;g===j?(l=g,n=c.y,p=r=g,s=h<=e?h:e,y=h<=e?e:h):h===e?(l=c.x,n=h,p=g<=j?g:j,r=g<=j?j:g,s=y=h):(n=(e-h)/(j-g),p=(h*j-g*e)/(j-g),l=(p-(c.y*e-c.y*h-c.x*g+c.x*j)/(e-h))/((g-j)/(e-h)-n),n=n*l+p,p=g<=j?
g:j,r=g<=j?j:g,s=h<=e?h:e,y=h<=e?e:h);l>=p&&l<=r&&n>=s&&n<=y?(g=Math.sqrt((c.x-l)*(c.x-l)+(c.y-n)*(c.y-n)),g<=f&&(f=g,v=l,w=n)):(l=Math.sqrt((g-c.x)*(g-c.x)+(h-c.y)*(h-c.y)),n=Math.sqrt((j-c.x)*(j-c.x)+(e-c.y)*(e-c.y)),l<=n?(p=l,l=g,n=h):(p=n,l=j,n=e),p<=f&&(f=p,v=l,w=n))}if("lineEnd"===b[k]){a=k;break}}v&&(b=new A(v,w),m=b=o.toMap(b))}return m},_setGraphic:function(a){this._currentGraphic=a},_addSnappingPointGraphic:function(){var a=this.map;this._snappingGraphic.setSymbol(this.snapPointSymbol);
a.graphics.add(this._snappingGraphic)},_setUpSnapping:function(){var a=this.map;this._onSnapKeyDown_connect=d.connect(a,"onKeyDown",this,"_onSnapKeyDownHandler");this._onSnapKeyUp_connect=d.connect(a,"onKeyUp",this,"_onSnapKeyUpHandler");this._onSnappingMouseMove_connect=d.connect(a,"onMouseMove",this,"_onSnappingMouseMoveHandler");this._onSnappingMouseDrag_connect=d.connect(a,"onMouseDrag",this,"_onSnappingMouseMoveHandler");this.alwaysSnap&&this._activateSnapping()},_killOffSnapping:function(){d.disconnect(this._onSnapKeyDown_connect);
d.disconnect(this._onSnapKeyUp_connect);d.disconnect(this._onSnappingMouseMove_connect);d.disconnect(this._onSnappingMouseDrag_connect);this._deactivateSnapping()},_onSnapKeyDownHandler:function(a){a.keyCode===this.snapKey&&(d.disconnect(this._onSnapKeyDown_connect),this.alwaysSnap?this._deactivateSnapping():this._activateSnapping())},_activateSnapping:function(){this._snappingActive=!0;this._addSnappingPointGraphic();this._currentLocation&&this._onSnappingMouseMoveHandler(this._currentLocation)},
_onSnapKeyUpHandler:function(a){if(a.keyCode===this.snapKey)this._onSnapKeyDown_connect=d.connect(this.map,"onKeyDown",this,"_onSnapKeyDownHandler"),this.alwaysSnap?this._activateSnapping():this._deactivateSnapping()},_deactivateSnapping:function(){this._snappingActive=!1;this._snappingPoint=null;this.map.graphics.remove(this._snappingGraphic);this._snappingGraphic.setGeometry(null)},_onSnappingMouseMoveHandler:function(a){this._currentLocation=a;this._snappingPoint=null;this._snappingActive&&(this._snappingGraphic.hide(),
this.getSnappingPoint(a.screenPoint).addCallback(this._snappingCallback))},_snappingCallback:function(a){if(this._snappingPoint=a)this._snappingGraphic.show(),this._snappingGraphic.setGeometry(a)}})});