//>>built
require({cache:{"url:esri/dijit/templates/BasemapGallery.html":'<div class="esriBasemapGallery">\r\n  <div dojoAttachPoint="flowContainer">\r\n  </div>\r\n</div>'}});
define(["require","dojo/_base/declare","dojo/_base/array","dojo/_base/connect","dojo/_base/lang","dojo/_base/kernel","dojo/_base/sniff","dojo/has","dojo/query","dojo/DeferredList","dojo/dom","dojo/dom-construct","dojo/dom-class","dijit/_Widget","dijit/_Templated","esri/kernel","esri/urlUtils","esri/request","esri/geometry/Extent","esri/virtualearth/VETiledLayer","esri/layers/OpenStreetMapLayer","esri/layers/ArcGISTiledMapServiceLayer","esri/layers/ArcGISDynamicMapServiceLayer","esri/layers/ArcGISImageServiceLayer","esri/layers/ImageServiceParameters","esri/dijit/Basemap","esri/dijit/_EventedWidget","dojo/text!esri/dijit/templates/BasemapGallery.html"],function(q,
r,e,k,f,l,D,E,F,s,t,h,m,u,v,g,w,i,n,j,x,y,z,o,p,A,B,C){return r([B,u,v],{declaredClass:"esri.dijit.BasemapGallery",widgetsInTemplate:!0,templateString:C,basePath:q.toUrl("esri/dijit")+"/",loaded:!1,basemaps:[],bingMapsKey:null,flowContainer:null,_hasUI:!1,_selectedBasemap:null,_selectBasemapInProgress:!1,_eventMap:{load:!0,"selection-change":!0,add:["basemap"],remove:["basemap"],error:["message"]},constructor:function(a,b){a=a||{};a.map||console.error("esri.dijit.BasemapGallery: Unable to find the 'map' property in parameters");
this.map=a.map;this._hasUI=b?!0:!1;this.bingMapsKey=a.bingMapsKey&&0<a.bingMapsKey.length?a.bingMapsKey:null;this.showArcGISBasemaps=!1===a.showArcGISBasemaps?!1:!0;this.basemaps=a.basemaps||[];this.basemapIds=a.basemapIds;this.referenceIds=a.referenceIds;this.basemapsGroup=a.basemapsGroup;if("https:"===location.protocol)g.dijit._arcgisUrl=g.dijit._arcgisUrl.replace("http:","https:");this.init()},init:function(){this.inherited(arguments);e.forEach(this.basemaps,function(a){if(!a.id||0===a.id.length)a.id=
this._getUniqueId();e.forEach(a.layers,function(a){a.opacity=0<=a.opacity?a.opacity:1;a.visibility=!0},this)},this);this.basemapIds&&0<this.basemapIds.length&&e.forEach(this.basemapIds,function(a){this.map.getLayer(a)._basemapGalleryLayerType="basemap"},this);this.referenceIds&&0<this.referenceIds.length&&e.forEach(this.referenceIds,function(a){this.map.getLayer(a)._basemapGalleryLayerType="reference"},this);this.basemapsGroup&&(this.basemapsGroup.owner&&this.basemapsGroup.title||this.basemapsGroup.id)?
this._findCustomBasemapsGroup(f.hitch(this,"_handleArcGISBasemapsResponse")):this.showArcGISBasemaps?this._findArcGISBasemapsGroup(f.hitch(this,"_handleArcGISBasemapsResponse")):this._finishStartup()},startup:function(){this.loaded?this._refreshUI():k.connect(this,"onLoad",f.hitch(this,function(){this._refreshUI()}))},select:function(a){this._select(a)},getSelected:function(){return this._selectedBasemap},get:function(a){var b;for(b=0;b<this.basemaps.length;b++)if(this.basemaps[b].id==a)return this.basemaps[b];
return null},add:function(a){if(a&&!a.id)return a.id=this._getUniqueId(),this.basemaps.push(a),this._refreshUI(),this.onAdd(a),!0;return a&&this._isUniqueId(a.id)?(this.basemaps.push(a),this._refreshUI(),this.onAdd(a),!0):!1},remove:function(a){var b;for(b=0;b<this.basemaps.length;b++){var c=this.basemaps[b];if(c.id===a){if(this._selectedBasemap&&this._selectedBasemap.id===c.id)this._selectedBasemap=null;this.basemaps.splice(b,1);this._refreshUI();this.onRemove(c);return c}}return null},onLoad:function(){},
onSelectionChange:function(){},onAdd:function(){},onRemove:function(){},onError:function(){},_defaultBasemapGalleryGroupQuery:'title:"ArcGIS Online Basemaps" AND owner:esri',_basemapGalleryGroupQuery:null,_finishStartup:function(){this.loaded=!0;this.onLoad();0===this.map.layerIds.length&&0<this.basemaps.length&&!this._selectBasemapInProgress&&this._select(this.basemaps[0].id)},_findCustomBasemapsGroup:function(a){this.basemapsGroup&&this.basemapsGroup.id?this._findArcGISBasemaps(this.basemapsGroup.id,
a):(this._basemapGalleryGroupQuery='title:"'+this.basemapsGroup.title+'" AND owner:'+this.basemapsGroup.owner,this._findArcGISBasemapsGroup(a))},_findArcGISBasemapsGroup:function(a){if(this._basemapGalleryGroupQuery)this._findArcGISBasemapsGroupContent(a);else{var b=g.dijit._arcgisUrl+"/accounts/self",c={f:"json"};c.culture=l.locale;i({url:b,content:c,callbackParamName:"callback",load:f.hitch(this,function(b){this._basemapGalleryGroupQuery=b&&b.basemapGalleryGroupQuery?b.basemapGalleryGroupQuery:
this._defaultBasemapGalleryGroupQuery;this._findArcGISBasemapsGroupContent(a)}),error:f.hitch(this,function(){this._basemapGalleryGroupQuery=this._defaultBasemapGalleryGroupQuery})})}},_findArcGISBasemapsGroupContent:function(a){var b=f.hitch(this,"_findArcGISBasemaps"),c=g.dijit._arcgisUrl+"/community/groups",d={};d.q=this._basemapGalleryGroupQuery;d.f="json";i({url:c,content:d,callbackParamName:"callback",load:f.hitch(this,function(c){if(0<c.results.length)b(c.results[0].id,a);else this.onError("esri.dijit.BasemapGallery: could not find group for basemaps.")}),
error:f.hitch(this,function(){this.onError("esri.dijit.BasemapGallery: could not find group for basemaps.")})})},_findArcGISBasemaps:function(a,b){var c=g.dijit._arcgisUrl+"/search",d={};d.q="group:"+a+' AND type:"web map"';d.sortField="name";d.sortOrder="desc";d.num=50;d.f="json";i({url:c,content:d,callbackParamName:"callback",load:f.hitch(this,function(a){if(0<a.results.length)b(a.results);else this.onError("esri.dijit.BasemapGallery: could not find group for basemaps.")}),error:f.hitch(this,function(){this.onError("esri.dijit.BasemapGallery: could not find group for basemaps.")})})},
_handleArcGISBasemapsResponse:function(a){0<a.length&&(e.forEach(a,function(a){if(this.bingMapsKey||!this.bingMapsKey&&a.title&&-1==a.title.indexOf("Bing Maps")){var c={};c.id=this._getUniqueId();c.title=a.title;c.thumbnailUrl="";if(a.thumbnail&&a.thumbnail.length&&(c.thumbnailUrl=g.dijit._arcgisUrl+"/content/items/"+a.id+"/info/"+a.thumbnail,g.id)){var d=g.id.findCredential(w.urlToObject(g.dijit._arcgisUrl).path);d&&(c.thumbnailUrl+="?token="+d.token)}c.itemId=a.id;this.basemaps.splice(0,0,new A(c,
this))}},this),this._finishStartup())},_refreshUI:function(){this._hasUI&&(h.empty(this.flowContainer),e.forEach(this.basemaps,function(a,b){if(!a.id)a.id="basemap_"+b;this.flowContainer.appendChild(this._buildNodeLayout(a))},this),h.create("br",{style:{clear:"both"}},this.flowContainer),this._markSelected(this._selectedBasemap))},_buildNodeLayout:function(a){var b=h.create("div",{id:"galleryNode_"+a.id,"class":"esriBasemapGalleryNode"}),c=h.create("a",{href:"javascript:void(0);"},b);k.connect(c,
"onclick",f.hitch(this,"_onNodeClick",a));a.thumbnailUrl?h.create("img",{"class":"esriBasemapGalleryThumbnail",src:a.thumbnailUrl},c):h.create("img",{"class":"esriBasemapGalleryThumbnail",src:this.basePath.toString()+"images/transparent.gif"},c);c=h.create("div",{"class":"esriBasemapGalleryLabelContainer"},b);a=a.title||"";h.create("span",{innerHTML:a,alt:a,title:a},c);return b},_onNodeClick:function(a,b){b.preventDefault();this._markSelected(a);this.select(a.id)},_markSelected:function(a){a&&(e.forEach(l.query(".esriBasemapGallerySelectedNode",
this.domNode),function(a){m.remove(a,"esriBasemapGallerySelectedNode")}),(a=t.byId("galleryNode_"+a.id))&&m.add(a,"esriBasemapGallerySelectedNode"))},_select:function(a){this._selectBasemapInProgress=!0;var b=this.get(a);b?(b.layers?this._getServiceInfos(b):(a=b.getLayers(),f.isArray(a)?this._getServiceInfos(b):a.addCallback(f.hitch(this,function(){this._getServiceInfos(b)}))),this._markSelected(b)):this._selectBasemapInProgress=!1},_getServiceInfos:function(a){"https:"==location.protocol&&e.forEach(a.layers,
function(a){if(this._isAgolService(a.url)||this._isHostedService(a.url))a.url=a.url.replace("http:","https:")},this);this._selectedBasemap=a;var b=[];e.forEach(a.layers,function(a){if(a.url&&0<a.url.length&&!a.isReference)a.deferredsPos=b.length,b.push(this._getServiceInfo(a.url))},this);0<b.length?(new s(b)).addCallback(f.hitch(this,function(b){var d=null;e.forEach(a.layers,function(a){if(0===a.deferredsPos||a.deferredsPos){a.serviceInfoResponse=b[a.deferredsPos][1];var e=a.serviceInfoResponse.fullExtent;
if(!e)e=a.serviceInfoResponse.extent;d=d?d.union(new n(e)):new n(e)}},this);this.map.extent&&5>this._getIntersectionPercent(d,this.map.extent)&&this.map.setExtent(d,!0);this._switchBasemapLayers(a);this._updateReferenceLayer(a)})):(this._switchBasemapLayers(a),this._updateReferenceLayer(a))},_switchBasemapLayers:function(a){a=a.layers;if(0<this.map.layerIds.length&&0===this.map.getNumLevels()&&("OpenStreetMap"===a[0].type||a[0].type&&-1<a[0].type.indexOf("BingMaps")))this.onError("esri.dijit.BasemapGallery: Unable to switch basemap because new basemap is a tiled service and cannot be loaded as a dynamic layer.");
else e.forEach(a,function(a){if(!a.isReference&&a.type&&-1<a.type.indexOf("BingMaps")&&!this.bingMapsKey)this.onError("esri.dijit.BasemapGallery: Invalid Bing Maps key.")},this),this._removeBasemapLayers(),e.forEach(a,function(a){if(!a.isReference){var c;if("OpenStreetMap"===a.type){if(0<this.map.layerIds.length&&0===this.map.getNumLevels()){this.onError("esri.dijit.BasemapGallery: Unable to switch basemap because new basemap is a tiled service and cannot be loaded as a dynamic layer.");return}c=
new x({id:"layer_osm",opacity:a.opacity})}else if(a.type&&-1<a.type.indexOf("BingMaps")){if(0<this.map.layerIds.length&&0===this.map.getNumLevels()){this.onError("esri.dijit.BasemapGallery: Unable to switch basemap because new basemap is a tiled service and cannot be loaded as a dynamic layer.");return}c=j.MAP_STYLE_AERIAL_WITH_LABELS;if("BingMapsAerial"==a.type)c=j.MAP_STYLE_AERIAL;else if("BingMapsRoad"==a.type)c=j.MAP_STYLE_ROAD;c=new j({id:"layer_bing",bingMapsKey:this.bingMapsKey,mapStyle:c,
opacity:a.opacity})}else if(a.serviceInfoResponse&&a.serviceInfoResponse.mapName)c=(0===this.map.layerIds.length||0<this.map.getNumLevels())&&!0===a.serviceInfoResponse.singleFusedMapCache?this._loadAsCached(a):this._loadAsDynamic(a);else if(a.serviceInfoResponse&&a.serviceInfoResponse.pixelSizeX){c=new p;c.bandIds=a.bandIds;if(!a.bandIds&&a.serviceInfoResponse.bandCount&&3<parseInt(a.serviceInfoResponse.bandCount))c.bandIds=[0,1,2];c=new o(a.url,{resourceInfo:a.serviceInfoResponse,opacity:a.opacity,
visible:a.visibility,imageServiceParameters:c})}if(c)c._basemapGalleryLayerType="basemap",this.map.addLayer(c,0)}},this),this._selectBasemapInProgress=!1,this.onSelectionChange()},_removeBasemapLayers:function(){var a=this.map.layerIds,b=[];e.forEach(a,function(a){a=this.map.getLayer(a);"basemap"===a._basemapGalleryLayerType&&b.push(a)},this);0===b.length&&0<a.length&&b.push(this.map.getLayer(a[0]));0<b.length&&e.forEach(b,function(a){this.map.removeLayer(a)},this)},_updateReferenceLayer:function(a){var b;
this._removeReferenceLayer();for(b=0;b<a.layers.length;b++)!0===a.layers[b].isReference&&this._addReferenceLayer(a.layers[b])},_removeReferenceLayer:function(){var a;for(a=this.map.layerIds.length-1;0<=a;a--){var b=this.map.getLayer(this.map.layerIds[a]);"reference"===b._basemapGalleryLayerType&&this.map.removeLayer(b)}},_addReferenceLayer:function(a){this._getServiceInfo(a.url,f.hitch(this,"_handleReferenceServiceInfoResponse",a))},_handleReferenceServiceInfoResponse:function(a,b){var c;if((a.serviceInfoResponse=
b)&&b.mapName)c=!0===b.singleFusedMapCache?this._loadAsCached(a):this._loadAsDynamic(a);else if(b&&b.pixelSizeX){c=new p;c.bandIds=a.bandIds;if(!a.bandIds&&b.bandCount&&3<parseInt(b.bandCount))c.bandIds=[0,1,2];c=new o(a.url,{resourceInfo:b,opacity:a.opacity,visible:a.visibility,imageServiceParameters:c})}if(c)c._basemapGalleryLayerType="reference",this.map.addLayer(c)},_getServiceInfo:function(a,b){return i({url:a,content:{f:"json"},callbackParamName:"callback",load:function(a,d){b&&b(a,d)},error:f.hitch(this,
function(){this.onError("esri.dijit.BasemapGallery: service not accessible.")})})},_loadAsCached:function(a){var b=[];a.displayLevels||(b=e.map(a.serviceInfoResponse.tileInfo.lods,function(a){return a.level}));return new y(a.url,{resourceInfo:a.serviceInfoResponse,opacity:a.opacity,visible:a.visibility,displayLevels:a.displayLevels||b})},_loadAsDynamic:function(a){var b=new z(a.url,{resourceInfo:a.serviceInfoResponse,opacity:a.opacity,visible:a.visibility});a.visibleLayers&&b.setVisibleLayers(a.visibleLayers);
return b},_getIntersectionPercent:function(a,b){var c=b.intersects(a);if(c){var c=c.getWidth()*c.getHeight(),d=b.getWidth()*b.getHeight();return 100*(c/d)}return 0},_getIds:function(){var a=[];e.forEach(this.basemaps,function(b){a.push(b.id)},this);return a},_getUniqueId:function(){for(var a=","+this._getIds().toString()+",",b=0;;)if(-1<a.indexOf(",basemap_"+b+","))b++;else return"basemap_"+b},_isUniqueId:function(a){return-1===(","+this._getIds().toString()+",").indexOf(","+a+",")?!0:!1},_isAgolService:function(a){return!a?
!1:-1!==a.indexOf("/services.arcgisonline.com/")||-1!==a.indexOf("/server.arcgisonline.com/")},_isHostedService:function(a){return!a?!1:-1!==a.indexOf(".arcgis.com/")}})});