//>>built
define(["dojo/_base/declare","dojo/_base/lang","dojo/_base/array","dojo/_base/connect","dojo/_base/json","dojo/has","dojo/sniff","dojo/DeferredList","dojo/json","dojo/dom","dojo/dom-construct","dojo/dom-style","dijit/_Widget","dojox/gfx","dojox/html/entities","esri/kernel","esri/config","esri/request","esri/renderers/SimpleRenderer","esri/renderers/UniqueValueRenderer","esri/renderers/ClassBreaksRenderer","esri/symbols/jsonUtils","esri/dijit/_EventedWidget","dojo/i18n!esri/nls/jsapi"],function(t,l,g,i,u,n,F,v,w,j,d,m,x,y,z,G,q,r,A,B,
C,s,D,E){var o=t([D,x],{declaredClass:"esri.dijit.Legend",widgetsInTemplate:!1,layers:null,alignRight:!1,hoverLabelShowing:!1,_ieTimer:100,constructor:function(a,b){l.mixin(this,E.widgets.legend);a=a||{};if(a.map)if(b){this.map=a.map;this.layerInfos=a.layerInfos;this._respectCurrentMapScale=!1===a.respectCurrentMapScale?!1:!0;this.arrangement=a.arrangement===o.ALIGN_RIGHT?o.ALIGN_RIGHT:o.ALIGN_LEFT;if(this.arrangement===o.ALIGN_RIGHT)this.alignRight=!0;this.autoUpdate=!1===a.autoUpdate?!1:!0;this._surfaceItems=
[]}else console.error("esri.dijit.Legend: must specify a container for the legend");else console.error("esri.dijit.Legend: unable to find the 'map' property in parameters")},startup:function(){this.inherited(arguments);this._initialize();if(n("ie"))this._repaintItems=l.hitch(this,this._repaintItems),setTimeout(this._repaintItems,this._ieTimer)},destroy:function(){this._deactivate();this._removeHoverHandlers();this.inherited(arguments)},refresh:function(a){if(this.domNode){if(a)this.layerInfos=a,this.layers=
[],g.forEach(this.layerInfos,function(a){if(this._isSupportedLayerType(a.layer)){if(a.title)a.layer._titleForLegend=a.title;a.layer._hideDefaultSymbol=!1===a.defaultSymbol?!0:!1;a.hideLayers?(a.layer._hideLayersInLegend=a.hideLayers,this._addSubLayersToHide(a)):a.layer._hideLayersInLegend=[];if(a.hoverLabel)a.layer._hoverLabel=a.hoverLabel;if(a.hoverLabels)a.layer._hoverLabels=a.hoverLabels;this.layers.push(a.layer)}},this);else if(this.useAllMapLayers)this.layers=this.layerInfos=null;for(a=this.domNode.children.length-
1;0<=a;a--)d.destroy(this.domNode.children[a]);this._removeHoverHandlers();this.startup()}},_legendUrl:"http://utility.arcgis.com/sharing/tools/legend",_initialize:function(){if(this.layerInfos)this.layers=[],g.forEach(this.layerInfos,function(a){if(this._isSupportedLayerType(a.layer)){if(a.title)a.layer._titleForLegend=a.title;a.layer._hideDefaultSymbol=!1===a.defaultSymbol?!0:!1;a.hideLayers?(a.layer._hideLayersInLegend=a.hideLayers,this._addSubLayersToHide(a)):a.layer._hideLayersInLegend=[];if(a.hoverLabel)a.layer._hoverLabel=
a.hoverLabel;if(a.hoverLabels)a.layer._hoverLabels=a.hoverLabels;this.layers.push(a.layer)}},this);this.useAllMapLayers=!1;if(!this.layers){this.useAllMapLayers=!0;this.layers=[];var a=[],b=[];g.forEach(this.map.layerIds,function(c){var c=this.map.getLayer(c),h;if(this._isSupportedLayerType(c)){if(c.arcgisProps&&c.arcgisProps.title)c._titleForLegend=c.arcgisProps.title;this.layers.push(c)}"esri.layers.KMLLayer"==c.declaredClass&&(h=c.getLayers(),g.forEach(h,function(b){a.push(b.id)},this));"esri.layers.GeoRSSLayer"==
c.declaredClass&&(h=c.getFeatureLayers(),g.forEach(h,function(a){b.push(a.id)},this))},this);g.forEach(this.map.graphicsLayerIds,function(c){var h=this.map.getLayer(c);if(-1==g.indexOf(a,c)&&-1==g.indexOf(b,c)&&this._isSupportedLayerType(h)&&h._params&&h._params.drawMode){if(h.arcgisProps&&h.arcgisProps.title)h._titleForLegend=h.arcgisProps.title;this.layers.push(h)}},this)}this._createLegend()},_activate:function(){this._deactivate();if(this.autoUpdate){if(this._respectCurrentMapScale)this._ozeConnect=
i.connect(this.map,"onZoomEnd",this,"_refreshLayers");if(this.useAllMapLayers)this._olaConnect=i.connect(this.map,"onLayerAdd",this,"_updateAllMapLayers"),this._olrConnect=i.connect(this.map,"onLayerRemove",this,"_updateAllMapLayers"),this._olroConnect=i.connect(this.map,"onLayersReordered",this,"_updateAllMapLayers");g.forEach(this.layers,function(a){a.ovcConnect=i.connect(a,"onVisibilityChange",this,"_refreshLayers");a.oscConnect=i.connect(a,"onScaleRangeChange",this,"_refreshLayers");if("esri.layers.ArcGISDynamicMapServiceLayer"===
a.declaredClass&&a.supportsDynamicLayers)a.odcConnect=i.connect(a,"_onDynamicLayersChange",l.hitch(this,"_updateDynamicLayers",a));if("esri.layers.ArcGISImageServiceLayer"===a.declaredClass)a.oirConnect=i.connect(a,"onRenderingChange",l.partial(this._updateImageServiceLayers,this,a))},this)}},_deactivate:function(){this._ozeConnect&&i.disconnect(this._ozeConnect);this._olaConnect&&i.disconnect(this._olaConnect);this._olroConnect&&i.disconnect(this._olroConnect);this._olrConnect&&i.disconnect(this._olrConnect);
g.forEach(this.layers,function(a){a.ovcConnect&&i.disconnect(a.ovcConnect);a.oscConnect&&i.disconnect(a.oscConnect);a.odcConnect&&i.disconnect(a.odcConnect);a.oirConnect&&i.disconnect(a.oirConnect)},this)},_updateDynamicLayers:function(a){delete a.legendResponse;this._refreshLayers()},_updateImageServiceLayers:function(a,b){delete b.legendResponse;a._refreshLayers()},_refreshLayers:function(){this.refresh()},_updateAllMapLayers:function(){this.layers=[];g.forEach(this.map.layerIds,function(a){a=this.map.getLayer(a);
this._isSupportedLayerType(a)&&this.layers.push(a)},this);g.forEach(this.map.graphicsLayerIds,function(a){a=this.map.getLayer(a);this._isSupportedLayerType(a)&&a._params&&a._params.drawMode&&this.layers.push(a)},this);this.refresh()},_createLegend:function(){var a=!1;m.set(this.domNode,"position","relative");d.create("div",{id:this.id+"_msg",innerHTML:this.NLS_creatingLegend+"..."},this.domNode);var b=[];g.forEach(this.layers,function(c){if("esri.layers.KMLLayer"==c.declaredClass||"esri.layers.GeoRSSLayer"==
c.declaredClass){var f;c.loaded?("esri.layers.KMLLayer"==c.declaredClass?f=c.getLayers():"esri.layers.GeoRSSLayer"==c.declaredClass&&(f=c.getFeatureLayers(),c._hideLayersInLegend&&(f=g.filter(f,function(a){return-1==g.indexOf(c._hideLayersInLegend,a.id)}))),g.forEach(f,function(a){if("esri.layers.FeatureLayer"==a.declaredClass&&c._titleForLegend)a._titleForLegend=c._titleForLegend+" - ","esriGeometryPoint"==a.geometryType?a._titleForLegend+=this.NLS_points:"esriGeometryPolyline"==a.geometryType?a._titleForLegend+=
this.NLS_lines:"esriGeometryPolygon"==a.geometryType&&(a._titleForLegend+=this.NLS_polygons),b.push(a)},this)):i.connect(c,"onLoad",l.hitch(this,function(){this.refresh(this.layerInfos)}))}else"esri.layers.WMSLayer"===c.declaredClass?c.loaded?c.visible&&0<c.layerInfos.length&&g.some(c.layerInfos,function(a){return a.legendURL})&&(d.create("div",{innerHTML:"<span class='esriLegendServiceLabel'>"+(c._titleForLegend||c.name||c.id)+"</span>"},this.domNode),g.forEach(c.layerInfos,function(b){-1<g.indexOf(c.visibleLayers,
b.name)&&(d.create("div",{innerHTML:"<img src='"+b.legendURL+"'/>"},this.domNode),a=!0)},this)):i.connect(c,"onLoad",l.hitch(this,function(){this.refresh(this.layerInfos)})):b.push(c)},this);var c=[];g.forEach(b,function(a){if(a.loaded){if(!0===a.visible&&(a.layerInfos||a.renderer||"esri.layers.ArcGISImageServiceLayer"==a.declaredClass)){var b=d.create("div",{id:this.id+"_"+a.id,style:"display: none;","class":"esriLegendService"});d.create("span",{innerHTML:this._getServiceTitle(a),"class":"esriLegendServiceLabel"},
d.create("td",{align:this.alignRight?"right":"left"},d.create("tr",{},d.create("tbody",{},d.create("table",{width:"95%"},b)))));d.place(b,this.id,"first");n("ie")&&m.set(j.byId(this.id+"_"+a.id),"display","none");a.legendResponse||a.renderer?this._createLegendForLayer(a):c.push(this._legendRequest(a))}}else var e=i.connect(a,"onLoad",this,function(){i.disconnect(e);e=null;this.refresh()})},this);0===c.length&&!a?(j.byId(this.id+"_msg").innerHTML=this.NLS_noLegend,this._activate()):(new v(c)).addCallback(l.hitch(this,
function(){a?j.byId(this.id+"_msg").innerHTML="":j.byId(this.id+"_msg").innerHTML=this.NLS_noLegend;this._activate()}))},_createLegendForLayer:function(a){if(a.legendResponse||a.renderer){var b=!1;if(a.legendResponse){var c=a.dynamicLayerInfos||a.layerInfos;c?g.forEach(c,function(c,f){if(!a._hideLayersInLegend||-1==g.indexOf(a._hideLayersInLegend,c.id)){var e=this._buildLegendItems(a,c,f);b=b||e}},this):"esri.layers.ArcGISImageServiceLayer"==a.declaredClass&&(b=this._buildLegendItems(a,{id:0,name:null,
title:a.name,subLayerIds:null,parentLayerId:-1},0))}else a.renderer&&(c=a.url?a.url.substring(a.url.lastIndexOf("/")+1,a.url.length):"fc_"+a.id,b=this._buildLegendItems(a,{id:c,name:null,subLayerIds:null,parentLayerId:-1},0));b&&(m.set(j.byId(this.id+"_"+a.id),"display","block"),m.set(j.byId(this.id+"_msg"),"display","none"))}},_legendRequest:function(a){if(a.loaded)return 10.01<=a.version?this._legendRequestServer(a):this._legendRequestTools(a);i.connect(a,"onLoad",l.hitch(this,"_legendRequest"))},
_legendRequestServer:function(a){var b=a.url,c=b.indexOf("?"),b=-1<c?b.substring(0,c)+"/legend"+b.substring(c):b+"/legend";(c=a._getToken())&&(b+="?token="+c);var h=l.hitch(this,"_processLegendResponse"),c={f:"json"};if(a._params.dynamicLayers&&(c.dynamicLayers=w.stringify(this._createDynamicLayers(a)),"[{}]"===c.dynamicLayers))c.dynamicLayers="[]";if(a._params.bandIds)c.bandIds=a._params.bandIds;if(a._params.renderingRule)c.renderingRule=a._params.renderingRule;return r({url:b,content:c,callbackParamName:"callback",
load:function(b,c){h(a,b,c)},error:q.defaults.io.errorHandler})},_legendRequestTools:function(a){var b=a.url.toLowerCase().indexOf("/rest/"),b=a.url.substring(0,b)+a.url.substring(b+5,a.url.length),b=this._legendUrl+"?soapUrl="+window.escape(b);if(!n("ie")||8<n("ie"))b+="&returnbytes=true";var c=l.hitch(this,"_processLegendResponse");return r({url:b,content:{f:"json"},callbackParamName:"callback",load:function(b,f){c(a,b,f)},error:q.defaults.io.errorHandler})},_processLegendResponse:function(a,b){b&&
b.layers?(a.legendResponse=b,j.byId(this.id+"_"+a.id)&&d.empty(j.byId(this.id+"_"+a.id)),d.create("span",{innerHTML:this._getServiceTitle(a),"class":"esriLegendServiceLabel"},d.create("td",{align:this.alignRight?"right":"left"},d.create("tr",{},d.create("tbody",{},d.create("table",{width:"95%"},j.byId(this.id+"_"+a.id)))))),this._createLegendForLayer(a)):console.log("Legend could not get generated for "+a.url+": "+u.toJson(b))},_buildLegendItems:function(a,b,c){var h=!1,f=j.byId(this.id+"_"+a.id),
e=b.parentLayerId;if(b.subLayerIds)c=d.create("div",{id:this.id+"_"+a.id+"_"+b.id+"_group",style:"display: none;","class":-1==e?0<c?"esriLegendGroupLayer":"":this.alignRight?"esriLegendRight":"esriLegendLeft"},-1==e?f:j.byId(this.id+"_"+a.id+"_"+e+"_group")),n("ie")&&m.set(j.byId(this.id+"_"+a.id+"_"+b.id+"_group"),"display","none"),d.create("td",{innerHTML:b.name.replace(/[\<]/g,"&lt;").replace(/[\>]/g,"&gt;"),align:this.alignRight?"right":"left"},d.create("tr",{},d.create("tbody",{},d.create("table",
{width:"95%","class":"esriLegendLayerLabel"},c))));else{if(a.visibleLayers&&-1==(","+a.visibleLayers+",").indexOf(","+b.id+","))return h;c=d.create("div",{id:this.id+"_"+a.id+"_"+b.id,style:"display:none;","class":-1<e?this.alignRight?"esriLegendRight":"esriLegendLeft":""},-1==e?f:j.byId(this.id+"_"+a.id+"_"+e+"_group"));n("ie")&&m.set(j.byId(this.id+"_"+a.id+"_"+b.id),"display","none");d.create("td",{innerHTML:b.name?b.name.replace(/[\<]/g,"&lt;").replace(/[\>]/g,"&gt;"):"",align:this.alignRight?
"right":"left"},d.create("tr",{},d.create("tbody",{},d.create("table",{width:"95%","class":"esriLegendLayerLabel"},c))));a.legendResponse?h=h||this._buildLegendItems_Tools(a,b,c):a.renderer&&(h=h||this._buildLegendItems_Renderer(a,b,c))}return h},_buildLegendItems_Tools:function(a,b,c){var h=b.parentLayerId,f=this.map.getScale(),e=!1,k=function(a,b){var c,e;for(c=0;c<a.length;c++)if(b.dynamicLayerInfos)for(e=0;e<b.dynamicLayerInfos[e].length;e++){if(b.dynamicLayerInfos[e].mapLayerId==a[c].layerId)return a[c]}else if(b.id==
a[c].layerId)return a[c];return{}};if(!this._respectCurrentMapScale||this._respectCurrentMapScale&&this._isLayerInScale(a,b,f)){var p=k(a.legendResponse.layers,b).legend;if(p){var c=d.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c),i=d.create("tbody",{},c);(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(c,a,b);g.forEach(p,function(c){if(!(10.1<=a.version&&!c.values&&1<p.length&&(a._hideDefaultSymbol||"<all other values>"===c.label||!c.label)))if(c.url&&
0===c.url.indexOf("http")||c.imageData&&0<c.imageData.length)e=!0,this._buildRow_Tools(c,i,a,b.id)},this)}}e&&(m.set(j.byId(this.id+"_"+a.id+"_"+b.id),"display","block"),-1<h&&(m.set(j.byId(this.id+"_"+a.id+"_"+h+"_group"),"display","block"),this._findParentGroup(a.id,a,h)));return e},_buildRow_Tools:function(a,b,c,h){var f=d.create("tr",{},b),e;this.alignRight?(b=d.create("td",{align:"right"},f),e=d.create("td",{align:"right",width:35},f)):(e=d.create("td",{width:35},f),b=d.create("td",{},f));f=
a.url;(!n("ie")||8<n("ie"))&&a.imageData&&0<a.imageData.length?f="data:image/png;base64,"+a.imageData:0!==a.url.indexOf("http")&&(f=c.url+"/"+h+"/images/"+a.url,(h=c._getToken())&&(f+="?token="+h));h=d.create("img",{src:f,border:0,style:"opacity:"+c.opacity},e);d.create("td",{innerHTML:a.label.replace(/[\<]/g,"&lt;").replace(/[\>]/g,"&gt;"),align:this.alignRight?"right":"left"},d.create("tr",{},d.create("tbody",{},d.create("table",{width:"95%",dir:"ltr"},b))));if(9>n("ie"))h.style.filter="alpha(opacity="+
100*c.opacity+")"},_buildLegendItems_Renderer:function(a,b,c){var h=b.parentLayerId,f=this.map.getScale(),e=!1;if(!this._respectCurrentMapScale||this._isLayerInScale(a,b,f)){var k;a.renderer instanceof B?a.renderer.infos&&0<a.renderer.infos.length&&(e=!0,c=d.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c),k=d.create("tbody",{},c),(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(c,a,b),g.forEach(a.renderer.infos,function(b){var c=null;a._editable&&a.types&&
(c=this._getTemplateFromTypes(a.types,b.value));var e=b.label;if(!e||0===e.length)e=b.value;this._buildRow_Renderer(a,b.symbol,e,c,k)},this)):a.renderer instanceof C?a.renderer.infos&&0<a.renderer.infos.length&&(e=!0,c=d.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c),k=d.create("tbody",{},c),(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(c,a,b),g.forEach(a.renderer.infos,function(b){var c=b.label;if(!c||0===c.length)c=b.minValue+" - "+b.maxValue;this._buildRow_Renderer(a,
b.symbol,c,null,k)},this)):a.renderer instanceof A&&(e=!0,c=d.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c),k=d.create("tbody",{},c),(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(c,a,b),c=null,a._editable&&a.templates&&0<a.templates.length&&(c=a.templates[0]),this._buildRow_Renderer(a,a.renderer.symbol,a.renderer.label,c,k));!a._hideDefaultSymbol&&a.renderer.defaultSymbol&&(e=!0,this._buildRow_Renderer(a,a.renderer.defaultSymbol,a.renderer.defaultLabel?
a.renderer.defaultLabel:"others",null,k))}e&&(m.set(j.byId(this.id+"_"+a.id+"_"+b.id),"display","block"),-1<h&&(m.set(j.byId(this.id+"_"+a.id+"_"+h+"_group"),"display","block"),this._findParentGroup(a.id,h)));return e},_buildRow_Renderer:function(a,b,c,h,f){var e=d.create("tr",{},f),k;this.alignRight?(f=d.create("td",{align:"right"},e),k=d.create("td",{align:"right",width:35},e)):(k=d.create("td",{width:35},e),f=d.create("td",{},e));var g=e=30;"simplemarkersymbol"==b.type?(e=Math.min(Math.max(e,b.size+
12),125),g=Math.min(Math.max(g,b.size+12),125)):"picturemarkersymbol"==b.type&&(e=Math.min(Math.max(e,b.width),125),g=Math.min(b.height?b.height:g,125));k=d.create("div",{style:"width:"+e+"px;height:"+g+"px;"},k);d.create("td",{innerHTML:c?c.replace(/[\<]/g,"&lt;").replace(/[\>]/g,"&gt;").replace(/^#/,""):"",align:this.alignRight?"right":"left"},d.create("tr",{},d.create("tbody",{},d.create("table",{width:"95%"},f))));this._surfaceItems.push(this._drawSymbol(k,b,e,g,h,a.opacity))},_drawSymbol:function(a,
b,c,h,f,e){var b=s.fromJson(b.toJson()),d;if("simplelinesymbol"===b.type||"cartographiclinesymbol"===b.type||"textsymbol"===b.type){if(!b.color)return;d=b.color.toRgba();d[3]*=e;b.color.setColor(d)}else if("simplemarkersymbol"===b.type||"simplefillsymbol"===b.type){if(!b.color)return;d=b.color.toRgba();d[3]*=e;b.color.setColor(d);b.outline&&b.outline.color&&(d=b.outline.color.toRgba(),d[3]*=e,b.outline.color.setColor(d))}else if("picturemarkersymbol"===b.type)a.style.opacity=e,a.style.filter="alpha(opacity=("+
100*e+"))";a=y.createSurface(a,c,h);n("ie")&&(e=a.getEventSource(),m.set(e,"position","relative"),m.set(e.parentNode,"position","relative"));var f=this._getDrawingToolShape(b,f)||s.getShapeDescriptors(b),g;try{g=a.createShape(f.defaultShape).setFill(f.fill).setStroke(f.stroke)}catch(i){a.clear();a.destroy();return}d=g.getBoundingBox();f=d.width;b=d.height;e=-(d.x+f/2);d=-(d.y+b/2);var j=a.getDimensions(),e={dx:e+j.width/2,dy:d+j.height/2};if(f>c||b>h)c=((c<h?c:h)-5)/(f>b?f:b),l.mixin(e,{xx:c,yy:c});
g.applyTransform(e);return a},_getDrawingToolShape:function(a,b){var c;switch(b?b.drawingTool||null:null){case "esriFeatureEditToolArrow":c={type:"path",path:"M 10,1 L 3,8 L 3,5 L -15,5 L -15,-2 L 3,-2 L 3,-5 L 10,1 E"};break;case "esriFeatureEditToolTriangle":c={type:"path",path:"M -10,14 L 2,-10 L 14,14 L -10,14 E"};break;case "esriFeatureEditToolRectangle":c={type:"path",path:"M -10,-10 L 10,-10 L 10,10 L -10,10 L -10,-10 E"};break;case "esriFeatureEditToolCircle":c={type:"circle",cx:0,cy:0,r:10};
break;case "esriFeatureEditToolEllipse":c={type:"ellipse",cx:0,cy:0,rx:10,ry:5};break;default:return null}return{defaultShape:c,fill:a.getFill(),stroke:a.getStroke()}},_repaintItems:function(){g.forEach(this._surfaceItems,function(a){this._repaint(a)},this)},_repaint:function(a){if(a){a.getStroke&&a.setStroke&&a.setStroke(a.getStroke());try{a.getFill&&a.setFill&&a.setFill(a.getFill())}catch(b){}a.children&&l.isArray(a.children)&&g.forEach(a.children,this._repaint,this)}},_createHoverAction:function(a,
b,c){var d=b._hoverLabel||b._hoverLabels[c.id];if(d)b.mouseMoveHandler=b.mouseMoveHandler||{},b.mouseMoveHandler[c.id]=dojo.connect(a,"onmousemove",dojo.hitch(this,function(a,b){this.mouseX=b.clientX;this.mouseY=b.clientY;if(this.hoverLabelShowing)this.hoverLabelShowing=!1,dojo.style(dojo.byId(this.id+"_hoverLabel"),"display","none");setTimeout(dojo.hitch(this,function(a,b,c){if(a==this.mouseX&&b==this.mouseY&&!this.hoverLabelShowing)if(this.hoverLabelShowing=!0,dojo.byId(this.id+"_hoverLabel")){var e=
dojo.byId(this.id+"_hoverLabel");e.innerHTML="<span>"+c+"</span>";dojo.style(e,"top",b+"px");dojo.style(e,"left",a+15+"px");dojo.style(e,"display","")}else dojo.create("div",{innerHTML:"<span>"+c+"</span>",id:this.id+"_hoverLabel","class":"esriLegendHoverLabel",style:{top:b+"px",left:a+15+"px"}},document.body)},b.clientX,b.clientY,a),500)},d)),b.mouseOutHandler=b.mouseOutHandler||{},b.mouseOutHandler[c.id]=dojo.connect(a,"onmouseout",dojo.hitch(this,function(){this.mouseY=this.mouseX=-1;if(this.hoverLabelShowing)this.hoverLabelShowing=
!1,dojo.style(dojo.byId(this.id+"_hoverLabel"),"display","none")}))},_removeHoverHandlers:function(){g.forEach(this.layers,function(a){if(a.mouseMoveHandler)for(key in a.mouseMoveHandler)i.disconnect(a.mouseMoveHandler[key]);if(a.mouseOutHandler)for(key in a.mouseOutHandler)i.disconnect(a.mouseOutHandler[key])})},_createDynamicLayers:function(a){var b=[];g.forEach(a.dynamicLayerInfos||a.layerInfos,function(c){var d={id:c.id};d.source=c.source&&c.source.toJson();var f;a.layerDefinitions&&a.layerDefinitions[c.id]&&
(f=a.layerDefinitions[c.id]);if(f)d.definitionExpression=f;var e;a.layerDrawingOptions&&a.layerDrawingOptions[c.id]&&(e=a.layerDrawingOptions[c.id]);if(e)d.drawingInfo=e.toJson();d.minScale=c.minScale||0;d.maxScale=c.maxScale||0;b.push(d)});return b},_getTemplateFromTypes:function(a,b){var c;for(c=0;c<a.length;c++)if(a[c].id==b&&a[c].templates&&0<a[c].templates.length)return a[c].templates[0];return null},_findParentGroup:function(a,b,c){var d,f=b.dynamicLayerInfos||b.layerInfos;for(d=0;d<f.length;d++)if(c==
f[d].id){-1<f[d].parentLayerId&&(m.set(j.byId(this.id+"_"+a+"_"+f[d].parentLayerId+"_group"),"display","block"),this._findParentGroup(a,b,f[d].parentLayerId));break}},_addSubLayersToHide:function(a){function b(c,d){var f=a.layer.dynamicLayerInfos||a.layer.layerInfos,e,i;for(e=0;e<f.length;e++)if(f[e].id===c&&f[e].subLayerIds)for(i=0;i<f[e].subLayerIds.length;i++){var j=f[e].subLayerIds[i];-1===g.indexOf(d,j)&&(d.push(j),b(j,d))}}a.layer.layerInfos&&g.forEach(a.layer._hideLayersInLegend,function(c){b(c,
a.layer._hideLayersInLegend)})},_isLayerInScale:function(a,b,c){var d,f=!0;if(a.legendResponse&&a.legendResponse.layers)for(d=0;d<a.legendResponse.layers.length;d++){var e=a.legendResponse.layers[d];if(b.id==e.layerId){var g,i;if(!a.minScale&&0!==a.minScale||!a.maxScale&&0!==a.maxScale){if(0==e.minScale&&a.tileInfo)g=a.tileInfo.lods[0].scale;if(0==e.maxScale&&a.tileInfo)i=a.tileInfo.lods[a.tileInfo.lods.length-1].scale}else g=Math.min(a.minScale,e.minScale)||a.minScale||e.minScale,i=Math.max(a.maxScale,
e.maxScale);if(0<g&&g<c||i>c)f=!1;break}}else if(a.minScale||a.maxScale)if(a.minScale&&a.minScale<c||a.maxScale&&a.maxScale>c)f=!1;return f},_getServiceTitle:function(a){var b=a._titleForLegend;if(!b)(b=a.url)?-1<a.url.indexOf("/MapServer")?(b=a.url.substring(0,a.url.indexOf("/MapServer")),b=b.substring(b.lastIndexOf("/")+1,b.length)):-1<a.url.indexOf("/ImageServer")?(b=a.url.substring(0,a.url.indexOf("/ImageServer")),b=b.substring(b.lastIndexOf("/")+1,b.length)):-1<a.url.indexOf("/FeatureServer")&&
(b=a.url.substring(0,a.url.indexOf("/FeatureServer")),b=b.substring(b.lastIndexOf("/")+1,b.length)):b="",a.name&&(b=0<b.length?b+(" - "+a.name):a.name);return z.encode(b)},_isSupportedLayerType:function(a){return a&&("esri.layers.ArcGISDynamicMapServiceLayer"===a.declaredClass||"esri.layers.ArcGISImageServiceLayer"===a.declaredClass&&10.2<=a.version||"esri.layers.ArcGISTiledMapServiceLayer"===a.declaredClass||"esri.layers.FeatureLayer"===a.declaredClass||"esri.layers.KMLLayer"===a.declaredClass||
"esri.layers.GeoRSSLayer"===a.declaredClass||"esri.layers.WMSLayer"===a.declaredClass)?!0:!1}});l.mixin(o,{ALIGN_LEFT:0,ALIGN_RIGHT:1});return o});