//>>built
define(["dojo/_base/declare","dojo/_base/lang","dojo/_base/array","dojo/_base/connect","dojo/dom-class","dojo/dom-construct","dojo/dom-geometry","dojo/dom-style","dojo/has","dojo/query","esri/kernel","esri/lang","esri/domUtils","esri/units","esri/SpatialReference","esri/WKIDUnitConversion","esri/geometry/Point","esri/geometry/ScreenPoint","esri/geometry/Polyline","esri/geometry/geodesicUtils","esri/geometry/webMercatorUtils","esri/geometry/screenUtils","esri/geometry/normalizeUtils"],function(A,k,j,g,l,m,B,p,C,i,D,q,r,s,t,n,u,v,w,
x,o,y,z){return A(null,{declaredClass:"esri.dijit.Scalebar",map:null,mapUnit:null,scalebarUnit:null,unitsDictionary:[],domNode:null,screenPt1:null,screenPt2:null,constructor:function(a,c){this.metricScalebar=m.create("div",{innerHTML:"<div class='esriScaleLabelDiv'><div class='esriScalebarLabel esriScalebarLineLabel esriScalebarSecondNumber'></div></div><div class='esriScalebarLine esriScalebarMetricLine'></div>"});this.englishScalebar=m.create("div",{innerHTML:"<div class='esriScalebarLine esriScalebarEnglishLine'></div><div class='esriScaleLabelDiv'><div class='esriScalebarLabel esriScalebarLineLabel esriScalebarSecondNumber'></div></div>"});
this.domNode=m.create("div");a=a||{};if(a.map){if(a.scalebarUnit){if("english"!==a.scalebarUnit&&"metric"!==a.scalebarUnit&&"dual"!==a.scalebarUnit){console.error("scalebar unit only accepts english or metric or dual");return}this.scalebarUnit=a.scalebarUnit}else this.scalebarUnit="english";if(a.scalebarStyle){if("ruler"!==a.scalebarStyle&&"line"!==a.scalebarStyle){console.error("scalebar style must be ruler or line");return}this.scalebarStyle=a.scalebarStyle}else this.scalebarStyle="ruler";this.background=
a.background;switch(this.scalebarUnit){case "english":if("ruler"===this.scalebarStyle)this.englishScalebar.innerHTML="<div class='esriScalebarRuler'><div class='esriScalebarRulerBlock upper_firstpiece'></div><div class='esriScalebarRulerBlock upper_secondpiece'></div><div class='esriScalebarRulerBlock lower_firstpiece'></div><div class='esriScalebarRulerBlock lower_secondpiece'></div></div><div class='scaleLabelDiv'><div class='esriScalebarLabel' style='left: -3%'>0</div><div class='esriScalebarLabel esriScalebarFirstNumber'></div><div class='esriScalebarLabel esriScalebarSecondNumber'></div></div>";
this.domNode.appendChild(this.englishScalebar);break;case "metric":if("ruler"===this.scalebarStyle)this.metricScalebar.innerHTML="<div class='esriScalebarRuler'><div class='esriScalebarRulerBlock upper_firstpiece'></div><div class='esriScalebarRulerBlock upper_secondpiece'></div><div class='esriScalebarRulerBlock lower_firstpiece'></div><div class='esriScalebarRulerBlock lower_secondpiece'></div></div><div class='scaleLabelDiv'><div class='esriScalebarLabel' style='left: -3%'>0</div><div class='esriScalebarLabel esriScalebarFirstNumber'></div><div class='esriScalebarLabel esriScalebarSecondNumber'></div></div>";
this.domNode.appendChild(this.metricScalebar);break;case "dual":this.domNode.appendChild(this.metricScalebar),this.domNode.appendChild(this.englishScalebar)}this.map=a.map;c?c.appendChild(this.domNode):(this.map.container.appendChild(this.domNode),a.attachTo?l.add(this.domNode,"scalebar_"+a.attachTo):l.add(this.domNode,"scalebar_bottom-left"));l.add(this.domNode,"esriScalebar");if(this.map.loaded)this._getDistance(this.map.extent),this._checkBingMaps();else var b=g.connect(this.map,"onLoad",this,
function(){g.disconnect(b);b=null;this._getDistance(this.map.extent);this._checkBingMaps()});this._mapOnPan=g.connect(this.map,"onPan",this,this._getDistance);this._mapOnExtentChange=g.connect(this.map,"onExtentChange",this,this._getDistance);j.forEach(this.map.layerIds,function(a){"esri.virtualearth.VETiledLayer"===this.map.getLayer(a).declaredClass&&g.connect(this.map.getLayer(a),"onVisibilityChange",k.hitch(this,function(){this._checkBingMaps()}))},this);this._mapOnLayerAdd=g.connect(this.map,
"onLayerAdd",k.hitch(this,function(a){"esri.virtualearth.VETiledLayer"===a.declaredClass&&g.connect(a,"onVisibilityChange",k.hitch(this,function(){this._checkBingMaps()}));this._checkBingMaps()}));this._mapOnLayerRemove=g.connect(this.map,"onLayerRemove",k.hitch(this,this._checkBingMaps))}else console.error("scalebar: unable to find the 'map' property in parameters")},hide:function(){this._hidden=!0;r.hide(this.domNode)},show:function(){this._hidden=!1;r.show(this.domNode)},destroy:function(){g.disconnect(this._mapOnPan);
g.disconnect(this._mapOnExtentChange);g.disconnect(this._mapOnLayerAdd);g.disconnect(this._mapOnLayerRemove);this.hide();this.map=null;m.destroy(this.domNode)},_checkBingMaps:function(){l.contains(this.domNode,"scalebar_bottom-left")&&(p.set(this.domNode,"left","25px"),j.forEach(this.map.layerIds,function(a){"esri.virtualearth.VETiledLayer"===this.map.getLayer(a).declaredClass&&this.map.getLayer(a).visible&&(a="95px",this.map._mapParams.nav&&(a="115px"),p.set(this.domNode,"left",a))},this))},_getDistance:function(a){var c=
B.position(this.domNode,!0).y-this.map.position.y,c=c>this.map.height?this.map.height:c,c=0>c?0:c,b=new v(0,c),c=new v(this.map.width,c),f,e;this.mapUnit="esriDecimalDegrees";var d=y.toMapPoint(a,this.map.width,this.map.height,b),h=y.toMapPoint(a,this.map.width,this.map.height,c),b=new u(a.xmin,(a.ymin+a.ymax)/2,this.map.spatialReference),c=new u(a.xmax,(a.ymin+a.ymax)/2,this.map.spatialReference);if(3857===this.map.spatialReference.wkid||102100===this.map.spatialReference.wkid||102113===this.map.spatialReference.wkid||
this.map.spatialReference.wkt&&-1!=this.map.spatialReference.wkt.indexOf("WGS_1984_Web_Mercator"))d=o.webMercatorToGeographic(d,!0),h=o.webMercatorToGeographic(h,!0),b=o.webMercatorToGeographic(b,!0),c=o.webMercatorToGeographic(c,!0);else if(q.isDefined(n[this.map.spatialReference.wkid])||this.map.spatialReference.wkt&&0===this.map.spatialReference.wkt.indexOf("PROJCS")){this.mapUnit="linearUnit";a=Math.abs(a.xmax-a.xmin);if(q.isDefined(n[this.map.spatialReference.wkid]))e=n.values[n[this.map.spatialReference.wkid]];
else{e=this.map.spatialReference.wkt;f=e.lastIndexOf(",")+1;var g=e.lastIndexOf("]]");e=parseFloat(e.substring(f,g))}a*=e;e=a/1609;f=a/1E3}"esriDecimalDegrees"===this.mapUnit&&(a=new w(new t({wkid:4326})),a.addPath([d,h]),d=z._straightLineDensify(a,10),a=x.geodesicLengths([d],s.KILOMETERS)[0],d=new w(new t({wkid:4326})),d.addPath([b,c]),b=z._straightLineDensify(d,10),x.geodesicLengths([b],s.KILOMETERS),e=a/1.609,f=a);"english"===this.scalebarUnit?this._getScaleBarLength(e,"mi"):"metric"===this.scalebarUnit?
this._getScaleBarLength(f,"km"):"dual"===this.scalebarUnit&&(this._getScaleBarLength(e,"mi"),this._getScaleBarLength(f,"km"))},_getScaleBarLength:function(a,c){var b=50*a/this.map.width,f=0,e=c;0.1>b&&("mi"===c?(b*=5280,e="ft"):"km"===c&&(b*=1E3,e="m"));for(;1<=b;)b/=10,f++;var d,h;0.5<b?(d=1,h=0.5):0.3<b?(d=0.5,h=0.3):0.2<b?(d=0.3,h=0.2):0.15<b?(d=0.2,h=0.15):0.1<b&&(d=0.15,h=0.1);d=d/b>=b/h?h:d;b=50*(d/b);f=Math.pow(10,f)*d;this._drawScaleBar(b,f,e)},_drawScaleBar:function(a,c,b){var f=2*Math.round(a),
e,d;"mi"===b||"ft"===b?(this.englishScalebar.style.width=f+"px",a=i(".esriScalebarFirstNumber",this.englishScalebar),e=i(".esriScalebarSecondNumber",this.englishScalebar),d=i(".esriScalebarMetricLineBackground",this.englishScalebar)):(this.metricScalebar.style.width=f+"px",a=i(".esriScalebarFirstNumber",this.metricScalebar),e=i(".esriScalebarSecondNumber",this.metricScalebar),d=i(".esriScalebarMetricLineBackground",this.metricScalebar));j.forEach(d,function(a){a.style.width=f-2+"px"},this);j.forEach(a,
function(a){a.innerHTML=c},this);j.forEach(e,function(a){a.innerHTML="esriUnknown"!==this.mapUnit?2*c+b:2*c+"Unknown Unit"},this)}})});