//>>built
define(["dojo/_base/lang","dojo/_base/array","dojo/_base/Deferred","dojo/sniff","dojo/number","dojox/data/CsvStore","esri/kernel","esri/config","esri/request","esri/SpatialReference","esri/geometry/Point","esri/geometry/jsonUtils","esri/geometry/webMercatorUtils"],function(h,d,n,s,E,F,J,u,G,v,H,I,w){function x(b){var c=0,f="";d.forEach([","," ",";","|","\t"],function(e){var d=b.split(e).length;d>c&&(c=d,f=e)});return f}function y(b,c){if(!b||"[object Date]"!==Object.prototype.toString.call(b)||isNaN(b.getTime()))return!1;
var f=!0;if(s("chrome")&&/\d+\W*$/.test(c)){var e=c.match(/[a-zA-Z]{2,}/);if(e){for(var f=!1,d=0,i=e.length,o=/^((jan(uary)?)|(feb(ruary)?)|(mar(ch)?)|(apr(il)?)|(may)|(jun(e)?)|(jul(y)?)|(aug(ust)?)|(sep(tember)?)|(oct(ober)?)|(nov(ember)?)|(dec(ember)?)|(am)|(pm)|(gmt)|(utc))$/i;!f&&d<=i&&!(f=!o.test(e[d]));)d++;f=!f}}return f}function z(b,c,f){var e=b.indexOf("\n"),e=h.trim(b.substr(0,e)),g=c.columnDelimiter;g||(g=x(e));var i=new F({data:b,separator:g}),b=9>s("ie")?750:1001;i.fetch({start:0,count:b,
onComplete:function(b){var e=0,a={layerDefinition:c.layerDefinition,featureSet:{features:[],geometryType:"esriGeometryPoint"}},g=a.layerDefinition.objectIdField;!g&&!d.some(a.layerDefinition.fields,function(a){return"esriFieldTypeOID"==a.type?(g=a.name,!0):!1})&&(a.layerDefinition.fields.push({name:"__OBJECTID",alias:"__OBJECTID",type:"esriFieldTypeOID",editable:!1,domain:null}),g="__OBJECTID");var p,h,q=i._attributes,m=[],n=[];d.forEach(a.layerDefinition.fields,function(a){"esriFieldTypeDate"===
a.type?m.push(a.name):("esriFieldTypeDouble"===a.type||"esriFieldTypeInteger"===a.type)&&n.push(a.name)});c.locationInfo&&"coordinates"===c.locationInfo.locationType?(p=c.locationInfo.latitudeFieldName,h=c.locationInfo.longitudeFieldName):d.forEach(q,function(a){var b;b=d.indexOf(A,a.toLowerCase());-1!==b&&(p=a);b=d.indexOf(B,a.toLowerCase());-1!==b&&(h=a)},this);if(!p||!h)setTimeout(function(){console.error("File does not seem to contain fields with point coordinates.")},1);else{for(var q=0,s=b.length;q<
s;q++){if(1E3<=a.featureSet.features.length){setTimeout(function(){console.error("1000 feature limit reached. Unable to load any more data.")},1);break}var r=b[q],k=i.getAttributes(r),l={};d.forEach(k,function(b){if(b){var e=b;0===b.length&&d.forEach(a.layerDefinition.fields,function(a,c){a.name==="attribute_"+(c-1)&&(b="attribute_"+(c-1))});if(d.some(m,function(a){return a===b})){var e=i.getValue(r,e),c=new Date(e);l[b]=y(c,e)?c.getTime():null}else if(d.some(n,function(a){return a===b})){c=E.parse(i.getValue(r,
e));if((b==p||b==h)&&(isNaN(c)||181<Math.abs(c)))c=parseFloat(i.getValue(r,e));l[b]=isNaN(c)?null:c}else l[b]=i.getValue(r,e)}});l[g]=e;e++;var k=l[p],t=l[h];null==t||null==k||isNaN(k)||isNaN(t)||(k={geometry:(new H(t,k,new v({wkid:4326}))).toJson(),attributes:l},a.featureSet.features.push(k))}a.layerDefinition.name="csv";f&&f(a)}},onError:function(b){console.error("Error fetching items from CSV store: ",b)}});return!0}function m(b,c,f,e,g,i){0===b.length&&g(null);var o=I.getGeometryType(c),j=[];
d.forEach(b,function(a){a=new o(a);a.spatialReference=f;j.push(a)},this);c=[102113,102100,3857];f.wkid&&4326===f.wkid&&e.wkid&&-1<d.indexOf(c,e.wkid)?(d.forEach(j,function(a){if(a.xmin)a.xmin=Math.max(a.xmin,-180),a.xmax=Math.min(a.xmax,180),a.ymin=Math.max(a.ymin,-89.99),a.ymax=Math.min(a.ymax,89.99);else if(a.rings)d.forEach(a.rings,function(a){d.forEach(a,function(a){a[0]=Math.min(Math.max(a[0],-180),180);a[1]=Math.min(Math.max(a[1],-89.99),89.99)},this)},this);else if(a.paths)d.forEach(a.paths,
function(a){d.forEach(a,function(a){a[0]=Math.min(Math.max(a[0],-180),180);a[1]=Math.min(Math.max(a[1],-89.99),89.99)},this)},this);else if(a.x)a.x=Math.min(Math.max(a.x,-180),180),a.y=Math.min(Math.max(a.y,-89.99),89.99)},this),b=[],d.forEach(j,function(a){a=w.geographicToWebMercator(a);if(102100!==e.wkid)a.spatialReference=e;b.push(a.toJson())},this),g(b)):null!==f.wkid&&-1<d.indexOf(c,f.wkid)&&null!==e.wkid&&4326===e.wkid?(b=[],d.forEach(j,function(a){b.push(w.webMercatorToGeographic(a).toJson())},
this),g(b)):u.defaults.geometryService?u.defaults.geometryService.project(j,e,h.hitch(this,function(a,c){a&&a.length===b.length?(b=[],d.forEach(a,function(a){a&&(a.rings&&0<a.rings.length&&0<a.rings[0].length&&0<a.rings[0][0].length&&!isNaN(a.rings[0][0][0])&&!isNaN(a.rings[0][0][1])||a.paths&&0<a.paths.length&&0<a.paths[0].length&&0<a.paths[0][0].length&&!isNaN(a.paths[0][0][0])&&!isNaN(a.paths[0][0][1])||a.xmin&&!isNaN(a.xmin)&&a.ymin&&!isNaN(a.ymin)||a.x&&!isNaN(a.x)&&a.y&&!isNaN(a.y))?b.push(a.toJson()):
b.push(null)},this),g(b)):i(a,c)}),i):g(null)}function C(b,c){var f=[102113,102100,3857];return b&&c&&b.wkid===c.wkid&&b.wkt===c.wkt||b&&c&&b.wkid&&c.wkid&&-1<d.indexOf(f,b.wkid)&&-1<d.indexOf(f,c.wkid)?!0:!1}function D(b,c,f,e){if(b.featureSet&&0!==b.featureSet.length)if(C(f,c))e(b);else{var g=function(a){var c=[];d.forEach(b.featureSet.features,function(b,e){if(a[e])b.geometry=a[e],c.push(b)},this);e(b)},i=function(){console.error("error projecting featureSet ("+b.layerDefinition.name+"). Final try.");
e(b)},o=function(){console.error("error projecting featureSet ("+b.layerDefinition.name+"). Try one more time.");m(j,b.featureSet.geometryType,c,f,h.hitch(this,g),h.hitch(this,i))};if(b.featureSet.features&&0<b.featureSet.features.length){var j=[];d.forEach(b.featureSet.features,function(a){j.push(a.geometry)});m(j,b.featureSet.geometryType,c,f,h.hitch(this,g),h.hitch(this,o))}else e(b)}}var A="lat,latitude,y,ycenter,latitude83,latdecdeg,POINT-Y".split(","),B="lon,lng,long,longitude,x,xcenter,longitude83,longdecdeg,POINT-X".split(",");
return{latFieldStrings:A,longFieldStrings:B,buildCSVFeatureCollection:function(b){var c=new n,d=function(b){c.callback(b)};G({url:b.url,handleAs:"text",load:function(c){z(c,b,h.hitch(this,d))},error:function(b){console.error("error: "+b)}},{usePost:!1});return c},projectFeatureCollection:function(b,c){var d=new n;D(b,new v({wkid:4326}),c,h.hitch(this,function(b){d.callback(b)}));return d},generateDefaultPopupInfo:function(b){var c={esriFieldTypeDouble:1,esriFieldTypeSingle:1},f={esriFieldTypeInteger:1,
esriFieldTypeSmallInteger:1},e={esriFieldTypeDate:1},g=null,b=d.map(b.layerDefinition.fields,h.hitch(this,function(b){if("NAME"===b.name.toUpperCase())g=b.name;var d="esriFieldTypeOID"!==b.type&&"esriFieldTypeGlobalID"!==b.type&&"esriFieldTypeGeometry"!==b.type,j=null;if(d){var a=b.name.toLowerCase();if(-1<",stretched value,fnode_,tnode_,lpoly_,rpoly_,poly_,subclass,subclass_,rings_ok,rings_nok,".indexOf(","+a+",")||-1<a.indexOf("area")||-1<a.indexOf("length")||-1<a.indexOf("shape")||-1<a.indexOf("perimeter")||
-1<a.indexOf("objectid")||a.indexOf("_")===a.length-1||a.indexOf("_i")===a.length-2&&1<a.length)d=!1;b.type in f?j={places:0,digitSeparator:!0}:b.type in c?j={places:2,digitSeparator:!0}:b.type in e&&(j={dateFormat:"shortDateShortTime"})}return h.mixin({},{fieldName:b.name,label:b.alias,isEditable:!0,tooltip:"",visible:d,format:j,stringFieldOption:"textbox"})}));return{title:g?"{"+g+"}":"",fieldInfos:b,description:null,showAttachments:!1,mediaInfos:[]}},_getSeparator:x,_isValidDate:y,_processCsvData:z,
_projectGeometries:m,_sameSpatialReference:C,_projectFeatureSet:D}});