//>>built
define(["dojo/_base/declare","dojo/_base/lang","dojo/_base/kernel","dojo/_base/Deferred","dojo/_base/array","dojo/_base/sniff","dojo/Evented","dojo/DeferredList","esri/kernel","esri/lang","esri/request","esri/IdentityManager"],function(f,d,s,k,g,x,t,y,u,v,w){var e={options:{disableIdentityLookup:!0},requestParams:{f:"json"}},i=function(a){function c(c){a[c]||(a[c]=function(){var d=arguments;return k.when(a,function(a){Array.prototype.unshift.call(d,a.results||a);return i(g[c].apply(g,d))})})}if(!a)return a;a.then&&
(a=d.delegate(a));if(!a.total)a.total=k.when(a,function(a){return v.isDefined(a.total)?a.total:a.length||0});c("forEach");c("filter");c("map");c("some");c("every");return a},b={useSSL:function(a,c){return-1!==a.indexOf("https:")||e.self&&e.self.allSSL?c.replace("http:","https:"):c},formatUrl:function(a){var c=e.loggedInUser&&e.loggedInUser.credential&&e.loggedInUser.credential.token;return-1!==a.indexOf("null")?null:b.useSSL(window.location.protocol,c?a+(-1!==a.indexOf("?")?"&":"?")+("token="+c):
a)},resultsToTypedArray:function(a,c,b){b=b?b.listings||b.notifications||b.userInvitations||b.tags||b.items||b.groups||b.comments||b.results||b:[];return g.map(b,function(b){b=d.mixin(b,c||{});return a?new a(b):b})},clearFieldsFromObject:function(a,c){var b,e=a.length;if(d.isArray(a))for(b=0;b<e;b++)delete c[a[b]];else for(b in a)delete c[b];return c},requestToTypedArray:function(a,c,e,f,g){return i(b.request(a,c,e).then(d.partial(b.resultsToTypedArray,f,g)))},request:function(a,c,h){c&&c.portal&&
delete c.portal;c=d.mixin(d.mixin({},c||{}),e.requestParams);h=d.mixin(h||{},e.options);return w({url:b.useSSL(window.location.protocol,a.url||a),content:c,callbackParamName:"callback",timeout:h&&h.timeout||0},h)},formatQueryParams:function(a,b,h){a=d.mixin(d.mixin({},a),d.isString(b)?{q:b}:b||{});a.q=!h&&e.extraQuery?"("+a.q+")"+e.extraQuery:a.q;return a}},l=f([],{declaredClass:"esri.arcgis.PortalComment",constructor:function(a){d.mixin(this,a);this.url=this.item.itemUrl+"/comments/"+this.id;this.created=
this.created?new Date(this.created):null}}),m=f([],{declaredClass:"esri.arcgis.PortalRating",constructor:function(a){d.mixin(this,a);this.url=this.item.itemUrl+"/rating";this.created=this.created?new Date(this.created):null}}),j=f([],{declaredClass:"esri.arcgis.PortalItem",constructor:function(a){d.mixin(this,a);this.folderId=this.ownerFolder||this.folderId;this.itemUrl=(this.portal&&this.portal.portalUrl)+"content/items/"+this.id;this.userItemUrl=this.itemUrl.replace("content","content/users/"+this.owner+
(this.folderId?"/"+this.folderId:""));this.itemDataUrl=b.formatUrl(this.itemUrl+"/data");this.thumbnailUrl=b.formatUrl(this.itemUrl+"/info/"+this.thumbnail);this.created=this.created?new Date(this.created):null;this.uploaded=this.uploaded?new Date(this.uploaded):null;this.modified=this.modified?new Date(this.modified):null},addComment:function(a){var c=d.isString(a)?{comment:a}:a;return b.request(this.itemUrl+"/addComment",c,{usePost:!0}).then(d.hitch(this,function(a){return l(d.mixin(c,{id:a.commentId,
item:this}))}))},updateComment:function(a){if(a&&a.url&&a.comment)return b.request(a.url+"/update",{comment:a.comment},{usePost:!0}).then(function(b){a.id=b.commentId;return a});throw Error();},getComments:function(){return b.requestToTypedArray(this.itemUrl+"/comments",null,null,l,{item:this})},deleteComment:function(a){if(a&&a.url)return b.request(a.url+"/delete",null,{usePost:!0});throw Error();},addRating:function(a){var c=d.isObject(a)?a:{rating:parseFloat(a)};return b.request(this.itemUrl+"/addRating",
c,{usePost:!0}).then(d.hitch(this,function(a){return new m(d.mixin(c,{id:a.ratingId,item:this}))}))},getRating:function(){return b.request(this.itemUrl+"/rating").then(d.hitch(this,function(a){return new m(d.mixin(a,{item:this}))}))},deleteRating:function(){return b.request(this.itemUrl+"/deleteRating",null,{usePost:!0})}}),n=f([],{declaredClass:"esri.arcgis.PortalListing",constructor:function(a){d.mixin(this,a);this.id=this.itemId;this.url=(this.portal&&this.portal.portalUrl)+"content/"+(this.userItemUrl?
"items/":"listings/")+this.itemId;this.created=this.created?new Date(this.created):null;this.banner=b.formatUrl(this.url+"/info/"+this.banner);this.thumbnail=b.formatUrl(this.url+"/info/"+this.thumbnail);this.largeThumbnail=b.formatUrl(this.url+"/info/"+this.largeThumbnail);this.avgRating=this.avgRating||0;this.numRatings=this.numRatings||0;this.numComments=this.numComments||0;this.commentsUrl=(this.portal&&this.portal.portalUrl)+"/content/items/"+this.itemId+"/comments";this.listingProperties=this.listingProperties||
{priceDesc:"",creditsPerTransaction:0,licenseType:"free",trialSupported:!1,trialDuration:0,listingAccess:"private"};for(var c in this.listingProperties)this[c]&&(this.listingProperties[c]=this[c]);this.properties=this.properties||{systemRequirements:"",termsAndConditions:"",version:"1.0"};this.screenshots=g.map(this.screenshots,d.hitch(this,function(a){return b.formatUrl(this.url+"/info/"+a)}));this.vendor.vendorPhone=this.vendor.vendorPhone;this.vendor.vendorEmail=this.vendor.vendorEmail;this.vendor.vendorUrl=
this.vendor.vendorUrl;this.vendor.description=this.vendor.description;this.vendor.thumbnail=this.userItemUrl?b.formatUrl(this.portal.portalUrl+"/accounts/self/resources/"+this.vendor.thumbnail):b.formatUrl(this.url+"/info/"+this.vendor.thumbnail)},getComments:function(){return b.requestToTypedArray(this.commentsUrl,null,null,l,{item:this})},getVendor:function(){return this.vendor}}),o=f([],{declaredClass:"esri.arcgis.PortalProvision",constructor:function(a){d.mixin(this,a);this.created=this.created?
new Date(this.created):null;this.startDate=this.startDate?new Date(this.startDate):null;this.endDate=this.endDate&&-1!==this.endDate?new Date(this.endDate):null;this.listing=a.listing?new n(d.mixin(a.listing,{portal:this.portal})):null}}),p=f([],{declaredClass:"esri.arcgis.PortalGroup",constructor:function(a){d.mixin(this,a);this.url=(this.portal&&this.portal.portalUrl)+"community/groups/"+this.id;this.thumbnailUrl=b.formatUrl(this.url+"/info/"+this.thumbnail);this.modified=this.modified?new Date(this.modified):
null;this.created=this.created?new Date(this.created):null},getMembers:function(){return b.request(this.url+"/users")},queryItems:function(a){a=b.formatQueryParams({},a);a.q="group:"+this.id+(a.q?" "+a.q:"");return this.portal.queryItems(a)}}),q=f([],{declaredClass:"esri.arcgis.PortalFolder",constructor:function(a){d.mixin(this,a);this.url=(this.portal&&this.portal.portalUrl)+"content/users/"+this.username+"/"+this.id;this.created=this.created?new Date(this.created):null},getItems:function(){return b.requestToTypedArray(this.url,
null,null,j,{portal:this.portal,folderId:this.id})}}),r=f([],{declaredClass:"esri.arcgis.PortalUser",constructor:function(a){d.mixin(this,a);this.url=(this.portal&&this.portal.portalUrl)+"community/users/"+this.username;this.userContentUrl=(this.portal&&this.portal.portalUrl)+"content/users/"+this.username;this.thumbnailUrl=b.formatUrl(this.url+"/info/"+this.thumbnail);this.modified=this.modified?new Date(this.modified):null;this.created=this.created?new Date(this.created):null},getGroups:function(){return i(b.request(this.url).then(d.hitch(this,
function(a){return b.resultsToTypedArray(p,{portal:this.portal},a.groups)})))},getNotifications:function(){return b.requestToTypedArray(this.url+"/notifications",null,null,null,{portal:this.portal})},getGroupInvitations:function(){return b.requestToTypedArray(this.url+"/invitations",null,null,null,{portal:this.portal})},getTags:function(){return b.requestToTypedArray(this.url+"/tags",null,null,null,{portal:this.portal})},getFolders:function(){return i(this.getContent().then(function(a){return a.folders}))},
getItems:function(a){return i(this.getContent(a).then(function(a){return a.items}))},getItem:function(a){return b.request(this.portal.portalUrl+"content/items/"+a).then(d.hitch(this,function(a){return new j(d.mixin(a,{portal:this.portal}))}))},getContent:function(a){var c=this.url.replace("community","content")+(a?"/"+a:"");return b.request(c).then(d.hitch(this,function(c){c.folders=b.resultsToTypedArray(q,{portal:this.portal},c.folders);c.items=b.resultsToTypedArray(j,{portal:this.portal,folderId:a},
c.items);return c}))}});return{Portal:f([t],{declaredClass:"esri.arcgis.Portal",onLoad:function(){},constructor:function(a){d.mixin(this,{url:a});this.init(a).then(d.hitch(this,function(){this.emit("ready",this);this.onLoad(this)}))},init:function(a,c){a=(a||this.portalUrl).replace(/\/+$/,"");this.portalUrl=-1!==a.indexOf("/sharing")?a+"/":a+"/sharing/rest/";return this._getSelf(this.portalUrl).then(d.hitch(this,function(a){e.self=d.mixin({},a);if(a=a.user)a.portal=this,a=new r(a),e.loggedInUser=
d.mixin({},d.mixin(a,{credential:c}));if(e.self.id&&!1===e.self.canSearchPublic)e.extraQuery=" AND orgid:"+e.self.id;d.mixin(this,e.self);this.thumbnailUrl=b.formatUrl(this.portalUrl+"accounts/self/resources/"+this.thumbnail);this.isOrganization=this.access&&this.access.length||!1;this.created=this.created?new Date(this.created):null;this.modified=this.modified?new Date(this.modified):null;return this}))},signIn:function(){if(e&&e.loggedInUser){var a=new k;a.resolve(e.loggedInUser);return a}e.options.disableIdentityLookup=
!1;return u.id.getCredential(this.portalUrl).then(d.hitch(this,"init",this.url)).then(function(){return e.loggedInUser},function(a){e.options.disableIdentityLookup=!0;throw a;})},signOut:function(){e.loggedInUser.credential&&e.loggedInUser.credential.destroy();e.loggedInUser=null;e.options.disableIdentityLookup=!0;b.clearFieldsFromObject(e.self,this);e.self=null;return this.init(this.url)},getPortalUser:function(){return e.loggedInUser},addResource:function(a,c){return b.request(this.portalUrl+"portals/self/addResource",
{key:a,text:c},{usePost:!0})},update:function(a){return b.request(this.portalUrl+"portals/self/update",a,{usePost:!0})},queryGroups:function(a){return this._queryPortal(this.portalUrl+"community/groups",b.formatQueryParams({},a),p)},queryItems:function(a){return this._queryPortal(this.portalUrl+"search",b.formatQueryParams({},a),j)},queryListings:function(a){var a=b.formatQueryParams({},a,!0),c="";if(a.q&&-1<a.q.toLowerCase().indexOf("mylistings:true"))a.q=a.q.toLowerCase().replace("mylistings:true",
""),c="?mylistings=true";return this._queryPortal(this.portalUrl+"content/listings"+c,a,n)},getPurchases:function(){return this.getCustomers().then(d.hitch(this,function(a){return a.purchases}))},getInterests:function(){return this.getCustomers().then(d.hitch(this,function(a){return a.interests}))},getTrials:function(){return this.getCustomers().then(d.hitch(this,function(a){return a.trials}))},getCustomers:function(){return b.request(this.portalUrl+"portals/self/customers")},getMyPurchases:function(){return this.getPurchases().then(function(a){return a.purchases})},
getMyInterests:function(){return this.getPurchases().then(function(a){return a.interests})},getPurchases:function(){return b.request(this.portalUrl+"portals/self/purchases").then(d.hitch(this,function(a){a.interests=g.map(a.interests,function(a){return d.mixin(a.provision,{listing:a.listing})});a.purchases=g.map(a.purchases,function(a){return d.mixin(a.provision,{listing:a.listing})});a.trials=g.map(a.trials,function(a){return d.mixin(a.provision,{listing:a.listing})});a.interests=b.resultsToTypedArray(o,
{portal:this},a.interests);a.trials=b.resultsToTypedArray(o,{portal:this},a.trials);a.purchases=b.resultsToTypedArray(o,{portal:this},a.purchases);return a}))},queryUsers:function(a){return this._queryPortal(this.portalUrl+"community/users",b.formatQueryParams({sortField:"username"},a),r)},_getSelf:function(a){return b.request(a+"accounts/self?culture="+s.locale)},_queryPortal:function(a,c,e){var f=d.mixin({num:10,start:0,sortField:"title",sortOrder:"asc"},c),g=["start","query","num","nextStart"],
a=b.request(a,f).then(d.hitch(this,function(a){a.results=b.resultsToTypedArray(e,{portal:this},a);a.queryParams=d.mixin({},f);a.nextQueryParams=d.mixin(f,{start:a.nextStart});return b.clearFieldsFromObject(g,a)})),a=d.delegate(a);a.queryParams=d.mixin({},f);a.nextQueryParams=k.when(a,function(a){return a.nextQueryParams});return i(a)}}),PortalFolder:q,PortalGroup:p,PortalItem:j,PortalComment:l,PortalRating:m,PortalUtil:b,PortalResult:i,PortalListing:n}});