//>>built
define(["dojo/_base/declare","dojo/_base/lang","dojo/_base/Deferred","dojo/_base/array","dojo/_base/json","dojo/_base/config","dojo/has","dojo/io-query","esri/kernel","esri/config","esri/lang","esri/request","esri/deferredUtils","esri/urlUtils","esri/geometry/Extent","esri/geometry/Point","esri/SpatialReference","esri/layers/MosaicRule","esri/layers/DynamicMapServiceLayer","esri/layers/TimeInfo","esri/layers/Field","esri/graphic","esri/tasks/ImageServiceIdentifyTask","esri/tasks/ImageServiceIdentifyParameters"],function(A,d,l,i,q,t,
J,B,K,y,v,r,k,m,z,C,L,n,D,E,F,G,H,I){return A(D,{declaredClass:"esri.layers.ArcGISImageServiceLayer",_eventMap:{"rendering-change":!0,"mosaic-rule-change":!0},constructor:function(a,b){this._url=m.urlToObject(a);var c=b&&b.imageServiceParameters;this.format=c&&c.format;this.interpolation=c?c.interpolation:null;this.compressionQuality=c?c.compressionQuality:null;this.bandIds=c?c.bandIds:null;this.mosaicRule=c?c.mosaicRule:null;this.renderingRule=c?c.renderingRule:null;this._params=d.mixin({},this._url.query,
{f:"image",interpolation:this.interpolation,format:this.format,compressionQuality:this.compressionQuality,bandIds:this.bandIds?this.bandIds.join(","):null},c?c.toJson():{});this._initLayer=d.hitch(this,this._initLayer);this._queryVisibleRastersHandler=d.hitch(this,this._queryVisibleRastersHandler);this._visibleRasters=[];this.useMapImage=b&&b.useMapImage||!1;this.infoTemplate=b&&b.infoTemplate;this._rasterAttributeTableFields=[];this._rasterAttributeTableFeatures=[];this._loadCallback=b&&b.loadCallback;
(c=b&&b.resourceInfo)?this._initLayer(c):r({url:this._url.path,content:d.mixin({f:"json"},this._url.query),callbackParamName:"callback",load:this._initLayer,error:this._errorHandler});this.registerConnectEvents()},disableClientCaching:!1,_initLayer:function(a){this._findCredential();(this.credential&&this.credential.ssl||a&&a._ssl)&&this._useSSL();var b=this.minScale,c=this.maxScale;d.mixin(this,a);this.minScale=b;this.maxScale=c;this.initialExtent=this.fullExtent=this.extent=new z(a.extent);this.spatialReference=
this.initialExtent.spatialReference;this.pixelSizeX=parseFloat(this.pixelSizeX);this.pixelSizeY=parseFloat(this.pixelSizeY);var h=this.minValues,o=this.maxValues,f=this.meanValues,e=this.stdvValues,j=this.bands=[];for(b=0,c=this.bandCount;b<c;b++)j[b]={min:h[b],max:o[b],mean:f[b],stddev:e[b]};this.timeInfo=(b=this.timeInfo)&&b.timeExtent?new E(b):null;c=this.fields=[];if(h=a.fields)for(b=0;b<h.length;b++)c.push(new F(h[b]));this.version=a.currentVersion;if(!this.version)this.version="fields"in a||
"objectIdField"in a||"timeInfo"in a?10:9.3;v.isDefined(a.minScale)&&!this._hasMin&&this.setMinScale(a.minScale);v.isDefined(a.maxScale)&&!this._hasMax&&this.setMaxScale(a.maxScale);b={};a.defaultMosaicMethod?(b.method=a.defaultMosaicMethod,b.operation=a.mosaicOperator,b.sortField=a.sortField,b.sortValue=a.sortValue):b.method=n.METHOD_NONE;this.defaultMosaicRule=new n(b);this.defaultMosaicRule.ascending=!0;10<this.version&&this.hasRasterAttributeTable&&this.getRasterAttributeTable().then(d.hitch(this,
function(a){if(a&&a.features&&0<a.features.length)this._rasterAttributeTableFeatures=d.clone(a.features);if(a&&a.fields&&0<a.fields.length)this._rasterAttributeTableFields=d.clone(a.fields)}));this.loaded=!0;this.onLoad(this);if(a=this._loadCallback)delete this._loadCallback,a(this)},getKeyProperties:function(){var a=this._url.path+"/keyProperties",b=new l(k._dfdCanceller);10<this.version?(b._pendingDfd=r({url:a,content:{f:"json"},handleAs:"json",callbackParamName:"callback"}),b._pendingDfd.then(function(a){b.callback(a)},
function(a){b.errback(a)})):(a=Error("Layer does not have key properties"),a.log=t.isDebug,b.errback(a));return b},getRasterAttributeTable:function(){var a=this._url.path+"/rasterAttributeTable",b=new l(k._dfdCanceller);10<this.version&&this.hasRasterAttributeTable?(b._pendingDfd=r({url:a,content:{f:"json"},handleAs:"json",callbackParamName:"callback"}),b._pendingDfd.then(function(a){b.callback(a)},function(a){b.errback(a)})):(a=Error("Layer does not support raster attribute table"),a.log=t.isDebug,
b.errback(a));return b},_getRasterAttributeTableFeatures:function(){var a=new l;if(this._rasterAttributeTableFeatures&&0<this._rasterAttributeTableFeatures.length)return a.resolve(this._rasterAttributeTableFeatures),a;if(10<this.version&&this.hasRasterAttributeTable)return a=this.getRasterAttributeTable(),a.then(d.hitch(this,function(a){if(a&&a.features&&0<a.features.length)this._rasterAttributeTableFeatures=d.clone(a.features)})),a;a.resolve(this._rasterAttributeTableFeatures);return a},getCustomRasterFields:function(a){var b=
a?a.rasterAttributeTableFieldPrefix:"",c={name:"Raster.ItemPixelValue",alias:"Item Pixel Value",domain:null,editable:!1,length:50,type:"esriFieldTypeString"},a=this.fields?d.clone(this.fields):[],h=a.length;a[h]={name:"Raster.ServicePixelValue",alias:"Service Pixel Value",domain:null,editable:!1,length:50,type:"esriFieldTypeString"};this.capabilities&&-1<this.capabilities.toLowerCase().indexOf("catalog")&&(a[h+1]=c);this._rasterAttributeTableFields&&0<this._rasterAttributeTableFields.length&&(c=i.filter(this._rasterAttributeTableFields,
function(a){return"esriFieldTypeOID"!==a.type&&"value"!==a.name.toLowerCase()}),c=i.map(c,function(a){var c=d.clone(a);c.name=b+a.name;return c}),a=a.concat(c));return a},getImageUrl:function(a,b,c,h){var o=a.spatialReference.wkid||q.toJson(a.spatialReference.toJson());delete this._params._ts;var f=this._url.path+"/exportImage?";d.mixin(this._params,{bbox:a.xmin+","+a.ymin+","+a.xmax+","+a.ymax,imageSR:o,bboxSR:o,size:b+","+c},this.disableClientCaching?{_ts:(new Date).getTime()}:{});var e=this._params.token=
this._getToken(),a=m.addProxy(f+B.objectToQuery(d.mixin(this._params,{f:"image"})));a.length>y.defaults.io.postLength||this.useMapImage?this._jsonRequest=r({url:f,content:d.mixin(this._params,{f:"json"}),callbackParamName:"callback",load:function(a){a=a.href;e&&(a+=-1===a.indexOf("?")?"?token="+e:"&token="+e);h(m.addProxy(a))},error:this._errorHandler}):h(a)},onRenderingChange:function(){},onMosaicRuleChange:function(){},setInterpolation:function(a,b){this.interpolation=this._params.interpolation=
a;b||this.refresh(!0)},setCompressionQuality:function(a,b){this.compressionQuality=this._params.compressionQuality=a;b||this.refresh(!0)},setBandIds:function(a,b){var c=!1;this.bandIds!==a&&(c=!0);this.bandIds=a;this._params.bandIds=a.join(",");if(c&&!b)this.onRenderingChange();b||this.refresh(!0)},setDefaultBandIds:function(a){this.bandIds=this._params.bandIds=null;a||this.refresh(!0)},setDisableClientCaching:function(a){this.disableClientCaching=a},setMosaicRule:function(a,b){var c=!1;this.mosaicRule!==
a&&(c=!0);this.mosaicRule=a;this._params.mosaicRule=q.toJson(a.toJson());if(c&&!b)this.onMosaicRuleChange();b||this.refresh(!0)},setRenderingRule:function(a,b){var c=!1;this.renderingRule!==a&&(c=!0);this.renderingRule=a;this._params.renderingRule=a?q.toJson(a.toJson()):null;if(c&&!b)this.onRenderingChange();b||this.refresh(!0)},setImageFormat:function(a,b){this.format=this._params.format=a;b||this.refresh(!0)},setInfoTemplate:function(a){this.infoTemplate=a},setDefinitionExpression:function(a,b){var c=
this.mosaicRule?this.mosaicRule.toJson():{};if(!this.mosaicRule)this.defaultMosaicRule?c=this.defaultMosaicRule.toJson():c.method=n.METHOD_NONE;c.where=a;this.setMosaicRule(new n(c),b);return this},getDefinitionExpression:function(){return this.mosaicRule?this.mosaicRule.where:null},refresh:function(a){if(a)this.inherited(arguments);else{var b=this.disableClientCaching;this.disableClientCaching=!0;this.inherited(arguments);this.disableClientCaching=b}},exportMapImage:function(a,b){var c=y.defaults.map,
c=d.mixin({size:c.width+","+c.height},this._params,a?a.toJson(this.normalization):{},{f:"json"});delete c._ts;this._exportMapImage(this._url.path+"/exportImage",c,b)},queryVisibleRasters:function(a,b,c,h){var d=this._map,f=k._fixDfd(new l(k._dfdCanceller));this._visibleRasters=[];var e,j,g=!0;if(this.infoTemplate&&this.infoTemplate.info.fieldInfos&&0<this.infoTemplate.info.fieldInfos.length){g=!1;for(e=0;e<this.infoTemplate.info.fieldInfos.length;e++)(j=this.infoTemplate.info.fieldInfos[e])&&j.visible&&
"raster.servicepixelvalue"!==j.fieldName.toLowerCase()&&(g=!0)}e=new I;e.geometry=a.geometry.getCenter();e.returnGeometry=!0;e.returnCatalogItems=g;e.timeExtent=a.timeExtent;e.mosaicRule=this.mosaicRule?this.mosaicRule:null;e.renderingRule=this.renderingRule?this.renderingRule:null;if(d)a=new C((d.extent.xmax-d.extent.xmin)/(2*d.width),(d.extent.ymax-d.extent.ymin)/(2*d.height),d.extent.spatialReference),e.pixelSize=a;var i=this,a=new H(this.url);(f._pendingDfd=a.execute(e)).addCallbacks(function(a){i._queryVisibleRastersHandler(a,
b,c,h,f)},function(a){i._resolve([a],null,h,f,!0)});return f},_queryVisibleRastersHandler:function(a,b,c,h,o){var f=a.features,e=a.value,j;if(a.catalogItems)f=a.catalogItems.features,j=a.properties.Values;this._visibleRasters=[];var g,a=-1<e.toLowerCase().indexOf("nodata");e&&!f&&!a&&(f=[],g=new G(new z(this.fullExtent),null,{ObjectId:0}),f.push(g));var k=[];if(f){var l=this._getDomainFields(this.getCustomRasterFields(b)),r=b?b.returnDomainValues:!1,n=b&&b.rasterAttributeTableFieldPrefix,s,u,q,m,
p,w,t,x;this._getRasterAttributeTableFeatures().then(d.hitch(this,function(a){for(s=0;s<f.length;s++){g=f[s];g.setInfoTemplate(this.infoTemplate);if(e&&(u=e,j&&j.length>=s&&(q=j[s],u=q.replace(/ /gi,", ")),g.attributes["Raster.ItemPixelValue"]=u,g.attributes["Raster.ServicePixelValue"]=e,a&&0<a.length&&(m=i.filter(a,function(a){if(a&&a.attributes)return a.attributes.hasOwnProperty("Value")?a.attributes.Value==u:a.attributes.VALUE==u}),0<m.length&&(p=d.clone(m[0]),n&&p)))){x={};for(w in p.attributes)p.attributes.hasOwnProperty(w)&&
(t=n+w,x[t]=p.attributes[w]);p.attributes=x;g.attributes=d.mixin(g.attributes,p.attributes)}r&&l&&0<l.length&&i.forEach(l,function(a){if(a){var b=g.attributes[a.name];v.isDefined(b)&&(b=this._getDomainValue(a.domain,b),v.isDefined(b)&&(g.attributes[a.name]=b))}},this);k.push(g);this._visibleRasters.push(g)}this._resolve([k,null,!0],null,c,o)}))}else this._resolve([k,null,null],null,c,o)},getVisibleRasters:function(){var a=this._visibleRasters,b=[],c;for(c in a)a.hasOwnProperty(c)&&b.push(a[c]);return b},
_getDomainFields:function(a){if(a){var b=[];i.forEach(a,function(a){if(a.domain){var d={};d.name=a.name;d.domain=a.domain;b.push(d)}});return b}},_getDomainValue:function(a,b){if(a&&a.codedValues){var c;i.some(a.codedValues,function(a){return a.code===b?(c=a.name,!0):!1});return c}},_resolve:function(a,b,c,d,i){b&&this[b].apply(this,a);c&&c.apply(null,a);d&&k._resDfd(d,a,i)}})});