//>>built
define(["dojo/_base/declare","dojo/_base/config","dojo/_base/connect","dojo/_base/lang","dojo/_base/Deferred","dojo/_base/json","dojo/has","esri/Evented","esri/kernel","esri/lang","esri/request","esri/deferredUtils","esri/urlUtils","esri/SpatialReference","esri/geometry/Extent"],function(j,k,c,f,l,m,t,n,g,d,o,p,q,h,r){var i=j([n],{declaredClass:"esri.layers.Layer",_eventMap:{error:["error"],load:["layer"],"opacity-change":["opacity"],"update-end":["error"],"visibility-change":["visible"]},constructor:function(a,b){a&&
f.isString(a)?this._url=q.urlToObject(this.url=a):(this.url=this._url=null,(b=b||a)&&b.layerDefinition&&(b=null));this.spatialReference=new h(4326);this.initialExtent=new r(-180,-90,180,90,new h(4326));this._map=this._div=null;this.normalization=!0;if(b){if(b.id)this.id=b.id;if(!1===b.visible)this.visible=!1;if(d.isDefined(b.opacity))this.opacity=b.opacity;d.isDefined(b.minScale)&&this.setMinScale(b.minScale);d.isDefined(b.maxScale)&&this.setMaxScale(b.maxScale);this.attributionDataUrl=b.attributionDataUrl||
"";this.hasAttributionData=!!this.attributionDataUrl;if(d.isDefined(b.showAttribution))this.showAttribution=b.showAttribution}this._errorHandler=f.hitch(this,this._errorHandler);if(this.managedSuspension){var e=this._setMap;this._setMap=function(a){var b=e.apply(this,arguments);this.evaluateSuspension();if(this.suspended&&!a.loaded)var d=c.connect(a,"onLoad",this,function(){c.disconnect(d);d=null;this.evaluateSuspension()});return b}}this.registerConnectEvents()},id:null,visible:!0,loaded:!1,minScale:0,
maxScale:0,visibleAtMapScale:!1,suspended:!0,attributionDataUrl:"",hasAttributionData:!1,showAttribution:!0,_errorHandler:function(a){this.onError(a)},_setMap:function(a){this._map=a;this._lyrZEHandle=c.connect(a,"onZoomEnd",this,this._processMapScale);if(a.loaded)this.visibleAtMapScale=this._isMapAtVisibleScale();else var b=c.connect(a,"onLoad",this,function(){c.disconnect(b);b=null;this._processMapScale()})},_unsetMap:function(){c.disconnect(this._lyrZEHandle);this._map=this._lyrZEHandle=null;this.suspended=
!0},_cleanUp:function(){this._map=this._div=null},_fireUpdateStart:function(){if(!this.updating)this.updating=!0,this.onUpdateStart(),this._map&&this._map._incr()},_fireUpdateEnd:function(a,b){this.updating=!1;this.onUpdateEnd(a,b);this._map&&this._map._decr()},_getToken:function(){var a=this._url,b=this.credential;return a&&a.query&&a.query.token||b&&b.token||void 0},_findCredential:function(){this.credential=g.id&&this._url&&g.id.findCredential(this._url.path)},_useSSL:function(){var a=this._url,
b=/^http:/i;if(this.url)this.url=this.url.replace(b,"https:");if(a&&a.path)a.path=a.path.replace(b,"https:")},refresh:function(){},show:function(){this.setVisibility(!0)},hide:function(){this.setVisibility(!1)},setMinScale:function(a){this.setScaleRange(a)},setMaxScale:function(a){this.setScaleRange(null,a)},setScaleRange:function(a,b){var e=d.isDefined(a),c=d.isDefined(b);if(!this.loaded)this._hasMin=this._hasMin||e,this._hasMax=this._hasMax||c;var s=this.minScale,f=this.maxScale;this.minScale=(e?
a:this.minScale)||0;this.maxScale=(c?b:this.maxScale)||0;if(s!==this.minScale||f!==this.maxScale)this.onScaleRangeChange(),this._processMapScale()},suspend:function(){this._suspended=!0;this.evaluateSuspension()},resume:function(){this._suspended=!1;this.evaluateSuspension()},canResume:function(){return this.loaded&&this._map&&this._map.loaded&&this.visible&&this.visibleAtMapScale&&!this._suspended},evaluateSuspension:function(){this.canResume()?this.suspended&&this._resume():this.suspended||this._suspend()},
_suspend:function(){this.suspended=!0;this.onSuspend();if(this._map)this._map.onLayerSuspend(this)},_resume:function(){this.suspended=!1;var a=void 0===this._resumedOnce;if(a)this._resumedOnce=!0;this.onResume({firstOccurrence:a});if(this._map)this._map.onLayerResume(this)},_processMapScale:function(){var a=this.visibleAtMapScale;this.visibleAtMapScale=this._isMapAtVisibleScale();a!==this.visibleAtMapScale&&(this.onScaleVisibilityChange(),this.evaluateSuspension())},isVisibleAtScale:function(a){return a?
i.prototype._isMapAtVisibleScale.apply(this,arguments):!1},_isMapAtVisibleScale:function(a){if(!a&&(!this._map||!this._map.loaded))return!1;var a=a||this._map.getScale(),b=this.minScale,e=this.maxScale,c=!b,d=!e;!c&&a<=b&&(c=!0);!d&&a>=e&&(d=!0);return c&&d?!0:!1},getAttributionData:function(){var a=this.attributionDataUrl,b=new l(p._dfdCanceller);this.hasAttributionData&&a?(b._pendingDfd=o({url:a,content:{f:"json"},handleAs:"json",callbackParamName:"callback"}),b._pendingDfd.then(function(a){b.callback(a)},
function(a){b.errback(a)})):(a=Error("Layer does not have attribution data"),a.log=k.isDebug,b.errback(a));return b},getResourceInfo:function(){var a=this.resourceInfo;return f.isString(a)?m.fromJson(a):f.clone(a)},setNormalization:function(a){this.normalization=a},setVisibility:function(a){if(this.visible!==a)this.visible=a,this.onVisibilityChange(this.visible),this.evaluateSuspension()},onLoad:function(){},onVisibilityChange:function(){},onScaleRangeChange:function(){},onScaleVisibilityChange:function(){},
onSuspend:function(){},onResume:function(){},onUpdate:function(){},onUpdateStart:function(){},onUpdateEnd:function(){},onError:function(){}});return i});