//>>built
define(["dojo/_base/declare","dojo/_base/connect","dojo/_base/lang","dojo/_base/array","dojo/has","esri/kernel","esri/geometry/Point","esri/tasks/query","esri/layers/RenderMode","esri/layers/GridLayout"],function(r,j,s,o,w,x,t,q,u,v){return r([u],{declaredClass:"esri.layers._OnDemandMode",constructor:function(b){this.featureLayer=b;this._featureMap={};this._queryErrorHandler=s.hitch(this,this._queryErrorHandler)},initialize:function(b){this.inherited(arguments);var a=this.featureLayer,c=a._srInfo;this._gridLayer=
new v(new t(c?c.valid[0]:b.extent.xmin,b.extent.ymax,b.spatialReference),{width:a._tileWidth,height:a._tileHeight},{width:b.width,height:b.height},c);this._cellMap={};this._gridLayer.setResolution(b.extent)},startup:function(){this._ioQueue=[];this.featureLayer.suspended||(this._zoomHandler(),this._enableConnectors())},propertyChangeHandler:function(b){this._init&&(2>b?this._zoomHandler():console.log("FeatureLayer: layer in on-demand mode does not support time definitions. Layer id = "+this.featureLayer.id+
", Layer URL = "+this.featureLayer.url))},destroy:function(){this._disableConnectors();this.inherited(arguments)},drawFeature:function(b){var a=b.geometry,c=[];if(a){var c=this._gridLayer.getCellsInExtent("point"===a.type?{xmin:a.x,ymin:a.y,xmax:a.x,ymax:a.y}:a.getExtent(),!1).cells,a=this._cellMap,e,d,g=b.attributes[this.featureLayer.objectIdField],f,h,i;for(e=0;e<c.length;e++)d=c[e],f=d.latticeID,h=d.row,i=d.col,f?d=a[f]=a[f]||d:(a[h]=a[h]||{},d=a[h][i]=a[h][i]||d),d.features=d.features||[],d.features.push(b),
this._addFeatureIIf(g,b),this._incRefCount(g)}},suspend:function(){this._init&&this._disableConnectors()},resume:function(){this._init&&(this._enableConnectors(),this._zoomHandler())},refresh:function(){this._zoomHandler()},_enableConnectors:function(){var b=this.map;this._zoomConnect=j.connect(b,"onZoomEnd",this,this._zoomHandler);this._panConnect=j.connect(b,"onPanEnd",this,this._panHandler);this._resizeConnect=j.connect(b,"onResize",this,this._panHandler)},_disableConnectors:function(){j.disconnect(this._zoomConnect);
j.disconnect(this._panConnect);j.disconnect(this._resizeConnect)},_zoomHandler:function(){this._processIOQueue(!0);var b=this.featureLayer,a=this.map;if(!b.suspended)b._fireUpdateStart(),this._clearIIf(),(b=b._trackManager)&&b.clearTracks(),this._cellMap={},this._gridLayer.setResolution(a.extent),this._sendRequest()},_panHandler:function(b){this.featureLayer._fireUpdateStart();this._sendRequest(this.featureLayer._resized&&b)},_getRequestId:function(b,a){return("_"+b.name+b.layerId+b._ulid+"_"+a.resolution+
"_"+(a.latticeID||a.row+"_"+a.col)).replace(/[^a-zA-Z0-9\_]+/g,"_")},_sendRequest:function(b){this._exceeds=!1;var a=this.featureLayer,c=this.map,b=b||c.extent,c=this._gridLayer.getCellsInExtent(b,a.latticeTiling).cells;if(!a.isEditable())var e=this._cellMap,c=o.filter(c,function(a){if(a.lattice){if(e[a.latticeID])return!1}else if(e[a.row]&&e[a.row][a.col])return!1;return!0});var d=a.getOutFields(),g=a.getDefinitionExpression(),f=a._getOffsettedTE(a._mapTimeExtent),h=a._usePatch,i=this._ioQueue,k,
m=this,j=this._drawFeatures,n,l,p;this._pending=this._pending||0;for(k=0;k<c.length;k++){n=c[k];l=new q;l.geometry=n.extent||n.lattice;l.outFields=d;l.where=g;if(a.latticeTiling&&n.extent)l.spatialRelationship=q.SPATIAL_REL_CONTAINS;l.returnGeometry=!0;l.timeExtent=f;l.maxAllowableOffset=a._maxOffset;if(a._ts)l._ts=(new Date).getTime();p=null;if(h&&(p=this._getRequestId(a,n),this._isPending(p)))continue;this._pending++;i.push(a._task.execute(l,function(){var a=n;return function(b){j.apply(m,[b,a])}}.call(this),
this._queryErrorHandler,p))}this._removeOldCells(b);this._endCheck()},_drawFeatures:function(b,a){this._exceeds=this._exceeds||b.exceededTransferLimit;this._finalizeIO();var c=this.map.extent,e=a.extent,d=a.row,g=a.col,f=this.featureLayer.objectIdField,h=b.features,i=this._gridLayer,k=this._cellMap,m=a.latticeID,j=m?k[m]:k[d]&&k[d][g];if(a.resolution!=i._resolution||(m?m!==i.getLatticeID(c):!i.intersects(e,c)))j&&this._removeCell(d,g,m);else if(j)this._updateCell(j,h);else{a.features=h;m?k[m]=a:(k[d]=
k[d]||{},k[d][g]=a);e=h.length;for(c=0;c<e;c++)d=h[c],g=d.attributes[f],this._addFeatureIIf(g,d),this._incRefCount(g)}this._endCheck()},_queryErrorHandler:function(b){this._finalizeIO();this.featureLayer._errorHandler(b);this._endCheck(!0)},_finalizeIO:function(){this._purgeRequests();this._pending--},_endCheck:function(b){if(0===this._pending){this._processIOQueue();var a=this.featureLayer,c=a._trackManager;c&&(c.clearTracks(),c.addFeatures(a.graphics),a._ager&&o.forEach(a.graphics,function(b){b._shape&&
a._repaint(b)}),c.moveLatestToFront(),c.drawTracks());this.featureLayer._fireUpdateEnd(b&&Error("FeatureLayer: an error occurred while updating the layer"),this._exceeds?{queryLimitExceeded:!0}:null);if(this._exceeds)a.onQueryLimitExceeded()}},_processIOQueue:function(b){this._ioQueue=o.filter(this._ioQueue,function(a){return-1<a.fired?!1:!0});b&&o.forEach(this._ioQueue,this._cancelPendingRequest)},_removeOldCells:function(b){var a=this._cellMap,c=this._gridLayer,e,d;for(e in a)if(a[e]){var g=a[e],
f=g.latticeID,h=0,i=0;if(f)h++,f!==c.getLatticeID(b)&&(this._removeCell(null,null,f),i++);else for(d in g)g[d]&&(h++,c.intersects(g[d].extent,b)||(this._removeCell(e,d),i++));i===h&&delete a[e]}},_updateCell:function(b,a){var c=this.featureLayer,e=c.objectIdField,c=c._selectedFeatures,d,g=a.length;b.features=b.features||[];for(d=0;d<g;d++){var f=a[d],h=f.attributes[e],i=this._addFeatureIIf(h,f);i===f?(this._incRefCount(h),b.features.push(i)):h in c||(i.setGeometry(f.geometry),i.setAttributes(f.attributes))}},
_removeCell:function(b,a,c){var e=this._cellMap,d=this.featureLayer,g=d.objectIdField,f=c?e[c]:e[b]&&e[b][a];if(f){c?delete e[c]:delete e[b][a];b=f.features;for(a=0;a<b.length;a++)c=b[a].attributes[g],this._decRefCount(c),c in d._selectedFeatures||this._removeFeatureIIf(c)}}})});