//>>built
define(["dojo/_base/declare","dojo/_base/connect","dojo/_base/lang","dojo/_base/array","dojo/_base/url","dojo/dom-construct","dojo/dom-class","dojo/dom-geometry","dojo/dom-style","dojox/collections/ArrayList","dojox/gfx/matrix","esri/kernel","esri/config","esri/sniff","esri/domUtils","esri/tileUtils","esri/geometry/Point","esri/geometry/Rect","esri/layers/layer"],function(N,k,y,v,C,o,G,H,j,I,J,q,O,s,K,z,L,A,P){var w=O.defaults.map.zoomDuration;return N(P,{declaredClass:"esri.layers.TiledMapServiceLayer",constructor:function(a,
c){k.connect(this,"onLoad",this,"_initTiledLayer");this._lowestLevel=(this._displayLevels=c?c.displayLevels:null)?this._displayLevels[0]:0;this._resampling=c?c.resampling:!1;this._resamplingTolerance=c?c.resamplingTolerance:null;var d=y.hitch;this._addImage=d(this,this._addImage);this._tileLoadHandler=d(this,this._tileLoadHandler);this._tileErrorHandler=d(this,this._tileErrorHandler);this._tilePopPop=d(this,this._tilePopPop);this._cleanUpRemovedImages=d(this,this._cleanUpRemovedImages);this._fireOnUpdateEvent=
d(this,this._fireOnUpdateEvent);this._transitionEnd=d(this,this._transitionEnd)},opacity:1,isPNG32:!1,_multiple:1,_initTiledLayer:function(){var a=this.tileInfo,c=a.lods;this._tileW=a.width;this._tileH=a.height;var d=this.scales=[],b=this._displayLevels,e="esri.layers.WMTSLayer"===this.declaredClass&&96!=a.dpi,f=-Infinity,g=Infinity,h=this.fullExtent,j=new L(h.xmin,h.ymax),h=new L(h.xmax,h.ymin),i=z.getContainingTileCoords,l,m,n,o=c.length;for(n=0;n<o;n++){m=c[n];if(e)m.scale=96*m.scale/a.dpi;l=i(a,
j,m);m.startTileRow=0>l.row?0:l.row;m.startTileCol=0>l.col?0:l.col;l=i(a,h,m);m.endTileRow=l.row;m.endTileCol=l.col;if(!b||-1!==v.indexOf(b,m.level))d[n]=m.scale,f=m.scale>f?m.scale:f,g=m.scale<g?m.scale:g}if(e)a.dpi=96;-Infinity!==f&&!this._hasMin&&this.setMinScale(f);Infinity!==g&&!this._hasMax&&this.setMaxScale(g);this._patchIE=6<=s("ie")&&7>s("ie")&&(this.isPNG32||"Mixed"===a.format)},_isMapAtVisibleScale:function(){var a=this.inherited(arguments);if(a){var c;c=this._map;var a=this.scales,d=c.getScale(),
b=!1,e=c.width>c.height?c.width:c.height;for(c=0;c<a.length;c++)if(Math.abs(a[c]-d)/a[c]<1/e){b=!0;break}a=b}return a},_setMap:function(a,c,d,b){this.inherited(arguments);this._map=a;var e=this._div=o.create("div",null,c),f=a.__visibleDelta,g=k.connect,h=q._css.names,r={position:"absolute",width:a.width+"px",height:a.height+"px",overflow:"visible"};"css-transforms"===a.navigationMode?(r[h.transform]=q._css.translate(-f.x,-f.y),j.set(e,r),delete r[h.transform],r[h.transition]=h.transformName+" "+w+
"ms ease",j.set(this._active=o.create("div",null,e),r),this._active._remove=0,this._passives=[]):(r.left=-f.x+"px",r.top=-f.y+"px",j.set(e,r));this._onResizeHandler_connect=g(a,"onResize",this,"_onResizeHandler");this._opacityChangeHandler_connect=g(this,"onOpacityChange",this,"_opacityChangeHandler");f=this.tileInfo;g=f.spatialReference;h=g._getInfo();(this._wrap=a.wrapAround180&&g._isWrappable()&&Math.abs(h.origin[0]-f.origin.x)<=h.dx)&&z._addFrameInfo(f,h);this.evaluateSuspension();if(this.suspended&&
!a.loaded)var i=k.connect(a,"onLoad",this,function(){k.disconnect(i);i=null;this.evaluateSuspension()});return e},_unsetMap:function(a,c){this.suspended||this._suspendImpl();o.destroy(this._div);this._map=this._div=null;var d=k.disconnect;d(this._onResizeHandler_connect);d(this._opacityChangeHandler_connect);this.inherited(arguments)},onSuspend:function(){this.inherited(arguments);this._suspendImpl()},_suspendImpl:function(){K.hide(this._div);clearTimeout(this._wakeTimer);this._wakeTimer=null;this._disableDrawConnectors();
var a=this._tiles,c=this._tileIds,d=this._loadingList,b,e,f=k.disconnect,g=o.destroy;d&&0<d.count&&(d.forEach(function(c){if(b=a[c])f(b._onload_connect),f(b._onerror_connect),f(b._onabort_connect),b._onload_connect=b._onerror_connect=b._onabort_connect=null}),d.clear(),this._fireUpdateEnd());this._removeList.clear();for(d=c.length-1;0<=d;d--)(b=(e=c[d])&&a[e])&&g(b);if("css-transforms"===this._map.navigationMode){c=this._active;e=this._passives;var h;this._noDom=0;for(d=e.length-1;0<=d;d--)h=e[d],
h._endHandle&&f(h._endHandle),h._matrix=h._multiply=h._endHandle=null,h._marked=h._remove=0,e.splice(d,1),g(h);c._matrix=c._multiply=null;c._marked=c._remove=0}this._tileIds=this._tiles=this._tileBounds=this._ct=this._loadingList=this._removeList=this._standby=null},onResume:function(){this.inherited(arguments);this._tileIds=[];this._tiles=[];this._tileBounds=[];this._ct=null;this._removeList=new I;this._loadingList=new I;K.show(this._div);this._enableDrawConnectors();this._wakeTimer=this._wakeTimer||
setTimeout(y.hitch(this,function(){this.suspended||this._onExtentChangeHandler(this._map.extent,null,!0,this._map.__LOD)}),0)},_enableDrawConnectors:function(){var a=this._map,c=k.connect;if("css-transforms"===a.navigationMode){if(this._onScaleHandler_connect=c(a,"onScale",this,this._onScaleHandler),s("esri-touch")||s("esri-pointer")){this._standby=[];var d=this,b=function(){d._noDom=1};this._onPanStartHandler_connect=c(a,"onPanStart",b);this._onZoomStartHandler_connect=c(a,"onZoomStart",b)}}else this._onZoomHandler_connect=
c(a,"onZoom",this,"_onZoomHandler");this._onPanHandler_connect=c(a,"onPan",this,"_onPanHandler");this._onExtentChangeHandler_connect=c(a,"onExtentChange",this,"_onExtentChangeHandler")},_disableDrawConnectors:function(){var a=k.disconnect;a(this._onPanHandler_connect);a(this._onZoomHandler_connect);a(this._onScaleHandler_connect);a(this._onExtentChangeHandler_connect);a(this._onPanStartHandler_connect);a(this._onZoomStartHandler_connect);this._onPanHandler_connect=this._onZoomHandler_connect=this._onScaleHandler_connect=
this._onExtentChangeHandler_connect=this._onPanStartHandler_connect=this._onZoomStartHandler_connect=null},_onResizeHandler:function(a,c,d){a={width:c+"px",height:d+"px"};c=j.set;c(this._div,a);if("css-transforms"===this._map.navigationMode){this._active&&c(this._active,a);for(d=this._passives.length-1;0<=d;d--)c(this._passives[d],a)}},_onExtentChangeHandler:function(a,c,d){var c=this._map,b,e=this._standby,f;clearTimeout(this._wakeTimer);this._wakeTimer=null;if(!c._isPanningOrZooming()){if("css-transforms"===
c.navigationMode){if(d)for(b=this._passives.length-1;0<=b;b--)if(f=this._passives[b],j.set(f,q._css.names.transition,"none"),f._marked)this._passives.splice(b,1),f.parentNode&&f.parentNode.removeChild(f),o.destroy(f);else if(0<f.childNodes.length)f._multiply=f._multiply?J.multiply(f._matrix,f._multiply):f._matrix;this._noDom=0;if(e&&e.length)for(b=e.length-1;0<=b;b--)f=e[b],j.set(f,"visibility","visible"),this._tilePopPop(f),e.splice(b,1)}this._fireUpdateStart();this._rrIndex=0;b=z.getCandidateTileInfo(c,
this.tileInfo,a);a=c.__visibleDelta;if(!this._ct||b.lod.level!==this._ct.lod.level||d){f=b&&this._ct&&b.lod.level!==this._ct.lod.level;this._ct=b;var g=this._tiles,h=this._tileIds,r=this._tileBounds,i=this._removeList,l,m=h.length;this._cleanUpRemovedImages();for(b=0;b<m;b++){e=h[b];l=g[e];r[e]=h[b]=null;if("css-transforms"===c.navigationMode&&f&&l.parentNode&&c.fadeOnZoom)l._fadeOut=f,l.parentNode._remove++;i.add(l)}if(d)this._tileIds=[],this._tiles=[],this._tileBounds=[]}b=a.x;d=a.y;"css-transforms"===
c.navigationMode?(e={},e[q._css.names.transform]=q._css.translate(b,d),j.set(this._div,e)):j.set(this._div,{left:b+"px",top:d+"px"});this.__coords_dx=b;this.__coords_dy=d;this._updateImages(new A(0,0,a.width,a.height));0===this._loadingList.count?(this.onUpdate(),this._fireUpdateEnd()):this._fireOnUpdate=!0;d=this._tileW;g=this._tileH;a=new A(-a.x,-a.y,a.width,a.height);for(b=this._tileIds.length-1;0<=b;b--)if(e=this._tileIds[b]){f=this._tiles[e];h=H.getMarginBox(f);h=new A(h.l,h.t,d,g);if("css-transforms"===
c.navigationMode)h.x=f._left,h.y=f._top;a.intersects(h)?this._tileBounds[e]=h:(this._loadingList.contains(e)&&this._tilePopPop(f),o.destroy(f),this._tileIds.splice(b,1),delete this._tileBounds[e],delete this._tiles[e])}else this._tileIds.splice(b,1),delete this._tileBounds[e],delete this._tiles[e]}},_onPanHandler:function(a,c){var d=this._map,b=d.__visibleDelta.offset(c.x,c.y);this.__coords_dx=this.__coords_dy=0;"css-transforms"===d.navigationMode?(d={},d[q._css.names.transform]=q._css.translate(b.x,
b.y),j.set(this._div,d),!s("esri-touch")&&!s("esri-pointer")&&this._updateImages({x:-b.x,y:-b.y,width:b.width,height:b.height})):(j.set(this._div,{left:b.x+"px",top:b.y+"px"}),this._updateImages({x:-b.x,y:-b.y,width:b.width,height:b.height}));if(0<this._loadingList.count)this._fireUpdateStart(),this._fireOnUpdate=!0},_onScaleHandler:function(a,c){var d,b={},e=q._css.names,f=this._map;for(d=this._passives.length-1;0<=d;d--){var g=this._passives[d];0===g.childNodes.length?(this._passives.splice(d,1),
o.destroy(g)):("none"===g.style[e.transition]&&j.set(g,e.transition,e.transformName+" "+w+"ms ease"),j.set(g,e.transition,c?"none":e.transformName+" "+w+"ms ease"),g._matrix=a,b[e.transform]=q._css.matrix(g._multiply?J.multiply(a,g._multiply):a),j.set(g,b))}if(!(this._active&&0===this._active.childNodes.length))j.set(this._active,e.transition,c?"none":e.transformName+" "+w+"ms ease"),this._active._matrix=a,b[e.transform]=q._css.matrix(this._active._matrix),j.set(this._active,b),this._passives.push(this._active),
b={position:"absolute",width:f.width+"px",height:f.height+"px",overflow:"visible"},b[e.transition]=e.transformName+" "+w+"ms ease",j.set(this._active=o.create("div",null,this._div),b),this._active._remove=0,f.fadeOnZoom&&o.place(this._active,this._div,"first")},_onZoomHandler:function(a,c,d){a=H.getMarginBox(this._div);d=d.offset(-a.l,-a.t);if(!this._previousScale||1===c)this._previousScale=1;var b,e=this._tileW*c,f=this._tileH*c,g=this._tileBounds,h=this._tiles,r=this._previousScale,i=this._multiple,
l=j.set,m,n;if((a=s("ie"))&&8>a)v.forEach(this._tileIds,function(a){n="";b=g[a];m=h[a].style.margin.split(" ");v.forEach(m,function(a){""!==n&&(n+=" ");a=parseFloat(a);n+=a/r*c+"px"});l(h[a],{left:b.x-(e-b.width)*(d.x-b.x)/b.width+"px",top:b.y-(f-b.height)*(d.y-b.y)/b.height+"px",margin:1!==i?n:"",zoom:c})});else{var o=e*i,q=f*i,M,k;v.forEach(this._tileIds,function(a){n="";b=g[a];M=b.x-(e-b.width)*(d.x-b.x)/b.width;k=b.y-(f-b.height)*(d.y-b.y)/b.height;m=h[a].style.margin.split(" ");v.forEach(m,function(a){""!==
n&&(n+=" ");a=parseFloat(a);n+=a/r*c+"px"});l(h[a],{left:M+"px",top:k+"px",margin:1!==i?n:"",width:o+"px",height:q+"px"})})}this._previousScale=c},_updateImages:function(a){if(this._ct){var c,d=this._tileW,b=this._tileH,e=this._ct;c=e.lod;var e=e.tile,f=e.offsets,g=e.coords,h=g.row,g=g.col,j=c.level,i=this.opacity,l=this._tileIds,m=this._loadingList,n=this._addImage,o=this._map.id,q=this.id,k=a.x,s=a.y,w=c.startTileRow,y=c.endTileRow,z=c.startTileCol,A=c.endTileCol,C=v.indexOf,u,p,E=f.x-this.__coords_dx,
B=f.y-this.__coords_dy;p=d-E+-a.x;var t=b-B+-a.y;u=Math.ceil;p=0<p?p%d:d-Math.abs(p)%d;var t=0<t?t%b:b-Math.abs(t)%b,k=0<k?Math.floor((k+E)/d):u((k-(d-E))/d),s=0<s?Math.floor((s+B)/b):u((s-(b-B))/b),B=k+u((a.width-p)/d),a=s+u((a.height-t)/b),x,D,F;if(this._wrap)x=c._frameInfo,D=x[0],F=x[1],x=x[2];for(t=k;t<=B;t++)for(k=s;k<=a;k++)u=h+k,p=g+t,this._wrap&&(p<F?(p%=D,p=p<F?p+D:p):p>x&&(p%=D)),u>=w&&u<=y&&p>=z&&p<=A&&(c=o+"_"+q+"_tile_"+j+"_"+k+"_"+t,-1===C(l,c)&&(m.add(c),l.push(c),n(j,k,u,t,p,c,d,b,
i,e,f)))}},_cleanUpRemovedImages:function(){var a=this._removeList,c=o.destroy,d,b=q._css.names;a.forEach(function(a){if(!a._fadeOut)a.style.filter="",a.style.zoom=1,c(a)});if("css-transforms"===this._map.navigationMode)for(d=this._passives.length-1;0<=d;d--){var e=this._passives[d];if(0===e.childNodes.length)this._passives.splice(d,1),c(e);else if(this._map.fadeOnZoom&&!e._marked&&e._remove===e.childNodes.length)j.set(e,b.transition,"opacity 0.65s"),j.set(e,"opacity",0),e._marked=1,10<=s("ie")?e.addEventListener(b.endEvent,
this._transitionEnd,!1):e._endHandle=k.connect(e,b.endEvent,this._transitionEnd)}a.clear()},_transitionEnd:function(a){var c=a.target;if("opacity"===a.propertyName)10<=s("ie")?c.removeEventListener(q._css.names.endEvent,this._transitionEnd,!1):(k.disconnect(c._endHandle),c._endHandle=null),a=v.indexOf(this._passives,c),-1<a&&this._passives.splice(a,1),c.parentNode&&c.parentNode.removeChild(c),o.destroy(c)},_addImage:function(a,c,d,b,e,f,g,h,r,i,l){if(this._patchIE)i=this._tiles[f]=o.create("div"),
i.id=f,G.add(i,"layerTile"),j.set(i,{left:g*b-l.x+"px",top:h*c-l.y+"px",width:g+"px",height:h+"px",filter:"progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+this.getTileUrl(a,d,e)+"', sizingMethod='scale')"}),1>r&&j.set(i,"opacity",r),a=i.appendChild(o.create("div")),j.set(a,{opacity:0,width:g+"px",height:h+"px"}),this._div.appendChild(i),this._loadingList.remove(f),this._fireOnUpdateEvent();else{var i=this._tiles[f]=o.create("img"),m=k.connect;i.id=f;G.add(i,"layerTile");f=g*b-l.x;l=h*c-
l.y;c=this._map;b=q._css.names;g={width:g+"px",height:h+"px",visibility:"hidden"};"css-transforms"===c.navigationMode?(g[b.transform]=q._css.translate(f,l),j.set(i,g),i._left=f,i._top=l):(g.left=f+"px",g.top=l+"px",j.set(i,g));1>r&&j.set(i,"opacity",r);i._onload_connect=m(i,"onload",this,"_tileLoadHandler");i._onerror_connect=m(i,"onerror",y.hitch(this,"_tileErrorHandler",d,e));i._onabort_connect=m(i,"onabort",this,"_tileAbortHandler");if(a=this.getTileUrl(a,d,e,i))this._failedRequests&&this._failedRequests[a]?
(j.set(i,this._failedRequests[a].css),i.src=this._failedRequests[a].src,this._multiple=parseInt(this._failedRequests[a].css.width)/this._tileW):(this._multiple=1,i.src=a);"css-transforms"===c.navigationMode?this._active.appendChild(i):this._div.appendChild(i)}},getTileUrl:function(){},refresh:function(){this.suspended||this._onExtentChangeHandler(this._map.extent,null,!0,this._map.__LOD)},_tilePopPop:function(a){var c=k.disconnect;c(a._onload_connect);c(a._onerror_connect);c(a._onabort_connect);a._onload_connect=
a._onerror_connect=a._onabort_connect=null;this._loadingList.remove(a.id);this._fireOnUpdateEvent()},_tileLoadHandler:function(a){a=a.currentTarget;this._noDom?this._standby.push(a):(j.set(a,"visibility","visible"),this._tilePopPop(a))},_tileAbortHandler:function(a){a=a.currentTarget;this.onError(Error("Unable to load tile: "+a.src));j.set(a,"visibility","hidden");this._tilePopPop(a)},_tileErrorHandler:function(a,c,d){var d=d.currentTarget,b=(new C(d.src)).path.split("/"),b=parseInt(b[b.length-3]);
this._multiple=Math.pow(2,this._ct.lod.level-b+1);!this._resampling||b===this._lowestLevel||0===this._resamplingTolerance||this._resamplingTolerance&&Math.log(this._multiple)/Math.LN2>this._resamplingTolerance?(this.onError(Error("Unable to load tile: "+d.src)),j.set(d,"visibility","hidden"),this._tilePopPop(d)):this._resample(d,a,c)},_resample:function(a,c,d){var b=(new C(a.src)).path.split("/"),e=this._multiple,f=parseInt(b[b.length-3])-1,g=parseInt(c/e),h=parseInt(d/e),b=d%e,k=c%e,g=this.getTileUrl(f,
g,h),c=this.getTileUrl(f+Math.log(e)/Math.LN2,c,d),e={width:this._tileW*e+"px",height:this._tileH*e+"px",border:"4px",margin:"-"+this._tileW*k+"px 0 0 "+("-"+this._tileH*b+"px")};if(!this._failedRequests)this._failedRequests={};this._failedRequests[c]={src:g,css:e};j.set(a,e);a.src=g},_fireOnUpdateEvent:function(){if(0===this._loadingList.count&&(this._cleanUpRemovedImages(),this._fireOnUpdate))this._fireOnUpdate=!1,this.onUpdate(),this._fireUpdateEnd()},setOpacity:function(a){if(this.opacity!=a)this.onOpacityChange(this.opacity=
a)},onOpacityChange:function(){},_opacityChangeHandler:function(a){var c=j.set,d,b,e;if("css-transforms"===this._map.navigationMode){if(this._active){e=this._active.childNodes;for(d=e.length-1;0<=d;d--)c(e[d],"opacity",a)}for(d=this._passives.length-1;0<=d;d--){e=this._passives[d].childNodes;for(b=e.length-1;0<=b;b--)c(e[b],"opacity",a)}}else{e=this._div.childNodes;for(d=e.length-1;0<=d;d--)c(e[d],"opacity",a)}}})});