//>>built
require({cache:{"url:esri/dijit/editing/templates/AttachmentEditor.html":"<div class=\"attachmentEditor\">\r\n    <br />\r\n    <div>\r\n        <b>${NLS_attachments}</b>\r\n        <hr />\r\n        <div dojoAttachPoint=\"_attachmentError\" style='color:red;display:none'></div>\r\n        <br />\r\n        <span dojoAttachPoint='_attachmentList' style='word-wrap: break-word;'></span>\r\n        <br><br>\r\n        <form dojoAttachPoint='_uploadForm'> ${NLS_add}:&nbsp;&nbsp;<input type='file' name='attachment' dojoAttachPoint='_uploadField' /> </form>\r\n    </div>\r\n</div>"}});
define(["require","dojo/_base/declare","dojo/_base/lang","dojo/_base/connect","dojo/_base/array","dojo/_base/kernel","dojo/has","dojo/query","dojo/io-query","dojo/dom-attr","dijit/_Widget","dijit/_Templated","esri/kernel","esri/lang","esri/domUtils","dojo/text!esri/dijit/editing/templates/AttachmentEditor.html","dojo/i18n!esri/nls/jsapi","dojo/NodeList-dom"],function(j,k,c,d,g,i,r,s,l,m,n,o,t,h,e,p,q){return k([n,o],{declaredClass:"esri.dijit.editing.AttachmentEditor",widgetsInTemplate:!0,templateString:p,basePath:j.toUrl("esri/dijit/editing")+
"/",_listHtml:"<span id='node_${oid}_${attid}'><a href='${href}' target='_blank'>${name}</a>",_deleteBtnHtml:"(<span style='cursor:pointer;color:red;font-weight:bold;' class='deleteAttachment' id='${attid}');'>X</span>)",_endHtml:"<br/></span>",_aeConnects:[],_layerEditingCapChecked:{},_layerEditingCap:{},constructor:function(){c.mixin(this,q.widgets.attachmentEditor)},startup:function(){this.inherited(arguments);this._uploadField_connect=d.connect(this._uploadField,"onchange",this,"_addAttachment");
this._uploadFieldFocus_connect=d.connect(this._uploadField,"onfocus",c.hitch(this,function(){e.hide(this._attachmentError)}))},destroy:function(){g.forEach(this._aeConnects,d.disconnect);d.disconnect(this._uploadField_connect);d.disconnect(this._uploadFieldFocus_connect);this.inherited(arguments)},showAttachments:function(a,b){this._attachmentList.innerHTML=this.NLS_none;this._uploadField.value="";g.forEach(this.domNode.children,function(a){e.show(a)});e.hide(this._attachmentError);if(a&&(this._featureLayer=
a.getLayer()||b))"esri.layers.FeatureLayer"!==this._featureLayer.declaredClass||!this._featureLayer.getEditCapabilities?(e.hide(this._uploadForm),g.forEach(this.domNode.children,function(a){e.hide(a)})):(this._currentLayerId=this._featureLayer.id,this._layerEditingCapChecked[this._currentLayerId]||(this._layerEditingCap[this._currentLayerId]=this._featureLayer.getEditCapabilities(),this._layerEditingCapChecked[this._currentLayerId]=!0),this._featureCanUpdate=this._featureLayer.getEditCapabilities({feature:a}).canUpdate,
this._oid=a.attributes[this._featureLayer.objectIdField],this._getAttachments(a))},_getAttachments:function(){this._featureLayer&&this._featureLayer.queryAttachmentInfos&&this._featureLayer.queryAttachmentInfos(this._oid,c.hitch(this,"_onQueryAttachmentInfosComplete"))},_addAttachment:function(){e.hide(this._attachmentError);this._featureLayer&&this._featureLayer.addAttachment&&this._featureLayer.addAttachment(this._oid,this._uploadForm,c.hitch(this,"_onAddAttachmentComplete"),c.hitch(this,"_onAddAttachmentError"))},
_deleteAttachment:function(a,b){this._featureLayer.deleteAttachments(a,[b],c.hitch(this,"_onDeleteAttachmentComplete"))},_onQueryAttachmentInfosComplete:function(a){var b=this._listHtml+this._deleteBtnHtml+this._endHtml;this._uploadForm.style.display="block";!this._featureCanUpdate&&this._layerEditingCap[this._currentLayerId].canUpdate||!this._layerEditingCap[this._currentLayerId].canCreate&&!this._layerEditingCap[this._currentLayerId].canUpdate?(b=this._listHtml+this._endHtml,this._uploadForm.style.display=
"none"):this._layerEditingCap[this._currentLayerId].canCreate&&!this._layerEditingCap[this._currentLayerId].canUpdate&&(b=this._listHtml+this._endHtml);var f=this._attachmentList,a=g.map(a,c.hitch(this,function(a){return h.substitute({href:a.url,name:a.name,oid:a.objectId,attid:a.id},b)}));f.innerHTML=a.join("")||this.NLS_none;this._updateConnects()},_onAddAttachmentComplete:function(a){var b=this._uploadField,f=b.value,c=f.lastIndexOf("\\");-1<c&&(f=f.substring(c+1,f.length));var f=f.replace(/\ /g,
"_"),c=this._attachmentList,d=l.objectToQuery({gdbVersion:this._featureLayer.gdbVersion,token:this._featureLayer._getToken()}),e=this._listHtml+this._deleteBtnHtml+this._endHtml;this._layerEditingCap[this._currentLayerId].canCreate&&!this._layerEditingCap[this._currentLayerId].canUpdate&&(e=this._listHtml+this._endHtml);a=h.substitute({href:this._featureLayer._url.path+"/"+a.objectId+"/attachments/"+a.attachmentId+(d?"?"+d:""),name:f,oid:a.objectId,attid:a.attachmentId},e);c.innerHTML=c.innerHTML==
this.NLS_none?a:c.innerHTML+a;this._updateConnects();b.value=""},_onAddAttachmentError:function(a){if(a&&h.isDefined(a.code)){var b=this._attachmentError;m.set(b,"innerHTML",(400===a.code?this.NLS_fileNotSupported:a.message||a.details&&a.details.length&&a.details[0])||this.NLS_error);e.show(b)}},_onDeleteAttachmentComplete:function(a){var b=this._attachmentList;if(g.every(a,function(a){return a.success})&&(i.query("#node_"+a[0].objectId+"_"+a[0].attachmentId).orphan(),!b.children||!b.children.length))b.innerHTML=
this.NLS_none},_updateConnects:function(){g.forEach(this._aeConnects,d.disconnect);i.query(".deleteAttachment").forEach(function(a){this._aeConnects.push(d.connect(a,"onclick",c.hitch(this,"_deleteAttachment",this._oid,a.id)))},this)}})});