//>>built
require({cache:{"url:esri/dijit/editing/templates/TemplatePicker.html":'<div class="templatePicker">\r\n\r\n  <table dojoType="dojox.grid.DataGrid" noDataMessage="${emptyMessage}" selectionMode="none" autoHeight="${_rows}" autoWidth="${_autoWidth}"\r\n         query="{ query: \'*\' }" dojoAttachPoint="grid" class="grid">\r\n  </table>\r\n  \r\n</div>'}});
define(["require","dojo/_base/declare","dojo/_base/lang","dojo/_base/connect","dojo/_base/html","dojo/_base/array","dojo/_base/json","dojo/_base/kernel","dojo/has","dojo/query","dojo/sniff","dojo/dom-class","dojo/dom-construct","dojo/dom-geometry","dojo/dom-style","dijit/_Widget","dijit/_Templated","dojo/data/ItemFileReadStore","dojox/grid/DataGrid","dojox/gfx","esri/layers/FeatureLayer","esri/symbols/PictureMarkerSymbol","esri/dijit/editing/TemplatePickerItem","esri/kernel","esri/lang","esri/request","esri/dijit/_EventedWidget","dojo/i18n!esri/nls/jsapi","dojo/text!esri/dijit/editing/templates/TemplatePicker.html"],function(z,
A,j,i,r,h,s,t,u,L,M,v,w,o,p,B,C,D,E,N,F,x,G,O,q,H,I,J,K){var y=A([I,B,C],{declaredClass:"esri.dijit.editing.TemplatePicker",widgetsInTemplate:!0,templateString:K,basePath:z.toUrl("esri/dijit/editing")+"/",featureLayers:null,items:null,grouping:!0,showTooltip:!1,maxLabelLength:0,rows:4,_rows:0,columns:3,surfaceWidth:30,surfaceHeight:30,emptyMessage:"",useLegend:!0,legendCache:{},_uniqueId:{id:0},_assumedCellWidth:90,_initialAutoWidth:300,_initialAutoHeight:200,_ieTimer:150,constructor:function(a){a=
a||{};!a.items&&!a.featureLayers&&console.error("TemplatePicker: please provide 'featureLayers' or 'items' parameter in the constructor");this._dojo14x=4<=t.version.minor;this._itemWidgets={};if(a.featureLayers&&a.featureLayers.length)this._flChanged=1;this._nls=J.widgets.templatePicker;this.emptyMessage=a.emptyMessage||this._nls&&this._nls.creationDisabled||""},postMixInProperties:function(){this.inherited(arguments);this._preprocess()},startup:function(){this.inherited(arguments);if("auto"===this.rows&&
"auto"===this.columns){var a=o.getContentBox(this.domNode);if(!a.w)this.domNode.style.width=this._initialAutoWidth+"px";if(!a.h)this.domNode.style.height=this._initialAutoHeight+"px";a=o.getContentBox(this.domNode);this._columns=Math.floor(a.w/this._assumedCellWidth)||1}this._applyGridPatches();this._setGridLayout();i.connect(this.grid,"onRowClick",this,this._rowClicked);this._setGridData();this._toggleTooltip();if(9>u("ie"))this._repaintItems=j.hitch(this,this._repaintItems),setTimeout(this._repaintItems,
this._ieTimer)},destroy:function(){this.showTooltip=!1;this._toggleTooltip();this._clearLegendInfo();this.featureLayers=this.items=this.grid=this._flItems=this._itItems=this._groupRowIndices=this._selectedCell=this._selectedInfo=this._selectedItem=null;this.inherited(arguments)},getSelected:function(){return this._selectedCell?this._selectedItem:null},clearSelection:function(){var a=this._selectedCell,b=this._selectedInfo;a&&this._rowClicked({cellNode:a,rowIndex:b.selRow,cellIndex:b.selCol})},update:function(a){var k;
var a="auto"===this.rows&&"auto"===this.columns&&a?!0:!1,b=this.grid,d;if(a){d=this.domNode;var c;c=t.query("#"+d.id+".templatePicker div.item")[0];d=o.getContentBox(d);k=(c=c&&c.parentNode)?r.coords(c).w:this._assumedCellWidth,c=k;this._columns=(this._columns=Math.floor((d.w-b.views.views[0].getScrollbarWidth())/c))||1}c=this._rows;this._preprocess();var e=this._rows;this._setGridLayout();this._setGridData();e!==c&&b.set("autoHeight",this._rows,!1);a?(b._resize({w:d.w,h:d.h}),b.viewsHeaderNode.style.display=
"none"):b.update();this._toggleTooltip();var g=this,f=this.getSelected();f&&b.store.fetch({onComplete:function(a){var d=(a=g._locate(f,g._selectedInfo,a))&&b.views.views[0].getCellNode(a[0],a[1]);d&&g._rowClicked({cellNode:d,rowIndex:a[0],cellIndex:a[1]},!0)}});9>u("ie")&&setTimeout(this._repaintItems,this._ieTimer);a=this.featureLayers;d=this.items;(!a||!a.length)&&(!d||!d.length)&&b&&this.emptyMessage&&b.showMessage(this.emptyMessage)},_eventMap:{"selection-change":!0},onSelectionChange:function(){},
_setUseLegendAttr:function(a){var b=this.useLegend;if(!this._started||b!==a)a?this._flChanged=1:this._clearLegendInfo();this.useLegend=a},_setFeatureLayersAttr:function(a){var b=this.featureLayers;if(!this._started||b!==a)this._flChanged=1;this.featureLayers=a},_adjustRowsCols:function(a){if("auto"===this.rows&&"auto"===this.columns){if(!this._started)this._rows=!1,this._columns=null,this._autoWidth=!1}else{var b=0;this._rows=this.rows;this._columns=this.columns;if("auto"===this.rows)this.featureLayers?
this.grouping?(b=a.length,h.forEach(a,function(a){b+=Math.ceil(a.length/this.columns)},this)):(h.forEach(a,function(a){b+=a.length},this),b=Math.ceil(b/this.columns)):b=Math.ceil(a.length/this.columns),this._rows=b;else if("auto"===this.columns)this.featureLayers?this.grouping?b=3:(h.forEach(a,function(a){b+=a.length},this),b=Math.ceil(b/this.rows)):b=Math.ceil(a.length/this.rows),this._columns=b}},_preprocess:function(){if(this.items)this.grouping=!1;this._autoWidth=!1;if("auto"===this.rows||"auto"===
this.columns)this._autoWidth=!0;var a;if(this.featureLayers){if(this.useLegend&&this._flChanged)this._legendIndices=[],this._loadingIndices=[],this._legendSymbols={},this._ignoreLegends(),this._loadingLegends=[],clearTimeout(this._legendTimer),this._legendTimer=null,this._processSelectionLayers(),this._flChanged=0;if(h.every(this.featureLayers,function(a){return a.loaded}))a=this._flItems=this._getItemsFromLayers(this.featureLayers),this._adjustRowsCols(a);else{var b=this.featureLayers.length,d=[];
h.forEach(this.featureLayers,function(c){if(c.loaded)b--,d.push(c);else var e=i.connect(c,"onLoad",this,function(c){i.disconnect(e);e=null;b--;d.push(c);if(!b)a=this._flItems=this._getItemsFromLayers(d),this._adjustRowsCols(a),this.update()})},this)}}else a=this._itItems=this._getItemsFromItems(this.items),this._adjustRowsCols(a)},_processSelectionLayers:function(){var a,b,d,c,e,g,f,l={};h.forEach(this.featureLayers,function(e,f){if(e.mode===F.MODE_SELECTION&&e._map&&e.url&&e._params.drawMode&&!e.source)b=
j.trim(e._url.path).replace(/\/(MapServer|FeatureServer).*/ig,"/MapServer").replace(/^https?:\/\//ig,"").toLowerCase(),d=l[b]=l[b]||{},c=d.featureLayers=d.featureLayers||{},g=d.indices=d.indices||[],c[f]=e,g.push(f),a=e._map});a&&h.forEach(a.layerIds,function(c){if((c=a.getLayer(c))&&c.url&&(c.getImageUrl||c.getTileUrl)&&c.loaded&&10.1<=c.version)if(b=j.trim(c._url.path).replace(/(\/MapServer).*/ig,"$1"),e=b.replace(/^https?:\/\//ig,"").toLowerCase(),l[e]&&!l[e].mapServiceUrl)d=l[e],d.mapServiceUrl=
b,d.mapServiceLayer=c,this._legendIndices=this._legendIndices.concat(d.indices),f=this._fetchLegend({pickerInstance:this,info:d},e),f.then?(this._loadingIndices=this._loadingIndices.concat(d.indices),this._loadingLegends.push(f)):this._processLegendResponse(f,d)},this)},_fetchLegend:function(a,b){var d=y.prototype,c=d.legendCache[b];c?c.then&&c._contexts.push(a):(c=d.legendCache[b]=H({url:a.info.mapServiceUrl+"/legend",content:{f:"json"},callbackParamName:"callback"}),c._contexts=[a],c.addBoth(function(a){if(!c.canceled){d.legendCache[b]=
a;var g=c._contexts;c._contexts=null;h.forEach(g,function(b){var d=b.pickerInstance,b=b.info,g;d._destroyed||(h.forEach(b.indices,function(a){g=h.indexOf(d._loadingIndices,a);-1<g&&d._loadingIndices.splice(g,1)}),g=h.indexOf(d._loadingLegends,c),-1<g&&d._loadingLegends.splice(g,1),d._processLegendResponse(a,b))})}}));return c},_clearLegendInfo:function(){clearTimeout(this._legendTimer);this._ignoreLegends();this._legendIndices=this._loadingIndices=this._legendSymbols=this._loadingLegends=this._legendTimer=
null},_ignoreLegends:function(){this._loadingLegends&&h.forEach(this._loadingLegends,function(a){var b=-1;h.some(a._contexts,function(a,c){a.pickerInstance===this&&(b=c);return-1<b},this);-1<b&&a._contexts.splice(b,1)},this)},_processLegendResponse:function(a,b){if(a&&!(a instanceof Error))h.forEach(b.indices,function(c){var d=b.featureLayers[c].layerId,f,l=b.mapServiceUrl+"/"+d+"/images/",m=b.mapServiceLayer._getToken(),n,k,i,j;this._legendSymbols[c]||(n=null,h.some(a.layers,function(a){a.layerId==
d&&(n=a);return!!n}),n&&(k=this._legendSymbols[c]={},h.forEach(n.legend,function(a){if((i=a.values)&&i.length)for(f=0;f<i.length;f++)k[i[f]]=a;else k.defaultSymbol=a;if((j=a.url)&&!a._fixed){a._fixed=1;if(-1===j.search(/https?\:/))a.url=l+j;m&&-1!==a.url.search(/https?\:/)&&(a.url+=(-1<a.url.indexOf("?")?"&":"?")+"token="+m)}})))},this);else{var d;h.forEach(b.indices,function(a){d=h.indexOf(this._legendIndices,a);-1<d&&this._legendIndices.splice(d,1)},this)}var c=this;if(c._started&&!c._legendTimer)c._legendTimer=
setTimeout(function(){clearTimeout(c._legendTimer);c._legendTimer=null;c._destroyed||c.update()},0)},_applyGridPatches:function(){var a=this.grid,b=a.adaptWidth,d,c,e;a.adaptWidth=function(){d=this.views.views;for(c=0;e=d[c];c++)p.set(e.headerNode,"display","block");b.apply(this,arguments);for(c=0;e=d[c];c++)p.set(e.headerNode,"display","none")};if(this._dojo14x){if("auto"!==this.rows&&"auto"!==this.columns)var g=i.connect(a,"_onFetchComplete",this,function(){i.disconnect(g);this.grid.set("autoHeight",
this._rows)});i.connect(a,"_onDelete",this,this._destroyItems);i.connect(a,"_clearData",this,this._destroyItems);i.connect(a,"destroy",this,this._destroyItems);if((a=a.focus)&&a.findAndFocusGridCell)a.findAndFocusGridCell=function(){return!1}}},_setGridLayout:function(){var a=function(a){return function(b,c){return this._cellGet(a,b,c)}},b=j.hitch(this,this._cellFormatter),d=[],c=this._columns,e;for(e=0;e<c;e++)d.push({field:"cell"+e,get:j.hitch(this,a(e)),formatter:b});a={cells:[d]};this.grouping&&
(c={field:"groupName",colSpan:c,get:j.hitch(this,this._cellGetGroup),formatter:j.hitch(this,this._cellGroupFormatter)},a.cells.push([c]));c=this.grid;b=E.prototype.rowsPerPage;c.set("rowsPerPage",this._rows>b?this._rows:b);c.set("structure",a)},_setGridData:function(){var a=[];if(this.grouping){this._groupRowIndices=[];var b,d,c=this._columns;h.forEach(this._flItems,function(e,g){a.push({});var f=0===g?0:b+d+1;this._groupRowIndices.push(f);b=f;d=Math.ceil(e.length/c);a=a.concat(this._getStoreItems(e))},
this)}else this.featureLayers?(h.forEach(this._flItems,function(b){a=a.concat(b)}),a=this._getStoreItems(a)):a=this._getStoreItems(this._itItems);this.grid.setStore(new D({data:{items:a}}))},_toggleTooltip:function(){if(this.showTooltip){if(!this.tooltip){this.tooltip=w.create("div",{"class":"tooltip"},this.domNode);this.tooltip.style.display="none";this.tooltip.style.position="fixed";var a=this.grid;this._mouseOverConnect=i.connect(a,"onCellMouseOver",this,this._cellMouseOver);this._mouseOutConnect=
i.connect(a,"onCellMouseOut",this,this._cellMouseOut)}}else if(this.tooltip)i.disconnect(this._mouseOverConnect),i.disconnect(this._mouseOutConnect),w.destroy(this.tooltip),this.tooltip=null},_rowClicked:function(a,b){var d=a.cellNode,c=a.rowIndex,e=a.cellIndex,g=this._getCellInfo(d,c,e);if(g){var f=this.grid.store;if(!f.getValue(g,"loadingCell")&&(this._selectedCell&&v.remove(this._selectedCell,"selectedItem"),d!==this._selectedCell?(v.add(d,"selectedItem"),this._selectedCell=d,this._selectedItem=
{featureLayer:f.getValue(g,"layer"),type:f.getValue(g,"type"),template:f.getValue(g,"template"),symbolInfo:f.getValue(g,"symbolInfo"),item:this._getItem(g)},this._selectedInfo={selRow:c,selCol:e,index1:f.getValue(g,"index1"),index2:f.getValue(g,"index2"),index:f.getValue(g,"index")}):this._selectedCell=this._selectedInfo=this._selectedItem=null,!b))this.onSelectionChange()}},_locate:function(a,b,d){var c=this.grid.store,e=Array(this._columns),g,f=b.index1,l=b.index2,m=b.index,i=a.item;h.some(d,function(a,
b){return h.some(e,function(d,e){var h=c.getValue(a,"cell"+e);return h&&(i?m===c.getValue(h,"index"):f===c.getValue(h,"index1")&&l===c.getValue(h,"index2"))?(g=[b,e],!0):!1})});return g},_getCellInfo:function(a,b,d){if(a)return a=this.grid,b=a.getItem(b),a.store.getValue(b,"cell"+d)},_getItem:function(a){var b=this.items;if(b)return b[this.grid.store.getValue(a,"index")]},_cellMouseOver:function(a){var b=this.tooltip,d=a.cellNode,c=this._getCellInfo(d,a.rowIndex,a.cellIndex);if(b&&c){var e=this.grid.store,
a=e.getValue(c,"template"),g=e.getValue(c,"type"),f=e.getValue(c,"symbolInfo"),e=e.getValue(c,"layer"),a=(c=this._getItem(c))&&c.label+(c.description?": "+c.description:"")||a&&a.name+(a.description?": "+a.description:"")||g&&g.name||f&&f.label+(f.description?": "+f.description:"")||(e&&e.name+": ")+"Default";b.style.display="none";b.innerHTML=a;d=r.coords(d.firstChild);p.set(b,{left:d.x+"px",top:d.y+d.h+5+"px"});b.style.display=""}},_cellMouseOut:function(){var a=this.tooltip;if(a)a.style.display=
"none"},_destroyItems:function(){var a=this._itemWidgets,b;for(b in a)a[b]&&(a[b].destroy(),delete a[b])},_repaintItems:function(){var a=this._itemWidgets,b;for(b in a){var d=a[b];d&&d._repaint(d._surface)}},_getStoreItems:function(a){for(var b=this._uniqueId,a=h.map(a,function(a){return j.mixin({surfaceId:"tpick-surface-"+b.id++},a)}),d=a.length,c=0,e={},g=0,f,l=[],m=!0,i=this._columns;c<d;)m=!0,f="cell"+g,e[f]=a[c],c++,g++,0===g%i&&(m=!1,l.push(e),e={},g=0);m&&d&&l.push(e);return l},_getItemsFromLayers:function(a){var b=
[];h.forEach(a,function(a,c){b.push(this._getItemsFromLayer(a,c))},this);return b},_getItemsFromLayer:function(a,b){var d=[];if(this.useLegend&&-1<h.indexOf(this._loadingIndices,b))return[{label:this._nls&&this._nls.loading||"",symbol:null,layer:a,type:null,template:null,index1:b,index2:0,loadingCell:1}];var c=[],c=c.concat(a.templates);h.forEach(a.types,function(a){var b=a.templates;h.forEach(b,function(b){b._type_=a});c=c.concat(b)});var c=h.filter(c,q.isDefined),e=a.renderer;if(e){var g=e.declaredClass.replace("esri.renderer.",
"");if(0<c.length)h.forEach(c,function(c){var f=c.prototype;if(f){var i=e.getSymbol(f);if(i){var k=null,j;if(this.useLegend&&-1<h.indexOf(this._legendIndices,b)){if(j=this._legendSymbols&&this._legendSymbols[b])switch(g){case "SimpleRenderer":k=j.defaultSymbol;break;case "UniqueValueRenderer":h.some(e.infos,function(a){a.symbol===i&&(k=j[a.value]);return!!k});break;case "ClassBreaksRenderer":h.some(e.infos,function(a){a.symbol===i&&(k=j[a.maxValue]);return!!k})}if(k){f=s.fromJson(s.toJson(x.defaultProps));
f.url=k.url;f.imageData=k.imageData;f.contentType=k.contentType;f.width=k.width;f.height=k.height;if(!q.isDefined(f.width)||!q.isDefined(f.height))f.width=15,f.height=15;k=new x(f)}}d.push({label:this._trimLabel(c.name),symbol:k||i,legendOverride:!!k,layer:a,type:c._type_,template:c,index1:b,index2:d.length})}}delete c._type_},this);else{var f=[];if("TemporalRenderer"===g)(e=e.observationRenderer)&&(g=e.declaredClass.replace("esri.renderer.",""));switch(g){case "SimpleRenderer":f=[{symbol:e.symbol,
label:e.label,description:e.description}];break;case "UniqueValueRenderer":case "ClassBreaksRenderer":f=e.infos}d=h.map(f,function(c,d){return{label:this._trimLabel(c.label),description:c.description,symbolInfo:j.mixin({constructor:function(){}},c),symbol:c.symbol,layer:a,index1:b,index2:d}},this)}}return d},_getItemsFromItems:function(a){return h.map(a,function(a,d){a=j.mixin({index:d},a);a.label=this._trimLabel(a.label);return a},this)},_trimLabel:function(a){var b=this.maxLabelLength;b&&a&&a.length>
b&&(a=a.substr(0,b)+"...");return a||""},_cellGet:function(a,b,d){return!d?"":this.grid.store.getValue(d,"cell"+a)},_cellFormatter:function(a){if(a){var b=this._itemWidgets,d=this.grid.store,c=d.getValue(a,"surfaceId"),e=b[c];e||(e=b[c]=new G({id:c,label:d.getValue(a,"label"),symbol:d.getValue(a,"symbol"),legendOverride:d.getValue(a,"legendOverride"),surfaceWidth:this.surfaceWidth,surfaceHeight:this.surfaceHeight,template:d.getValue(a,"template")}));return e||""}return""},_cellGetGroup:function(a,
b){if(!this._groupRowIndices)return"";var d=h.indexOf(this._groupRowIndices,a);return!b||-1===d?"":this.featureLayers[d]&&this.featureLayers[d].name||""},_cellGroupFormatter:function(a){return a?"<div class='groupLabel'>"+a+"</div>":""}});return y});