//>>built
define(["dojo/_base/array","dojo/_base/lang","dojo/_base/Deferred","dojo/has","esri/kernel","esri/config","esri/deferredUtils","esri/geometry/Polyline","esri/geometry/Polygon","esri/geometry/webMercatorUtils","esri/geometry/jsonUtils"],function(h,k,B,J,K,H,v,s,x,w,I){function t(a,f){return Math.ceil((a-f)/(2*f))}function y(a,f){var c=a.paths||a.rings,b,e,d=c.length,l;for(b=0;b<d;b++){l=c[b].length;for(e=0;e<l;e++){var m=a.getPoint(b,e);a.setPoint(b,e,m.offset(f,0))}}return a}function C(a,f){if(!(a instanceof
s||a instanceof x))throw console.error("_straightLineDensify: the input geometry is neither polyline nor polygon"),Error("_straightLineDensify: the input geometry is neither polyline nor polygon");var c=a instanceof s,b=[],e;h.forEach(c?a.paths:a.rings,function(a){b.push(e=[]);e.push([a[0][0],a[0][1]]);var l,c,n,j,i,g,h,u,k,o,p,q;for(i=0;i<a.length-1;i++){l=a[i][0];c=a[i][1];n=a[i+1][0];j=a[i+1][1];h=Math.sqrt((n-l)*(n-l)+(j-c)*(j-c));u=(j-c)/h;k=(n-l)/h;o=h/f;if(1<o){for(g=1;g<=o-1;g++)q=g*f,p=k*
q+l,q=u*q+c,e.push([p,q]);g=(h+Math.floor(o-1)*f)/2;p=k*g+l;q=u*g+c;e.push([p,q])}e.push([n,j])}});return c?new s({paths:b,spatialReference:a.spatialReference}):new x({rings:b,spatialReference:a.spatialReference})}function z(a,f,c){f&&(a=C(a,1E6),a=w.webMercatorToGeographic(a,!0));c&&(a=y(a,c));return a}function A(a,f,c){var b=a.x||a[0],e;b>f?(e=t(b,f),a.x?a=a.offset(e*-2*f,0):a[0]=b+e*-2*f):b<c&&(e=t(b,c),a.x?a=a.offset(e*-2*c,0):a[0]=b+e*-2*c);return a}function D(a,f){var c=-1;h.forEach(f.cutIndexes,
function(b,e){var d=f.geometries[e];h.forEach(d.rings||d.paths,function(a,e){h.some(a,function(b){if(!(180>b[0])){var b=0,c,f=a.length,g;for(c=0;c<f;c++)g=a[c][0],b=g>b?g:b;b=-360*t(b,180);f=a.length;for(c=0;c<f;c++)g=d.getPoint(e,c),d.setPoint(e,c,g.offset(b,0))}return!0})});b===c?d.rings?h.forEach(d.rings,function(d){a[b]=a[b].addRing(d)}):h.forEach(d.paths,function(d){a[b]=a[b].addPath(d)}):(c=b,a[b]=d)});return a}function E(a,f,c,b){var e=new B;e.addCallbacks(c,b);var d=[],l=[],m,n,j,i,g,k,u,
r,o=0;h.forEach(a,function(a){if(a){if(!m)m=a.spatialReference,n=m._getInfo(),i=(j=m._isWebMercator())?2.0037508342788905E7:180,g=j?-2.0037508342788905E7:-180,k=j?102100:4326,u=new s({paths:[[[i,g],[i,i]]],spatialReference:{wkid:k}}),r=new s({paths:[[[g,g],[g,i]]],spatialReference:{wkid:k}});if(n){var b=I.fromJson(a.toJson()),c=a.getExtent();"point"===a.type?d.push(A(b,i,g)):"multipoint"===a.type?(b.points=h.map(b.points,function(a){return A(a,i,g)}),d.push(b)):"extent"===a.type?(b=c._normalize(null,
null,n),d.push(b.rings?new x(b):b)):(a=t(c.xmin,g)*2*i,b=0===a?b:y(b,a),c=c.offset(a,0),c.intersects(u)&&c.xmax!==i?(o=c.xmax>o?c.xmax:o,b=z(b,j),l.push(b),d.push("cut")):c.intersects(r)&&c.xmin!==g?(o=c.xmax*2*i>o?c.xmax*2*i:o,b=z(b,j,360),l.push(b),d.push("cut")):d.push(b))}else d.push(a)}else d.push(a)});for(var c=new s,b=t(o,i),p=-90,q=b;0<b;){var v=-180+360*b;c.addPath([[v,p],[v,-1*p]]);p*=-1;b--}0<l.length&&0<q?f?f.cut(l,c,function(b){l=D(l,b);var c=[];h.forEach(d,function(b,e){if("cut"===b){var f=
l.shift();a[e].rings&&1<a[e].rings.length&&f.rings.length>=a[e].rings.length?(d[e]="simplify",c.push(f)):d[e]=!0===j?w.geographicToWebMercator(f):f}});0<c.length?f.simplify(c,function(a){h.forEach(d,function(b,c){"simplify"===b&&(d[c]=!0===j?w.geographicToWebMercator(a.shift()):a.shift())});e.callback(d)},function(a){e.errback(a)}):e.callback(d)},function(a){e.errback(a)}):e.errback(Error("esri.geometry.normalizeCentralMeridian: 'geometryService' argument is missing.")):(h.forEach(d,function(a,b){if("cut"===
a){var c=l.shift();d[b]=!0===j?w.geographicToWebMercator(c):c}}),e.callback(d));return e}function r(a,f,c,b){var e=!1,d;if(k.isObject(a)&&a)k.isArray(a)?a.length&&((d=a[0]&&a[0].declaredClass)&&-1!==d.indexOf("Graphic")?(a=h.map(a,function(a){return a.geometry}),e=a.length?!0:!1):d&&-1!==d.indexOf("esri.geometry.")&&(e=!0)):(d=a.declaredClass)&&-1!==d.indexOf("FeatureSet")?(a=h.map(a.features||[],function(a){return a.geometry}),e=a.length?!0:!1):d&&-1!==d.indexOf("esri.geometry.")&&(e=!0);e&&f.push({index:c,
property:b,value:a})}function F(a,f){var c=[];h.forEach(f,function(b){var e=b.i,d=a[e],b=b.p,f;if(k.isObject(d)&&d)if(b)if("*"===b[0])for(f in d)d.hasOwnProperty(f)&&r(d[f],c,e,f);else h.forEach(b,function(a){r(k.getObject(a,!1,d),c,e,a)});else r(d,c,e)});return c}function G(a,f){var c=0,b={};h.forEach(f,function(e){var d=e.index,f=e.property,h=e.value,n=h.length||1,j=a.slice(c,c+n);k.isArray(h)||(j=j[0]);c+=n;delete e.value;f?(b[d]=b[d]||{},b[d][f]=j):b[d]=j});return b}return{normalizeCentralMeridian:E,
_foldCutResults:D,_prepareGeometryForCut:z,_offsetMagnitude:t,_pointNormalization:A,_updatePolyGeometry:y,_straightLineDensify:C,_createWrappers:function(a){var f=k.isObject(a)?a.prototype:k.getObject(a+".prototype");h.forEach(f.__msigns,function(a){var b=f[a.n];f[a.n]=function(){var e=this,d=[],f,m=new B(v._dfdCanceller);a.f&&v._fixDfd(m);for(f=0;f<a.c;f++)d[f]=arguments[f];var k={dfd:m};d.push(k);var j,i=[],g;e.normalization&&!e._isTable&&(j=F(d,a.a),h.forEach(j,function(a){i=i.concat(a.value)}),
i.length&&(g=E(i,H.defaults.geometryService)));g?(m._pendingDfd=g,g.addCallbacks(function(a){if(!m.canceled)k.assembly=G(a,j),m._pendingDfd=b.apply(e,d)},function(b){var f=e.declaredClass;f&&-1!==f.indexOf("FeatureLayer")?e._resolve([b],null,d[a.e],m,!0):e._errorHandler(b,d[a.e],m)})):m._pendingDfd=b.apply(e,d);return m}})},_disassemble:F,_addToBucket:r,_reassemble:G}});