//>>built
define(["dojo/_base/declare","dojo/_base/array","dojo/_base/lang","dojo/has","esri/kernel","esri/lang","esri/SpatialReference","esri/geometry/Geometry","esri/geometry/Point","esri/geometry/Extent","esri/geometry/mathUtils"],function(x,m,h,B,C,y,z,A,j,s,v){var w={type:"polygon",rings:null},k=x(A,{declaredClass:"esri.geometry.Polygon",constructor:function(a){h.mixin(this,w);this.rings=[];this._ring=0;if(a&&(a.rings?h.mixin(this,a):this.spatialReference=a,this.spatialReference))this.spatialReference=new z(this.spatialReference);
this.verifySR()},_extent:null,addRing:function(a){this._extent=null;this._ring=this.rings.length;this.rings[this._ring]=[];h.isArray(a[0])?m.forEach(a,this._addPointArr,this):m.forEach(a,this._addPoint,this);return this},_addPointArr:function(a){this.rings[this._ring].push(a)},_addPoint:function(a){this.rings[this._ring].push([a.x,a.y])},_insertPoints:function(a,b){this._extent=null;this._ring=b;this.rings[this._ring]||(this.rings[this._ring]=[]);m.forEach(a,this._addPoint,this)},_validateInputs:function(a,
b){return null!==a&&void 0!==a&&(0>a||a>=this.rings.length)||null!==b&&void 0!==a&&(0>b||b>=this.rings[a].length)?!1:!0},getPoint:function(a,b){if(this._validateInputs(a,b))return new j(this.rings[a][b],this.spatialReference)},setPoint:function(a,b,c){if(this._validateInputs(a,b))return this._extent=null,this.rings[a][b]=[c.x,c.y],this},insertPoint:function(a,b,c){if(this._validateInputs(a)&&y.isDefined(b)&&0<=b&&b<=this.rings[a].length)return this._extent=null,this.rings[a].splice(b,0,[c.x,c.y]),
this},removeRing:function(a){if(this._validateInputs(a,null)){this._extent=null;var a=this.rings.splice(a,1)[0],b,c=a.length,d=this.spatialReference;for(b=0;b<c;b++)a[b]=new j(a[b],d);return a}},removePoint:function(a,b){if(this._validateInputs(a,b))return this._extent=null,new j(this.rings[a].splice(b,1)[0],this.spatialReference)},getExtent:function(){var a;if(this._extent)return a=new s(this._extent),a._partwise=this._partwise,a;a=this.rings;var b=a.length;if(b&&a[0].length){var c,d,e,g,i,f,l,n,
t=g=a[0][0][0],u=i=a[0][0][1],k=Math.min,h=Math.max,j=this.spatialReference,m=[],o,p,q,r;for(f=0;f<b;f++){c=a[f];o=p=c[0]&&c[0][0];q=r=c[0]&&c[0][1];n=c.length;for(l=0;l<n;l++)d=c[l],e=d[0],d=d[1],t=k(t,e),u=k(u,d),g=h(g,e),i=h(i,d),o=k(o,e),q=k(q,d),p=h(p,e),r=h(r,d);m.push(new s({xmin:o,ymin:q,xmax:p,ymax:r,spatialReference:j?j.toJson():null}))}this._extent={xmin:t,ymin:u,xmax:g,ymax:i,spatialReference:j?j.toJson():null};this._partwise=1<m.length?m:null;a=new s(this._extent);a._partwise=this._partwise;
return a}},contains:function(a){var b=this.rings,c,d=!1,e,g,i,f,l,n,k=b.length;c=this.spatialReference;e=a.spatialReference;var h=a.x,a=a.y;c&&e&&!c.equals(e)&&c._canProject(e)&&(a=c.isWebMercator()?j.lngLatToXY(h,a):j.xyToLngLat(h,a,!0),h=a[0],a=a[1]);for(n=0;n<k;n++){c=b[n];i=c.length;for(l=f=0;l<i;l++)if(f++,f===i&&(f=0),e=c[l],g=c[f],(e[1]<a&&g[1]>=a||g[1]<a&&e[1]>=a)&&e[0]+(a-e[1])/(g[1]-e[1])*(g[0]-e[0])<h)d=!d}return d},isClockwise:function(a){var b=0,c,d=a.length,e=h.isArray(a[0])?function(a,
b){return a[0]*b[1]-b[0]*a[1]}:function(a,b){return a.x*b.y-b.x*a.y};for(c=0;c<d;c++)b+=e(a[c],a[(c+1)%d]);return 0>=b/2},isSelfIntersecting:function(a){var a=a||this,b,c,d,e,g,i,f,l=a.rings.length;for(d=0;d<l;d++){for(b=0;b<a.rings[d].length-1;b++){g=[[a.rings[d][b][0],a.rings[d][b][1]],[a.rings[d][b+1][0],a.rings[d][b+1][1]]];for(c=d+1;c<l;c++)for(e=0;e<a.rings[c].length-1;e++)if(i=[[a.rings[c][e][0],a.rings[c][e][1]],[a.rings[c][e+1][0],a.rings[c][e+1][1]]],(f=v._getLineIntersection2(g,i))&&!(f[0]===
g[0][0]&&f[1]===g[0][1]||f[0]===i[0][0]&&f[1]===i[0][1]||f[0]===g[1][0]&&f[1]===g[1][1]||f[0]===i[1][0]&&f[1]===i[1][1]))return!0}e=a.rings[d].length;if(!(4>=e))for(b=0;b<e-3;b++){var h=e-1;0===b&&(h=e-2);g=[[a.rings[d][b][0],a.rings[d][b][1]],[a.rings[d][b+1][0],a.rings[d][b+1][1]]];for(c=b+2;c<h;c++)if(i=[[a.rings[d][c][0],a.rings[d][c][1]],[a.rings[d][c+1][0],a.rings[d][c+1][1]]],(f=v._getLineIntersection2(g,i))&&!(f[0]===g[0][0]&&f[1]===g[0][1]||f[0]===i[0][0]&&f[1]===i[0][1]||f[0]===g[1][0]&&
f[1]===g[1][1]||f[0]===i[1][0]&&f[1]===i[1][1]))return!0}}return!1},toJson:function(){var a={rings:h.clone(this.rings)},b=this.spatialReference;if(b)a.spatialReference=b.toJson();return a}});k.defaultProps=w;k.createEllipse=function(a){var b=a.center.x,c=a.center.y,d=a.longAxis,e=a.shortAxis,g=a.numberOfPoints,i=a.map,f,h,j,a=[],m=2*Math.PI/g;for(h=0;h<g;h++)f=Math.cos(h*m),j=Math.sin(h*m),f=i.toMap({x:d*f+b,y:e*j+c}),a.push(f);a.push(a[0]);b=new k(i.spatialReference);b.addRing(a);return b};k.createCircle=
function(a){return k.createEllipse({center:a.center,longAxis:a.r,shortAxis:a.r,numberOfPoints:a.numberOfPoints,map:a.map})};return k});